### ISSUE TITLE
pdf doesn't display the whole function.

### ISSUE THREAD

**Issue by heinosasshallik** [radareorg/radare2#19119] opened 2021-09-20 12:54 UTC
## Environment

```sh
radare2 5.4.2 1 @ linux-x86-64 git.
commit: 84e6cc6a21ec1c816d4d3eb3510d2cdc94330414 build: 2021-09-20__04:53:52
Linux x86_64

```

## Description

Running ` pdf @ sym.grab_files_abi:cxx11___ `  doesn't display the whole function (up until the `ret`). It falls short.

```
[0x7f36cb27a100]> pdf @ sym.grab_files_abi:cxx11___ 
            ; CALL XREF from main @ 0x559b7fea78cb
┌ 124: sym.grab_files_abi:cxx11___ (int64_t arg1);
│           ; var int64_t var_58h @ rbp-0x58
│           ; var int64_t var_50h @ rbp-0x50
│           ; var int64_t var_30h @ rbp-0x30
│           ; var int64_t var_18h @ rbp-0x18
│           ; arg int64_t arg1 @ rdi
│           0x559b7fea72fb      f30f1efa       endbr64                 ; grab_files[abi:cxx11]()
│           0x559b7fea72ff      55             push rbp
│           0x559b7fea7300      4889e5         mov rbp, rsp
│           0x559b7fea7303      53             push rbx
│           0x559b7fea7304      4883ec58       sub rsp, 0x58
│           0x559b7fea7308      48897da8       mov qword [var_58h], rdi ; arg1
│           0x559b7fea730c      64488b042528.  mov rax, qword fs:[0x28]
│           0x559b7fea7315      488945e8       mov qword [var_18h], rax
│           0x559b7fea7319      31c0           xor eax, eax
│           0x559b7fea731b      488d45b0       lea rax, [var_50h]
│           0x559b7fea731f      4889c7         mov rdi, rax
│           0x559b7fea7322      e8f0f9ffff     call sym get_filenames[abi:cxx11]() ; sym.get_filenames_abi:cxx11___
│           0x559b7fea7327      488d55b0       lea rdx, [var_50h]
│           0x559b7fea732b      488d45d0       lea rax, [var_30h]
│           0x559b7fea732f      4889d6         mov rsi, rdx
│           0x559b7fea7332      4889c7         mov rdi, rax
│           0x559b7fea7335      e820130000     call sym std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::vector(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ; sym.std::vector_std::__cxx11::basic_string_char__std::char_traits_char___std::allocator_char_____std::allocator_std::__cxx11::basic_string_char__std::char_traits_char___std::allocator_char_______::vector_std::vector_std::__cxx11::basic_string_char__std::char_traits_char___std::allocator_char_____std::allocator_std::__cxx11::basic_string_char__std::char_traits_char___std::allocator_char________const_
│           0x559b7fea733a      488b45a8       mov rax, qword [var_58h]
│           0x559b7fea733e      488d55d0       lea rdx, [var_30h]
│           0x559b7fea7342      4889d6         mov rsi, rdx
│           0x559b7fea7345      4889c7         mov rdi, rax
│           0x559b7fea7348      e898fdffff     call sym read_files(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) ; sym.read_files_std::vector_std::__cxx11::basic_string_char__std::char_traits_char___std::allocator_char_____std::allocator_std::__cxx11::basic_string_char__std::char_traits_char___std::allocator_char________
│           0x559b7fea734d      488d45d0       lea rax, [var_30h]
│           0x559b7fea7351      4889c7         mov rdi, rax
│           0x559b7fea7354      e8950f0000     call sym std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector() ; sym.std::vector_std::__cxx11::basic_string_char__std::char_traits_char___std::allocator_char_____std::allocator_std::__cxx11::basic_string_char__std::char_traits_char___std::allocator_char_______::vector__
│           0x559b7fea7359      488d45b0       lea rax, [var_50h]
│           0x559b7fea735d      4889c7         mov rdi, rax
│           0x559b7fea7360      e8890f0000     call sym std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector() ; sym.std::vector_std::__cxx11::basic_string_char__std::char_traits_char___std::allocator_char_____std::allocator_std::__cxx11::basic_string_char__std::char_traits_char___std::allocator_char_______::vector__
│           0x559b7fea7365      90             nop
│           0x559b7fea7366      488b45e8       mov rax, qword [var_18h]
│           0x559b7fea736a      644833042528.  xor rax, qword fs:[0x28]
│       ┌─< 0x559b7fea7373      743a           je 0x559b7fea73af
└      ┌──< 0x559b7fea7375      eb33           jmp loc.559b7fea73aa
[0x7f36cb27a100]> 
```

The ret is at 0x559b7fea73b9 but pdf stops displaying at  0x559b7fea7375.

## Test

**Note**: Don't run this executable on your own machine. It will try to send your ssh keys over an HTTP request. Also I sent it over the network and I cannot guarantee that I haven't been MitM'd.

```
r2 -A -d ./sketchy
pdf @ sym.grab_files_abi:cxx11___ 
```
[sketchy.zip](https://github.com/radareorg/radare2/files/7195834/sketchy.zip)

**Comment by trufae** [comment] 2021-09-20 13:15
Pdf only works well for linear functions, better use pdr for such cases. But ill look into that issue and see how to address it asap

**Comment by trufae** [comment] 2021-09-25 10:40
Unfortunely, that's not a bug in pdf, but in the analysis. pdf is showing the whole function. As a workaround you can use `a2f` instead of `af` , which is a rewritten from scratch analysis loop that doesnt handle all the cases that `af` do. but it works for your case.

you can use e anal.a2f=true and then use aaa or just a2f in the offset of that function. a2f is experimental and may fail in other situations, but the code is cleaner and it may improve over time.

Thanks for the test case.

Can I add this file into the testsuite?

**Comment by heinosasshallik** [comment] 2021-09-25 19:47
> Can I add this file into the testsuite?

Yeah, sure. 

I'll just keep using `pdf` for now. Interestingly, after recompiling the executable and reinstalling the radare2 package a bunch of times (by rebuilding a VM image basically), it actually eventually started working correctly. Not sure what that's about.

**Comment by trufae** [comment] 2021-11-22 11:41
Closing as it seems to work if i undertood u correctly

**Closed** 2021-11-22 11:41 UTC
