### ISSUE TITLE
ihj/iHj command output is not valid JSON

### ISSUE THREAD

**Issue by whoami-defnotme** [radareorg/radare2#20772] opened 2022-09-18 10:50 UTC
## Environment

```sh
Sun Sep 18 18:44:23 +08 2022
radare2 5.7.8 29058 @ darwin-arm-64 git.5.7.8-78-g15d337a70a
commit: 15d337a70a0a266676da6c5e3a7d22cb8ef5f049 build: 2022-09-18__18:12:39
Darwin arm64
```

## Description

I'm trying to access a target Mach-O's headers in JSON format but keep getting a parse error because the supposed JSON contains hex values:

```
[0x100001f60]> ihj | jq
parse error: Invalid numeric literal at line 1, column 496
```

## Test

```
# Try to parse JSON and get the error
[0x100001f60]> ihj | jq
parse error: Invalid numeric literal at line 1, column 496

# Cat the supposed JSON out to tmp
[0x100001f60]> ihj > /private/tmp/headers.json

# Open the tmp file and find out what's happening at line 1, column 496
> vim /private/tmp/headers.json
[{"name":"header","vaddr":4294967296,"paddr":4294967296,"comment":"mach0_header","format":"mach0_header","pf":[{"name":"magic","type":"x","offset":4294967296,"value":4277009103},{"name":"cputype","type":"x","offset":4294967300,"value":16777223},{"name":"cpusubtype","type":"x","offset":4294967304,"value":2147483651},{"name":"filetype","type":"E","offset":4294967308,"value":2,"label":"MH_EXECUTE","enum":"mach0_header_filetype"},{"name":"ncmds","type":"d","offset":4294967312,"value":0x00000017}

# Discover hex values, which JSON doesn't support; sad face :-(
```

**Comment by trufae** [comment] 2022-09-18 23:47
Can't reproduce with any bin i tried. can you share the file you are using and verify if this is still happening on git?

**Comment by whoami-defnotme** [comment] 2022-09-19 00:18
Just updated from git again and yes, still happening:

```
> r2 -v
radare2 5.7.8 29063 @ darwin-arm-64 git.5.7.8-83-g563f3538bd
commit: 563f3538bd0a7b29433ebaa02c3c1d58a8f529be build: 2022-09-19__08:14:57
 
> r2 -A 18e57fa6e009cd69be100fd6f542aa343d681ffe6c222bb692872502b21fa5f7
INFO: Analyze all flags starting with sym. and entry0 (aa)
INFO: Analyze all functions arguments/locals
INFO: Analyze function calls (aac)
INFO: Analyze len bytes of instructions for references (aar)
INFO: Check for objc references (aao)
INFO: Parsing metadata in ObjC to find hidden xrefs
INFO: Found 0 objc xrefs
INFO: Found 0 objc xrefs in 0 dwords
INFO: Finding and parsing C++ vtables (avrr)
INFO: Type matching analysis for all functions (aaft)
INFO: Propagate noreturn information (aanr)
INFO: Use -AA or aaaa to perform additional experimental analysis
 -- Ask not what r2 can do for you - ask what you can do for r2
[0x100001f60]> ihj | jq
parse error: Invalid numeric literal at line 1, column 496
```

**Comment by whoami-defnotme** [comment] 2022-09-19 00:19
[bin.zip](https://github.com/radareorg/radare2/files/9595552/bin.zip)

It's a malware binary so usual caveats there; password is `infected`

**Comment by trufae** [comment] 2022-09-19 08:54
fixed in a pr. thanks! this code should be refactored to use the PJ api to avoid such issues for a proper fix

**Closed** 2022-09-19 09:06 UTC
