### ISSUE TITLE
Radare2 can't find XREF, found by x64dbg and IDA

### ISSUE THREAD

**Issue by ripxorip** [radareorg/radare2#15315] opened 2019-10-20 13:02 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Mac
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 23167 @ darwin-x86-64 git.3.9.0-208-gda18e5aad
commit: da18e5aadcecd17206314860dd2ff52d2ffaa585 build: 2019-10-15__16:11:39

### Expected behavior
In my crackme I have a reference from text to data: `lea edx, [esi*4 + 0x582b80]`. After running aar in radare I can find most of the other references but not to this particular one. I tested the same thing on x64dbg (right after it has been loaded to memory) on Windows and the reference is found. The same for IDA.

### Actual behavior
To find this reference in radare2 as well or is there some other analysis I should perform in order to catch this ref? One of the references is at 0x0040115f

### Steps to reproduce the behavior 
[CrackMeTwo.zip](https://github.com/radareorg/radare2/files/3747874/CrackMeTwo.zip)
Perform aar and seek to 0x582b80, then list references with axt.

**Comment by radare** [comment] 2019-10-20 21:36
the value of esi depends on ecx, which is an argument passed to the function when called, and each of those callers compute the value of ecx differently and taking it as arguments too, so i dont see why this instruction should have any specific reference withouht using a debugger.

aar wont find any reference here because the instruction is using a register that can have any value. using aae it may work because its using emulation, but for this case as long as the esi can have multiple values it cant be compmuted that way either because emulation doesnt goes multiple times recursively in r2, just once.

what ida does here? can you show a screenshot or something? using the debugger in r2 u may get the same as x64dbg, just enable the emu.str=true eval variable

**Comment by ripxorip** [comment] 2019-10-21 15:12
Of course, here it is 
<img width="744" alt="Screenshot 2019-10-21 at 17 07 38" src="https://user-images.githubusercontent.com/3415007/67217661-6a8b6b80-f425-11e9-86a0-5cacb70f6a17.png">
I reasoned just like when I started digging in to the disassembly but somehow IDA and x64dbg is able to pull it off. x64xbg found the reference **before** I let it continue from the entry point so it too must have figured it out in another way rather than waiting for the registers to get the proper values. The crackme is compiled with MSVC, could it be some specific MSVC ABI that can be known? Thank you for getting back to me, let me know if I can support in some other way.

**Comment by radare** [comment] 2019-10-21 19:17
Thats a lie. That xref is pointing to the base address of that instruction, but thats not correct because it depends on a value of a register that can have multiple values, not just one. I can make r2 show this reference if u like but its not correct

**Comment by ripxorip** [comment] 2019-10-22 04:26
Yeah because you dont know the value of esi*4 without running some kind of emulation/debugging right? x64dbg finds the reference in the same way. I am the author of the crackme and it is indeed the **correct** XREF. Isn't it possible that in that context esi*4 will hold the address to some location in memory so that the offset to the actual data is the same independent of where it has been dynamically loaded to?

**Comment by karliss** [comment] 2019-10-22 23:08
In this case using xrefs widget it's easy to see that all places calling the function set different values for ecx but all of them are small <0x100.

The equivalent code is something like this:
```
int global_array[144];
int array_2[100];
int foo(ecx, edx)
{
    int* ptr = &global_array[ecx]
    for (int j=ecx; j<edx; j++,ptr++) {
        x = *ptr;
    }
}

void bar1()
{
    foo(0, 10);
}
void bar2()
{
    foo(10, 30);
}
void bar3()
{
    foo(30, 80);
}
...
void bar5(){}
```

Required emulation length from all the callsites of `foo` seems impractical for basic analysis. I guess that IDA and x64dbg with more or less heuristics just assumes that ecx is 0 or some kind of base offset.

For code  pattern similar to `lea edx, [esi*4 + 0x582b80]` i can think of multiple possible situations
* 0x582b80 contains an array and esi is an index, xref to 0x582b80 is reasonable
* it is a weird arithmetic expression - unlikely if .reloc section contains a relocation for this instruction
* 0x582b80 address get used for accesing multiple objects (global_array[144] to array_2[0]) - if written manually that would be very bad code, not sure if compiler would generate something like that for normal code
* if the register expression didn't have *4 multiplier and this were a position independent code register could be some kind of base offset , in this case xref would be reasonable
* if integer offset were smaller it could be an instruction for accessing a field in object, no xrefs applicable
* this is crazy obfuscated code and the instruction could be referring to anything

There is room for doing better than just assuming that registers are 0.

Isn't r2 already making a bunch of false positive xrefs in similar situations where constant is even less pointer like?

![Screenshot from 2019-10-23 02-03-30](https://user-images.githubusercontent.com/7101031/67342044-e8409b80-f539-11e9-98a5-475773e14daa.png)

**Comment by radare** [comment] 2019-10-23 11:35
kk fixing

**Comment by radare** [comment] 2019-10-23 11:44
Fixed in https://github.com/radareorg/radare2/pull/15336

**Comment by radare** [comment] 2019-10-23 11:45
will merge it when travis finishes the run

**Closed by radare** 2019-10-23 11:44 UTC

**Comment by radare** [comment] 2019-10-23 11:52
can you submit a test for r2r? maybe just providing a smaller binary, because this is 2MB and we dont want to make r2r that big for just a test

thanks!

**Comment by ripxorip** [comment] 2019-10-23 12:15
Great, thank you very much ! Of course, I will submit a test with a minimal binary to verify this.

**Comment by radare** [comment] 2019-10-23 13:05
see https://github.com/radareorg/radare2-regressions/issues/1998

**Comment by ripxorip** [comment] 2019-10-23 15:09
I managed to produce an 10kb binary that has the same behaviour. Although this time ebx is used instead. Will pull the latest and do a manual test before submitting a test for regression.

**Comment by radare** [comment] 2019-10-23 16:31
thank you!
