### ISSUE TITLE
af cmd overwrite flag to wrong address

### ISSUE THREAD

**Issue by dark-lbp** [radareorg/radare2#15387] opened 2019-10-29 23:12 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS 10.14.6
| File format of the file you reverse (mandatory)      | etc.
| Architecture/bits of the file (mandatory)            | ARM/32.
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0 93 @ darwin-x86-64 git.4.0.0
commit: 0257d4be10ef46fba0810beafd678ccd2724d429 build: 2019-10-30__06:54:08

### Expected behavior
`r2 -a arm -b 32 -m 0xF2003FE4 image_vx6_arm_little_endian.bin`
```
0xf2003fe4]> fs functions; f sysInit 1 @ 0xF2004000
[0xf2003fe4]> af sysInit @ 0xF2004000
[0xf2003fe4]> fs functions; f usrInit 1 @ 0xF20141B8
[0xf2003fe4]> af usrInit @ 0xF20141B8
[0xf2003fe4]> fs functions; f usrKernelInit 1 @ 0xF2013594
[0xf2003fe4]> af usrKernelInit @ 0xF2013594
[0xf2003fe4]> fs
    0 . classes
    3 * functions
    0 . relocs
    0 . sections
    0 . segments
    0 . symbols
[0xf2003fe4]> f
0xf2004000 1 sysInit
0xf2013594 1 usrKernelInit
0xf20141b8 1 usrInit
```

### Actual behavior
`r2 -a arm -b 32 -m 0xF2003FE4 image_vx6_arm_little_endian.bin`
```
0xf2003fe4]> fs functions; f sysInit 1 @ 0xF2004000
[0xf2003fe4]> af sysInit @ 0xF2004000
[0xf2003fe4]> fs functions; f usrInit 1 @ 0xF20141B8
[0xf2003fe4]> af usrInit @ 0xF20141B8
[0xf2003fe4]> fs functions; f usrKernelInit 1 @ 0xF2013594
[0xf2003fe4]> af usrKernelInit @ 0xF2013594
[0xf2003fe4]> fs
    0 . classes
    3 * functions
    0 . relocs
    0 . sections
    0 . segments
    0 . symbols

# Function address should be different
[0xf2003fe4]> f
0xf2004000 66148 sysInit
0xf2004000 66148 usrInit
0xf2004000 66148 usrKernelInit
```
### Additional Logs, screenshots, source-code,  configuration dump, ...
[image_vx6_arm_little_endian.bin.zip](https://github.com/radareorg/radare2/files/3786158/image_vx6_arm_little_endian.bin.zip)

**Comment by radare** [comment] 2019-11-14 22:40
this happens because i never used the 'af' argument  and i think there are no tests for this. you can do it like this:

```
fs functions
f sysInit 1 @ 0xF2004000
f usrInit 1 @ 0xF20141B8
f usrKernelInit 1 @ 0xF2013594
af@sysInit
af@usrInit
af@usrKernelInit
afl
f
```

PD: im fixing this in a PR

**Comment by radare** [comment] 2019-11-15 01:10
Fixed in https://github.com/radareorg/radare2/pull/15466

**Comment by radare** [comment] 2019-11-15 16:10
i merged the PR. please test it, as well as using the new anal.jmp.tailcall variable which can have 3 values:

0: default, do nothing, same as before
-X: check if branch destination is a function prelude
X: check destination length to consider function or bb

**Closed by radare** 2019-11-15 16:10 UTC

**Comment by dark-lbp** [comment] 2019-11-16 08:49
Thanks, below is the tests, flags address is correct now. I use `af@sysInit` to analyze function at  0xF2004000 but actually `sysInit` is not a function(It's assembly language start-up routine of VxWorks system), this might cause the problem.

PS: It that possible to disable the output like `--- sysInit f2004000` ? I use r2pipe to analyze firmware there will be thousands function.

## Using default anal.jmp.tailcall

`r2 -a arm -b 32 -m 0xF2003FE4 image_vx6_arm_little_endian.bin`
```
[0xf2003fe4]> fs functions
[0xf2003fe4]> f sysInit 1 @ 0xF2004000
[0xf2003fe4]> f usrInit 1 @ 0xF20141B8
[0xf2003fe4]> f usrKernelInit 1 @ 0xF2013594
[0xf2003fe4]> af@sysInit
--- sysInit f2004000
[0xf2003fe4]> af@usrInit
--- sysInit f2004000
[0xf2003fe4]> af@usrKernelInit
--- sysInit f2004000
[0xf2003fe4]> afl
0xf2004000    9 66148 -> 620  sysInit
[0xf2003fe4]> fs
    0 . classes
    3 * functions
    0 . relocs
    0 . sections
    0 . segments
    0 . symbols
[0xf2003fe4]> f
0xf2004000 66148 sysInit
0xf2013594 1 usrKernelInit
0xf20141b8 1 usrInit
[0xf2003fe4]>
```

## With anal.jmp.tailcall=-X

```
[0xf2003fe4]> e anal.jmp.tailcall=-X
[0xf2003fe4]> e anal.jmp.tailcall
-X
[0xf2003fe4]> fs functions
[0xf2003fe4]> f sysInit 1 @ 0xF2004000
[0xf2003fe4]> f usrInit 1 @ 0xF20141B8
[0xf2003fe4]> f usrKernelInit 1 @ 0xF2013594
[0xf2003fe4]> af@sysInit
--- sysInit f2004000
[0xf2003fe4]>  af@usrInit
--- sysInit f2004000
[0xf2003fe4]> af@usrKernelInit
--- sysInit f2004000
[0xf2003fe4]> afl
0xf2004000    9 66148 -> 620  sysInit
[0xf2003fe4]> f
0xf2004000 66148 sysInit
0xf2013594 1 usrKernelInit
0xf20141b8 1 usrInit
[0xf2003fe4]>
```

## With anal.jmp.tailcall=-X

```
[0xf2003fe4]> e anal.jmp.tailcall=-X
[0xf2003fe4]> e anal.jmp.tailcall
-X
[0xf2003fe4]> fs functions
[0xf2003fe4]> f sysInit 1 @ 0xF2004000
[0xf2003fe4]> f usrInit 1 @ 0xF20141B8
[0xf2003fe4]> f usrKernelInit 1 @ 0xF2013594
[0xf2003fe4]> af@sysInit
--- sysInit f2004000
[0xf2003fe4]>  af@usrInit
--- sysInit f2004000
[0xf2003fe4]> af@usrKernelInit
--- sysInit f2004000
[0xf2003fe4]> afl
0xf2004000    9 66148 -> 620  sysInit
[0xf2003fe4]> f
0xf2004000 66148 sysInit
0xf2013594 1 usrKernelInit
0xf20141b8 1 usrInit
[0xf2003fe4]>
```

**Comment by radare** [comment] 2019-11-16 10:20
Ouch those are debug printf left overs. Yes ill remove them now. Also can you submit all those tests as a PR in the radare2-regressions repo?

Thanks!! And sorry for the delay :)

**Comment by dark-lbp** [comment] 2019-11-16 12:50
Sure, I can find some examples in the radare2-regressions repo.

**Comment by radare** [comment] 2019-11-17 13:18
Yup!
