### ISSUE TITLE
!! crash on windows

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#17155] opened 2020-06-27 06:08 UTC
as stated here https://github.com/radareorg/radare2/pull/17143 this command crashes on windows

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows
| File format of the file you reverse (mandatory)      | ?
| Architecture/bits of the file (mandatory)            | ?
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 26778 @ darwin-x86-64 git.4.4.0-331-gf68cb5c6f commit: f68cb5c6f162a039e7e586611df877ec7c4cdcca build: 2020-06-22__15:22:50

### Expected behavior

!!r2 -v -> should work

### Actual behavior

!!r2 -v -> seems to crash on windows

### Steps to reproduce the behavior 

see behaviour section

### Additional Logs, screenshots, source-code,  configuration dump, ...
nope

**Comment by pelijah** [comment] 2020-07-06 21:13
`!!radare2 -v` works fine
`!!r2.bat -v` works fine
`!!r2 -v` doesn't work (no crash) because `r2` is a shell script

**Comment by XVilka** [comment] 2020-07-07 05:02
Not a bug then. Closing.

**Closed by XVilka** 2020-07-07 05:02 UTC
Labels: Windows
