### ISSUE TITLE
F4 and F2 not working in V mode

### ISSUE THREAD

**Issue by bannsec** [radareorg/radare2#14260] opened 2019-06-09 17:20 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 244 @ linux-x86-64 git.3.5.1-194-gb435d19 commit: b435d195152c32206d436fc0f4c6dae0c123879b build: 2019-06-09__17:15:13

### Expected behavior
 - When I press F4 in V mode, it should execute to my cursor
 - When I press F2 in V mode, it should set a breakpoint

### Actual behavior
 - Not sure what either of those actually are doing, but it's not that.

### Steps to reproduce the behavior 
```
r2 -A /bin/ls
ood
dbm ls main
dc
V
<Try to use F2 or F4>
```

**Comment by XVilka** [comment] 2019-06-21 08:57
F2 works for me, F4 doesn't. @radare do you have any ideas?

**Comment by radare** [comment] 2019-06-21 09:07
probably different escape codes sent to the terminal depending on the configuration, i built a stupid C program to grab keystrokes and print them in hexa for debugging this when i started RCons. maybe you can do this or add some printfs in rcons_readchar to see whats up

**Comment by radare** [comment] 2019-09-15 10:54
@deepakchethan can you take a look at this?

e key.f2=!sleep 3
V
F2

**Comment by radare** [comment] 2019-09-16 10:39
works for me on linux, fails on mac, probably ebcause of different escape codes or just the F key is handled by the terminal itself. can you specify which terminal emulator are you using?

**Comment by bannsec** [comment] 2019-09-16 20:11
I'm using gnu screen over putty. It would appear f4 == `^[[14~` and f2 == `^[[12~` on my setup.

**Comment by radare** [comment] 2019-10-23 11:55
it just depends on the terminal. feel free to improve the F key handling on more consoles.

see libr/cons/input.c 220 and add the changesss needed to handle more F keys please

<img width="722" alt="Screenshot 2019-10-23 at 13 54 49" src="https://user-images.githubusercontent.com/917142/67390302-b01e7480-f59c-11e9-97a8-48215334fb00.png">

**Comment by radare** [comment] 2019-10-23 11:56
this is an easy issue to fix but needs reproducer/test, so its easier to fix than to report.. can you submit a pr before sunday?

**Comment by bannsec** [comment] 2019-10-23 12:48
I'll take a look. Next couple weeks are super busy for me though.

**Comment by radare** [comment] 2019-10-23 17:27
fixed in https://github.com/radareorg/radare2/pull/15345

pleaes confirm

**Comment by radare** [comment] 2019-10-23 17:27
rls is sunday, a couple of weeks for 10 locs is toomuch, seems to work fine on mac btw

**Comment by radare** [comment] 2019-10-24 00:21
Its merged. Just test in master

**Comment by bannsec** [comment] 2019-10-24 14:35
Ok, so F2 works now. F4 does not still.

Also of note, just pulled from master and "V!" is completely borked on every binary I try it on. It appears to get into some loop that doesn't exist, and when i see a partial ascii graph it's has a million jump lines back to the top. Simple repro on that one is just r2 -A /bin/ls and attempt to V! on main.

**Comment by radare** [comment] 2019-10-24 15:28
F keys only work in visual and panels. On the promot they show the escape codes only

**Comment by radare** [comment] 2019-10-24 15:28
Was this your initial complain? Because the issue specifies V mode

We can make f keys work in prompt too

**Comment by bannsec** [comment] 2019-10-24 15:32
Nope. That's just what my F2 and F4 are sending (cat >/dev/null then F4 to discover sending). Visual mode F4 does not work still is what i was mentioning.

**Comment by radare** [comment] 2019-10-25 16:36
all the keys are working fine on mac and linux on xterm, vte and iterm. so imho the problem is in your side.

F2 and F4 have no command defined by default, so if you didnt touched the key eval vars thats expected

**Closed by radare** 2019-10-25 16:36 UTC
Labels: bug, good first issue, visual
