### ISSUE TITLE
"iflj" generates an invalid JSON format

### ISSUE THREAD

**Issue by cpuinfo** [radareorg/radare2#19963] opened 2022-04-17 08:56 UTC
## Environment

date
Sun 17 Apr 2022 02:15:05 PM IST
r2 -v
radare2 5.4.2 0 @ linux-x86-64 git.5.4.2
commit: 5.4.2 build: 2021-09-26__11:56:56
uname -ms
Linux x86_64

## Description
After giving the command 
**iflj**
the generated output ends up as a invalid JSON object

## Test
**Note**: Tried on x86 and ARM ELF files
\> aaa
\> iflj
```
{{"core":{"type":"EXEC (Executable file)","file":"/tmp/test/firmwares/WRT32X/sbin/netifd","fd":3,"size":112068,"humansz":"109.4K","iorw":false,"mode":"r-x","minopsz":4,"maxopsz":4,"invopsz":4,"pcalign":4,"block":256,"format":"elf"},"bin":{"arch":"arm","baddr":65536,"binsz":111280,"bintype":"elf","bits":32,"canary":true,"class":"ELF32","compiled":"","compiler":"","crypto":false,"dbg_file":"","endian":"little","havecode":true,"guid":"","intrp":"/lib/ld-musl-arm.so.1","laddr":0,"lang":"c","linenum":true,"lsyms":true,"machine":"ARM","nx":true,"os":"linux","cc":"","pic":false,"relocs":true,"relro":"full","rpath":"NONE","sanitize":false,"static":false,"stripped":false,"subsys":"linux","va":true,"checksums":{}}},"libs":["libubox.so","libubus.so","libuci.so","libjson-c.so.2","libblobmsg_json.so","libnl-tiny.so","libgcc_s.so.1","libc.so"]}
```
_After passing through JSON linter_

![Selection_956](https://user-images.githubusercontent.com/69376519/163707574-b9c11be9-3e4c-4f27-bd5c-efea7e1bdb9f.png)

**Comment by trufae** [comment] 2022-04-18 21:52
Can you test with latest master? 5.4.2 is pretty old

**Comment by trufae** [comment] 2022-04-18 21:59
I can confirm this issue is happening in master too.

As a workaround I would suggest to use two separate commands for now:

`ifj` and `ilj` in this case.

funnily `ilfj` also prints an invalid json (but a different one) and other subcommands just don't show the right output (`isflj`)

**Comment by aviciano** [comment] 2022-05-27 17:17
Is `if` a valid command? because it's not documented

**Comment by trufae** [comment] 2022-05-27 22:50
no. `if` is not a valid command. i pushed this pr accordingly https://github.com/radareorg/radare2/pull/20182

**Comment by trufae** [comment] 2022-05-30 19:01
I think you want to do `ij` instead. closing for now

**Closed by trufae** 2022-05-30 19:01 UTC
