### ISSUE TITLE
r2 fails to detect main

### ISSUE THREAD

**Issue by ghost** [radareorg/radare2#7721] opened 2017-06-11 00:27 UTC
the bin is compiled with VS C++ 2016 on win10 and uses the MSVCP runtime dll.
attached the really simple bin.
![consoleapplication1](https://user-images.githubusercontent.com/5345101/27007271-7f7fe7a8-4e4d-11e7-94ff-9265e3527f62.jpg)

**Comment by radare** [comment] 2017-06-12 09:30
is the main supossed to be at 0x00414240 ?

**Comment by n0way0ut** [comment] 2017-06-12 21:28
no, it should be at 0x00412370

**Comment by radare** [comment] 2017-06-13 10:51
Detecting this requires some really fuckedup logic. ida handles this because it haves signatures for all MSVC runtime functions which are then detected there. the whole program is constructed within a jump table that hooks all control flows of the program, this is only done in debug builds. it would be good to know what happens when you build for release. But anyway, i was thinking in different ways to handle this, but all require some automation which can be done in a script, but handling this in a generic form is too weak imho.

My proposed solution implies finding xrefs for the argc import symbols which are handled by the real entrypoint of the program (not the one speifieid in the PE header), and then following the 4th pointer call of this function and resolving the jump table you get into the main.

any better idea?

maybe i should come back to add custom scripts to load depending on the bin type like vim does, it is an easy addition and may be good for this

**Comment by Maijin** [comment] 2017-06-13 18:30
IDA doesn't handle it.

**Comment by radare** [comment] 2017-06-13 19:43
someone with the last version of ida confirmed me that it does

**Comment by Maijin** [comment] 2017-06-14 02:14
Well if you consider:

![image](https://user-images.githubusercontent.com/1408600/27112495-8df98822-5085-11e7-8046-75a2f9c1751a.png)

_main   .text 004112DF 00000005                   R . . . . T .
_main_0 .text 00412370 0000005B 000000D0 00000000 R . . . B . .

Then yes

**Comment by radare** [comment] 2017-06-14 08:35
there’s no winmain here, its just a console app

**Comment by Maijin** [comment] 2017-06-14 20:49
I know, just doesn't seem to be "main" detection was more looking like symbol or smth. I didn't check closely.

**Comment by Maijin** [comment] 2017-09-10 22:23
ping @skuater

**Comment by ret2libc** [comment] 2020-07-27 13:55
@GustavoLCR I see this is assigned to you. Do you think you'll be able to complete this for next release? I'm asking not to put pressure, just to try cleaning up a bit the issues that are assigned for the next milestone.

**Closed** 2020-08-03 04:30 UTC
Labels: PE, test-required
