### ISSUE TITLE
"PTRACE_GETREGSET: Invalid argument" spam in debugging mode

### ISSUE THREAD

**Issue by Vyber90** [radareorg/radare2#17944] opened 2020-11-19 19:53 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | WSL Kali x86_64, Windows 20H2
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 25277 @ linux-x86-64 git.4.4.0-941-g3ae296254
commit: 3ae296254b035cc01872d09bdf7e40258b95e512 build: 2020-11-19__18:43:32

### Expected behavior
Not showing PTRACE_GETREGSET: Invalid argument at all
### Actual behavior
The program will print tens of lines with PTRACE_GETREGSET: Invalid argument for some commands
### Steps to reproduce the behavior 
~$ radare2 program
[0x00000000] ood
Process with PID XXX started...
= attach XXX XXX
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
File dbg:///program
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
PTRACE_GETREGSET: Invalid argument
XXX
[0x00000000]

**Comment by XVilka** [comment] 2020-11-20 05:18
Likely a duplicate of https://github.com/radareorg/radare2/issues/17944

**Comment by badgateway666** [comment] 2020-12-10 01:02
> Likely a duplicate of #17944
I guess that should be #17919 since #17944 is this issue itself

**Comment by trufae** [comment] 2021-04-14 08:35
Closing as long as its dupe. im gonna fix that

**Closed by trufae** 2021-04-14 08:35 UTC
Labels: Linux OS, RDebug, Windows
