### ISSUE TITLE
Unable to debug ELF64 (haskell binary)

### ISSUE THREAD

**Issue by fcasal** [radareorg/radare2#13404] opened 2019-03-17 14:56 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 22005 @ linux-x86-64 git.3.3.0-172-ge73d2c1commit: e73d2c1f63f5814b928c5e0a3c471bc6a4d2433e build: 2019-03-17__14:36:18

The binary reads from stdin and checks if it is the correct flag.
```
mandlebro@manford:~/.../my_ctf_challenges/haskell$ ./haskell_chall 
asd
False
```
### Actual behavior
When debugging in r2 an alarm is raised and nothing happens at first.

```sh
mandlebro@manford:~/.../my_ctf_challenges/haskell$ r2 haskell_chall 
Module version mismatch /home/mandlebro/.local/share/radare2/plugins/io_frida.so (3.3.0-git) vs (3.4.0-git)
 -- Add comments using the ';' key in visual mode or the 'CC' command from the radare2 shell
[0x00405eb0]> ood
Process with PID 1444 started...
File dbg:///home/mandlebro/Documents/my_ctf_challenges/haskell/haskell_chall  reopened in read-write mode
= attach 1444 1444
ptrace (PT_ATTACH): Operation not permitted
1444
[0x7f26ae622c30]> dc
child stopped with signal 26
[+] SIGNAL 26 errno=0 addr=0x00000000 code=-2 ret=0
[+] signal 26 aka SIGVTALRM received 0
```
However, if you then reopen the binary with `oo` what you type starts going either to the binary or to r2 afaict:
```sh
mandlebro@manford:~/.../my_ctf_challenges/haskell$ r2 haskell_chall 
Module version mismatch /home/mandlebro/.local/share/radare2/plugins/io_frida.so (3.3.0-git) vs (3.4.0-git)
 -- Add comments using the ';' key in visual mode or the 'CC' command from the radare2 shell
[0x00405eb0]> ood
Process with PID 1444 started...
File dbg:///home/mandlebro/Documents/my_ctf_challenges/haskell/haskell_chall  reopened in read-write mode
= attach 1444 1444
ptrace (PT_ATTACH): Operation not permitted
1444
[0x7f26ae622c30]> dc
child stopped with signal 26
[+] SIGNAL 26 errno=0 addr=0x00000000 code=-2 ret=0
[+] signal 26 aka SIGVTALRM received 0
[0x7f26ad7c05b3]> oo
3
[0x00405f50]> 
[0x00405f50]> dc                   # here you have to type the same keys twice 
PTRACE_CONT: No such process
asdasd
False
child exited with status 0

==> Process finished
```

[haskell_chall.zip](https://github.com/radare/radare2/files/2975299/haskell_chall.zip)

**Comment by radare** [comment] 2019-03-18 09:27
what happens with -d ?

**Comment by fcasal** [comment] 2019-03-18 09:49
The same:
```
mandlebro@manford:~/.../my_ctf_challenges/haskell$ r2 -d haskell_chall
Module version mismatch /home/mandlebro/.local/share/radare2/plugins/io_frida.so (3.3.0-git) vs (3.4.0-git)
Process with PID 7393 started...
= attach 7393 7393
bin.baddr 0x00400000
Using 0x400000
asm.bits 64
 -- EIP = 0x41414141
[0x7ff3da05cc30]> dc
child stopped with signal 26
[+] SIGNAL 26 errno=0 addr=0x00000000 code=-2 ret=0
[+] signal 26 aka SIGVTALRM received 0
[0x7ff3d91fa5b3]> dc
child stopped with signal 26
[+] SIGNAL 26 errno=0 addr=0x2a600000000 code=-2 ret=0
[+] signal 26 aka SIGVTALRM received 0
[0x7ff3d91fa5b3]> oo
3
[0x00405f50]> dc
PTRACE_CONT: No such process
asd
False
child exited with status 0

==> Process finished

[0x00000000]> 
```

**Comment by v45k0** [comment] 2019-04-15 08:39
I can confirm the same bug when tested on a simple C crackme (uploaded, see below) with the slightest difference that if the debug mode is started with `r2 -d bin` everything works as expected:
- `r2 bin` and then executing `ood` crashes with *ptrace (PT_ATTACH): Operation not permitted* as in the initial comment
- `r2 -d bin` works fine

Info about the work environment (running latest r2):

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali 4.19.0-kali1-amd64
| File format of the file you reverse (mandatory)      | ELF 
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21466 @ linux-x86-64 git.3.4.1-131-g73c38d38e commit: 73c38d38e7e113f6103d98c5b6751ff42902bb20 build: 2019-04-15__04:10:16

[crackme.zip](https://github.com/radare/radare2/files/3079172/crackme.zip)

**Comment by radare** [comment] 2019-04-15 11:17
Would be good to deetermine if this is caused by ptrace-wrap, can u try rebuilding r2 without it?

**Comment by fcasal** [comment] 2019-04-15 14:10
The same behaviour happens to me when I change the configure variable to WANT_PTRACE_WRAP=0 and build r2.

**Comment by rgnkn** [comment] 2019-04-18 08:21
Same this end.

With me there seems to be an issue with the TracerPid of the newly spawned process. The newly spawned process (with ood or doo) will show the same TracerPid (grep TracerPid /proc/.../status) as with the original start (with r2 -d ...) though the annotated tracer won't be alive after the first ood/doo. The annotated remains at <r2-pid + 1>.

=> ptrace (PT_ATTACH): Operation not permitted

Neither WANT_PTRACE_WRAP, nor changing yama settings helps.

Any ideas?

Os: Ubuntu 18.10

**Comment by thestr4ng3r** [comment] 2019-04-18 14:26
@rgnkn How do you know the tracer is not alive anymore? The reason it is r2-pid + 1 is most likely because ptrace-wrap, which pushes all ptrace calls into a separate thread, which would get this pid, not the initial r2 pid and this thread should stay alive as long as r2 runs.

These `ptrace (PT_ATTACH): Operation not permitted` messages seem to happen because of subsequent `PT_ATTACH` calls to the same pid, even though it is already attached. This should be fixed, but it probably shouldn't cause any major issues right now.

What I do see though is that after `ood`, the original process is still there:
```
16961 pts/1    00:00:00 ls <defunct>
```
This might actually be what causes the initial issues described by @fcasal, namely that the keyboard input goes into the old process from the first debug session.

About the signals: It seems to me like the Haskell binary is raising those SIGVTALRMs itself, in which case r2 stopping there would be correct, but I haven't investigated more about that so far.

**Comment by abcSup** [comment] 2020-03-03 22:55
I looked into this issues. Here are what I found in Linux native debugger case:

```
$ r2 -d /bin/ls
Process with PID 51578 started...
= attach 51578 51578
bin.baddr 0x5611e416b000
Using 0x5611e416b000
asm.bits 64
Warning: r_bin_file_hash: file exceeds bin.hashlimit
 -- Hang in there, Baby!
[0x7fe7c714a090]> ood /
Process with PID 51579 started...
= attach 51579 51579
File dbg:///bin/ls  / reopened in read-write mode
d51579
[0x7f69e6853090]> dc
child received signal 9
[0x7f69e686ef43]> dc
bin   etc         initrd.img.old  lib64       mnt   root  srv  usr      vmlinuz.old
boot  home        lib             lost+found  opt   run   sys  var
dev   initrd.img  lib32           media       proc  sbin  tmp  vmlinuz

```

1. `ood /`, `r_core_file_reopen_debug` sends a kill signal to the current child process/debuggee, but it is suspended so it does not terminate. The kill signal is not blocked, but we would still need to do a `wait` to receive the child status changed in order to terminate it (because it was traced?) .
2.  `dc`, the debugger will call `r_debug_wait` which calls `waitpid(-1, XX, XX)`, and because the previous child process is still under `r2`, `waitpid` will returns the previous kill signal, hence `child received signal 9`

**Comment by radare** [comment] 2020-03-04 01:22
can you fix this in a pr?

**Comment by abcSup** [comment] 2020-03-04 07:32
sure, I am still looking into it.

**Closed** 2020-03-05 13:42 UTC
Labels: RDebug, bug
