### ISSUE TITLE
Function boundaries not recognized

### ISSUE THREAD

**Issue by Stormys** [radareorg/radare2#8275] opened 2017-08-22 18:39 UTC
Some functions seem to have their boundaries end short, missing certain blocks of the function.

```
/ (fcn) sym.hard_locale 34
|   sym.hard_locale ();
|              ; CALL XREF from 0x00404c87 (sym.rpl_mbrtowc)
|           0x00404d50      4883ec08       sub rsp, 8                  ; /lib:39
|           0x00404d54      31f6           xor esi, esi                ; /lib:41
|           0x00404d56      e8b5c7ffff     call sym.imp.setlocale      ; char *setlocale(int category, const char *locale)
|           0x00404d5b      4885c0         test rax, rax               ; /lib:43
|       ,=< 0x00404d5e      7430           je 0x404d90
|       |   0x00404d60      803843         cmp byte [rax], 0x43        ; /lib:47 ; [0x43:1]=255 ; 'C' ; 67
|      ,==< 0x00404d63      7513           jne 0x404d78
|      ||   0x00404d65      80780100       cmp byte [rax + 1], 0
|     ,===< 0x00404d69      750d           jne 0x404d78
|     |||   0x00404d6b      31c0           xor eax, eax                ; /lib:48
|     |||   0x00404d6d      4883c408       add rsp, 8                  ; /lib:72
\     |||   0x00404d71      c3             ret
```
when it should be 
```
/ (fcn) sym.hard_locale 34
|   sym.hard_locale ();
|              ; CALL XREF from 0x00404c87 (sym.rpl_mbrtowc)
|           0x00404d50      4883ec08       sub rsp, 8                  ; /lib:39
|           0x00404d54      31f6           xor esi, esi                ; /lib:41
|           0x00404d56      e8b5c7ffff     call sym.imp.setlocale      ; char *setlocale(int category
, const char *locale)
|           0x00404d5b      4885c0         test rax, rax               ; /lib:43
|       ,=< 0x00404d5e      7430           je 0x404d90
|       |   0x00404d60      803843         cmp byte [rax], 0x43        ; /lib:47 ; [0x43:1]=255 ; 'C'
 ; 67
|      ,==< 0x00404d63      7513           jne 0x404d78
|      ||   0x00404d65      80780100       cmp byte [rax + 1], 0
|     ,===< 0x00404d69      750d           jne 0x404d78
|     |||   0x00404d6b      31c0           xor eax, eax                ; /lib:48
|     |||   0x00404d6d      4883c408       add rsp, 8                  ; /lib:72
\     |||   0x00404d71      c3             ret
      |||   0x00404d72      660f1f440000   nop word [rax + rax]
      |||      ; JMP XREF from 0x00404d63 (sym.hard_locale)
      |||      ; JMP XREF from 0x00404d69 (sym.hard_locale)
      ``--> 0x00404d78      4889c6         mov rsi, rax                ; /lib:47
        |   0x00404d7b      bf60644000     mov edi, str.POSIX          ; 0x406460 ; "POSIX"
        |   0x00404d80      b906000000     mov ecx, 6
        |   0x00404d85      f3a6           repe cmpsb byte [rsi], byte ptr [rdi] ; [0x2700000000:1]=$55 ; 167503724544
        |   0x00404d87      0f95c0         setne al
        |   0x00404d8a      4883c408       add rsp, 8                  ; /lib:72
        |   0x00404d8e      c3             ret
        |   0x00404d8f      90             nop
        |      ; JMP XREF from 0x00404d5e (sym.hard_locale)
        `-> 0x00404d90      b801000000     mov eax, 1                  ; /lib:40
            0x00404d95      4883c408       add rsp, 8                  ; /lib:72
            0x00404d99      c3             ret
            0x00404d9a      660f1f440000   nop word [rax + rax]
```
Does not make sense. Those are not far jmps. What kind of reasoning is it using to determine the end of a function.

I have also tried enabling
```
e anal.jmptbl=true
e anal.jmpref=true
e anal.jmpabove=true
e anal.afterjmp=true
```

**Comment by radare** [comment] 2017-08-23 13:56
There are tests for this and we know thats a regression after the siol merge. We are doing lot of internal breakage to make everything much pleasant and consistent. Help on improving master or use the previous release

**Comment by ret2libc** [comment] 2020-07-01 20:15
Hi, I'm closing this issue as a lot has passed since it was created and analysis was improved/changed. Please feel free to re-open it if you think the issue is not solved and provide a proper test case so we can reproduce. Thanks again for creating this bug!

**Closed by ret2libc** 2020-07-01 20:15 UTC
Labels: RAnal, test-required
