### ISSUE TITLE
Remove "projects" feature until it's implemented properly.

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#17034] opened 2020-06-10 05:05 UTC
It doesn't work anyway, proper implementation will require some time, people try this feature and go away disappointed because it doesn't work in 98% of time. I think it's better to remove them completely until they are properly implemented.
- [ ] Remove the code
- [ ] Remove the commands
- [ ] Remove mentions from manpages and help
- [ ] Remove mentions from radare2book
- [ ] Go through radare2-extras and r2pm to remove all usages if any.
- [ ] Make a public announcement on blog, twitter, social networks about removal of the feature.

**Comment by unixfreaxjp** [comment] 2020-06-10 10:37
I taught people who learn r2 in beginners level in my community to create project to save their stuff.
I understand the situation, as users, so I am not against this feature's deletion due to mentioned circumstance.

However, please make a proper announcement if the project feature is completely removed. So I can refer it to documentation that I made. Adding "announcement" in these tasks will be appreciated.

>    Remove the code
>    Remove the commands
>    Remove mentions from manpages and help
>    Remove mentions from radare2book
>    Go through radare2-extras and r2pm to remove all usages if any.

@XVilka 
cc: @trufae

**Comment by thestr4ng3r** [comment] 2020-06-10 10:55
fyi a rewrite of projects is currently in process: https://github.com/thestr4ng3r/r2db

**Comment by ulidtko** [comment] 2020-07-11 10:03
This gets a strong bold **-1** from me.

Main reason: despite being imperfect and buggy (like the whole radare2 itself), it's still very useful.

Secondary reason: I fail to see what the removal will achieve besides inflicting suffering. `Ps`/`Po` can be incrementally improved IMO.

> [...] To make it work it would require huge amounts of tests, considering every corner case.

No; this is exactly the use-case for **fuzz-testing**. With not much code, it'll find all those corner cases for you. With not much code, it can find `Ps` idempotence violations, `Ps; Po` identity violations, version regressions and whatever other properties one cares to formulate.

I agree with "something needs to be done with r2 projects" — but as soon as the "something" takes the value of "remove for indeterminate time", I disagree strongly.

**Comment by ret2libc** [comment] 2020-08-24 05:45
Did we reach any conclusion on this? I'm personally for removing the feature because it is as unreliable as possible, thus something I would not trust using in any case. However, if users think it's better to keep the feature as is until a replacement will be available, I'm ok as well.

Let's try to reach an agreement in less than one month, so we can either close this issue or work on removing the feature.

**Closed** 2020-11-12 05:40 UTC
Labels: FEEDBACK WANTED, projects
