### ISSUE TITLE
pxr no longer shows correct telescoping of single lines/variables

### ISSUE THREAD

**Issue by xx55x** [radareorg/radare2#14605] opened 2019-07-21 22:03 UTC
### Work environment

|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0-git 22337 @ linux-x86-64 git.3.6.0-187-ga4908fa0a
commit: a4908fa0a1ca880c68de9b7a64a14569f93291af build: 2019-07-20__15:50:27

### Expected behavior
When executing pxr $w @ 0xffc5b548, this is the expected output: 

0xffc5b548 0xffc5b60c  .... stack R W 0xffc5c5bd -->  stack R W 0x4c454853 (SHELL=/bin/bash) -->  ascii ('S')

It normally derefrences the pointers and shows any ascii/etc. 

### Actual behavior
Currently, when executing pxr $w @ 0xffc5b548, the output is this:

0xffc5b548 0xffc5b60c  .... 0

This also happens when executing pxr 4 @ 0xffc5b548

When executing pxr 8 @ 0xffc5b548, the behavior is similar, but is two lines with wrong values:

0xffc5b548 0xffc5b60c  .... 0
0xffc5b54c 0xe5ea1300  .... 0

However when executing pxr 12 @ 0xffc5b548 or more, the first line(s) are correct, while the rest are invalid:

0xffc5b548 0xffc5b60c  .... stack R W 0xffc5c5bd -->  stack R W 0x4c454853 (SHELL=/bin/bash) -->  ascii ('S')
0xffc5b54c 0xe5ea1300  .... 0
0xffc5b550 0xf7f27520   u.. 0

When executing on something bigger such as default block size/pxr @ esp however, I believe only the last few lines are wrong. 

### Steps to reproduce the behavior 
I believe this behavior will occur when running pxr on an address/variable with a size of 4-8 for a 32bit system, or 8-16 on a 64, at least on x86.

- Use asciinema to describe the issue and share the link here (mandatory if u can't share the binary) 

https://asciinema.org/a/ECXh7Z4Ju85mR7qCB88NplFQx

**Comment by radare** [comment] 2019-07-23 13:28
Cant repro

**Comment by xx55x** [comment] 2019-07-23 14:06
Huh that is very strange.

Another thing I’ve noticed is the command used for afvd is now “pf d @ ebp-0x14” for example instead of “pxr $w @ ebp-0x14”, and the values are being shown only in decimal.

Now I’m really wondering if that’s just me, or if that has happened to anyone else? 

If there is any more information I could provide please let me know. I’ll continue to try and see what’s going on, and will try a few vms soon. 

I tried the older version from apt repository again and it is working well in all situations for some reason, when I am home I’ll definitely investigate further.

**Comment by radare** [comment] 2019-07-23 19:09
can you identiffy which commit was the first to introduce this rergression? is this issue only on 32bit?

**Comment by xx55x** [comment] 2019-07-23 20:03
Hmm I am not sure when this was introduced, as I jumped from using version 3.2.1 from the Debian repository to the git version. I do notice it on both 32 and 64bit binaries. 

I've just tried it on my blackarch VM which has radare2 from the arch repository: 

radare2 3.6.0 0 @ linux-x86-64 git.3.6.0
commit: unknown build: 2019-07-01__21:50:36

It has the same issue it seems. This happens on both 32 bit and 64 bit binaries. 
typing afvd outputs the variables in decimal with pf d @rbp-0x34, and the pxr $w @ rbp-0x34 command will output something like this: 

0x7ffe755207ec 0x0000000100000005   ........ 0

when the expected behavior is this:

0x7ffe755207ec 0x0000000100000005   ........ 4294967301

**Comment by radare** [comment] 2019-07-24 23:59
Uhm, may be related to the block size? why do you use $w ?

**Comment by thestr4ng3r** [comment] 2019-07-25 08:22
@radare You should just be able to reproduce with the broken test

**Comment by radare** [comment] 2019-07-25 08:55
The broken test shows an issue at the end of the block thats why im asking

**Comment by xx55x** [comment] 2019-07-25 09:01
I’ll try to experiment with the block size ,I use $w mostly to look at variables as afvd has been showing them in decimal.

**Comment by thestr4ng3r** [comment] 2019-07-25 10:36
The broken size seems to be always 8 for some reason. That's maybe why it's two entries in this issue (32 bit) and one at the end in the test.

**Comment by radare** [comment] 2019-07-25 14:03
Can u try to fix the issue?

**Comment by thestr4ng3r** [comment] 2019-07-25 14:28
Yes, but can't say when right now

**Comment by trufae** [comment] 2021-06-12 09:07
Closing. I think i fixed this long time ago and i cant reproduce it, the asciinema no longer exists and there's no unit or r2 test.

**Closed by trufae** 2021-06-12 09:07 UTC
