### ISSUE TITLE
Create a 'real' centralized parser

### ISSUE THREAD

**Issue by 08A** [radareorg/radare2#17449] opened 2020-08-12 12:46 UTC
**Is your feature request related to a problem? Please describe.**
The parsing is mixed with the code logic
Example
```
libr/core/cmd_anal.c
10109 static int cmd_anal(void *data, const char *input) {
```

**Describe the solution you'd like**
Explicit in the documentation the parsing process, location, ect...
https://github.com/radareorg/radare2/pull/17326 ~Centralized the help (aa?, a?, ?)~
Maybe create a new interface to add cmd like
```
REGISTER_CMD("aaa", "Usage: See aa? for more help", ...)
```

**Describe alternatives you've considered**
Use lex, bison or an alternative?

**Additional context**
If we can simplify the parsing process, it will improve debugging process, creation of new feature, ect...

**Comment by XVilka** [comment] 2020-08-12 14:20
Duplicate of https://github.com/radareorg/radare2/issues/7967

**Closed by XVilka** 2020-08-12 14:20 UTC

**Comment by ret2libc** [comment] 2020-08-26 07:50
@08A by the way, if you want you can use `e cfg.newshell=true`, which enables the new parser we are developing with tree-sitter. It centralize the parsing of command, command arguments, etc. Right now we are in a sort of mixed-state, because we have to be somehow compatible with existing code, but the idea is to move everything to the new parser at some point.

**Comment by 08A** [comment] 2020-08-26 07:55
@ret2libc Okay thanks and where can I found the new implementation?

**Comment by ret2libc** [comment] 2020-08-26 08:40
The tree-sitter grammar is in `shlr/radare2-shell-parser/`. That parts just ensure that commands arguments are correctly split, etc. Then in `core/cmd.c:r_core_cmd` you can see where all things start. When cfg.newshell=true, the function will just execute:
```C
	if (core->use_tree_sitter_r2cmd) {
		return cmdstatus2int(core_cmd_tsr2cmd (core, cstr, false, log));
	}
```

you can follow the code from there.

Then in `r_cmd.h` you can see some functions like `r_cmd_desc_argv_new` that are used to add commands that accept argv-style. Look at `core/cmd_write.c:cmd_write_init` for an idea on how they are used.

Once you look at those things, feel free to ask other questions ;)
