### ISSUE TITLE
e cfg.newshell=false in test body does not switch to old parser

### ISSUE THREAD

**Issue by kazarmy** [radareorg/radare2#17495] opened 2020-08-19 15:17 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora Rawhide x86-64
| File format of the file you reverse (mandatory)      | Not applicable
| Architecture/bits of the file (mandatory)            | Not applicable
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 28339 @ linux-x86-64 git.4.4.0-572-g5f0be49fd commit: 5f0be49fd16fadb8c6338d0807f3de65c5fb1e0e build: 2020-08-19__21:51:33

### Expected behavior

From 
https://github.com/radareorg/radare2/blob/5f0be49fd16fadb8c6338d0807f3de65c5fb1e0e/test/db/tools/r2#L111-L122
and moving the `e cfg.newshell=false` from `ARGS` into the test body as the first line i.e.

```
NAME=r2 shortcut
FILE=-
CMDS=<<EOF
e cfg.newshell=false
?q `!!r2 -h~Usage?`
?+ ?vi $?
?! ?e `!!r2.bat -h~Usage?`
EOF
EXPECT=<<EOF
1
EOF
RUN
```

the test should pass after doing
```
R2_CFG_NEWSHELL=1 r2r -i db/tools/r2
```

### Actual behavior

![q_test2](https://user-images.githubusercontent.com/12002672/90653110-5f85af80-e271-11ea-9ea3-195c7b1dd1cf.PNG)

@ret2libc While I'm confident that not many people will do this for fun or profit, I think this should still be bought to your attention because of the possibility of strange behavior e.g. https://github.com/radareorg/radare2/runs/984844221#step:13:100.

**Comment by ret2libc** [comment] 2020-08-19 16:02
I will have a look thanks. I think a workaround short term should be to use `ARGS=-ecfg.newshell=true`.

**Comment by ret2libc** [comment] 2020-08-27 10:09
Ok I think I understand what's going on. The issue is that the entire script is considered as a single "unit" and because R2_CFG_NEWSHELL is set to 1, that whole script is passed to newshell. During the execution of the script, newshell variable is changed to false, but this is already too late because everything was already passed to the newshell parser.

I'm not sure how to fix this or if it's even worth thinking about it and complicating the code. WDYT?

**Comment by kazarmy** [comment] 2020-08-27 10:47
Well, the engineering should be modular enough such that one should be able to cleanly switch between the parsers, and it was a big what-the-heck moment, but since we are planning to replace the old parser entirely I agree the benefits should outweigh the costs.

**Comment by ret2libc** [comment] 2020-08-27 11:59
I'm going to close this without fixing it. Thanks for finding this!

**Closed by ret2libc** 2020-08-27 11:59 UTC
Labels: command, input
