### ISSUE TITLE
Incorrect behavior in Xtensa disassembly backward direction

### ISSUE THREAD

**Issue by yaghmr** [radareorg/radare2#22896] opened 2024-05-03 16:50 UTC
## Environment

```sh
Fri 3 May 2024, 18:42:37, CEST
radare2 5.9.0 0 @ linux-x86-64
birth: git.5.9.0 2024-04-28__16:01:19
commit: unknown
options: gpl release -O1 cs:5 cl:2 meson
Linux x86_64

```

## Description

When attempting to disassemble N instructions backwards in _Xtensa_ architecture, there's an issue where the behavior deviates from the expected. For example, passing `-5` results in disassembling 2 instructions before and 2 after, rather than the expected 5 before

## Test
```
[0x400814ec]> i
fd       3
file     app.elf
size     0xeff124
humansz  15.0M
mode     r-x
format   elf
iorw     false
block    0x100
type     EXEC (Executable file)
arch     xtensa
baddr    0x3f400000
binsz    15717475
bintype  elf
bits     32
canary   false
injprot  true
class    ELF32
compiler GCC: (crosstool-NG esp-13.2.0_20230928) 13.2.0 GCC: (crosstool-NG crosstool-ng-1.22.0-97-gc752ad5) 5.2.0
flags    0x300
crypto   false
endian   little
havecode true
laddr    0x0
lang     c++
linenum  true
lsyms    true
machine  Tensilica Xtensa Architecture
nx       false
os       linux
pic      false
relocs   true
relro    no
rpath    NONE
sanitize false
static   true
stripped false
subsys   linux
va       true
[0x400814ec]> s 0x4008150a
[0x4008150a]> pd -5
│           0x40081505      e9fb           s32i.n a14, a11, 60
│           0x40081507      e00800         callx8 a8
│           0x4008150a      a1d5fb         l32r a10, loc._bss_start   
│           0x4008150d      0c0b           movi.n a11, 0
│           0x4008150f      c1d3fb         l32r a12, loc._bss_end   
```

**Comment by trufae** [comment] 2024-05-03 17:03
cant repro, no matter if the bin is analized or not

<img width="965" alt="Screenshot 2024-05-03 at 19 02 10" src="https://github.com/radareorg/radare2/assets/6431515/e9e86591-3a4d-41ed-83de-71a2332d0e5d">

<img width="972" alt="Screenshot 2024-05-03 at 19 02 27" src="https://github.com/radareorg/radare2/assets/6431515/b5e6a86c-7faa-419e-a424-62f38921380e">

please provide your app.elf

**Comment by yaghmr** [comment] 2024-05-04 09:32
Here it is: [app.elf.tar.gz](https://github.com/radareorg/radare2/files/15209199/app.elf.tar.gz)

**Comment by radare** [comment] 2024-05-07 22:08
same, cant reproduce. but im using r2 from git

**Comment by yaghmr** [comment] 2024-05-08 07:19
As mentioned, I am using radare2 **5.9.0**. Now I will try the Git version and let you know.

**Comment by trufae** [comment] 2024-05-08 08:43
I plan to release 5.9.2 this week. Just finishing some last minute issues these days :) the uneven patch version numbers are only in git. Releases are even/pair numbers. Closing the ticket as i only keep track of issues affecting git. 

Thanks to confirm!

feel free to report any other issue you find in xtensa, as well as adding more tests for this arch! Thank you!

**Closed by trufae** 2024-05-08 08:43 UTC
