### ISSUE TITLE
Searching in raw kernel memory

### ISSUE THREAD

**Issue by lordneon** [radareorg/radare2#16647] opened 2020-04-20 07:57 UTC
Issue #16327 has not been fixed. The fix commited just hides the error message and does not resolve the underlying issue.

The issue appears to be using a signed INT64 for the end search offset rather than unsigned.  ( https://github.com/radareorg/radare2/commit/e0b197766811db0952d243b2df36969d34cee36e ) 

Could the previous issue be reopened please?

**Comment by XVilka** [comment] 2020-04-20 09:03
Next time please write in the original issue to reopen it.
Duplicate of https://github.com/radareorg/radare2/issues/16327

**Closed by XVilka** 2020-04-20 09:03 UTC
Labels: RIO, RSearch, gdb
