### ISSUE TITLE
Graph view bugged after 4.3.0

### ISSUE THREAD

**Issue by d-we** [radareorg/radare2#16125] opened 2020-03-04 02:58 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux amd64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.0 23980 @ linux-x86-64 git.4.3.0-1-gb76831c05 commit: b76831c05045b5126f067c8751853e295f5c2e5d build: 2020-03-04__01:32:59 2018-02-17__11:08:27
screen resolution | 3840x2160
### Expected behavior
Normal looking graph view

### Actual behavior
The graph view looks like the following:

![Screenshot_20200304_035001](https://user-images.githubusercontent.com/31281970/75840342-48d6c380-5dcb-11ea-8048-368f2a6ed418.png)

### Steps to reproduce the behavior 
`r2 /bin/ls -c Vp`
This happens for every binary on my system.

Zip containing the binary:
[graph-issue.zip](https://github.com/radareorg/radare2/files/4284809/graph-issue.zip)
### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by XVilka** [comment] 2020-03-04 07:59
I cannot reproduce with either local or same binary. Moreover, `-c Vp` doesn't call a graph view, it should show just disassembly. We need more information on terminal, local config, if terminal multiplexer was used, etc.

**Comment by radare** [comment] 2020-03-04 09:34
meh, it was fixed in a commit from me right after the first 4.3 tag, i just push -f --tags. should be good

**Closed by radare** 2020-03-04 09:34 UTC
Labels: regression, visual
