### ISSUE TITLE
Cannot place a breakpoint on

### ISSUE THREAD

**Issue by RazviAlex** [radareorg/radare2#14437] opened 2019-06-27 18:01 UTC
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04.2 LTS x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ELF 64-bit LSB shared object, x86-64, version 1 (SYSV)
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 22130 @ linux-x86-64 git.3.5.1-294-g3fe39f0c commit: 3fe39f0c38b66efa64ef3673e2ba3e6fc3830bf9 build: 2019-06-19__19:13:43

### Expected behavior

First of all what I'm trying to do is just set a break-point without start radare2 with `-d `option. 
I set a script in python to manipulate a file with radare, enter first in the debug mod with `ood` and what I expected is just to set the break-point like this: 

![image](https://user-images.githubusercontent.com/51793648/60287949-70f45580-9913-11e9-85f6-ac3b101668c4.png)
Image from a youtube video: "Scripting radare2 with python for dynamic analysis - TUMCTF 2016 Zwiebel part 2"

### Actual behavior

First I try first do it just with radare and when it works go to the script, so I open radare like `r2 ./hello` 
Enter in the visual mode: `VV`
Set `aa`
Set `ood` 
And finally set a breakpoint: `db 0x000005e1`

![image](https://user-images.githubusercontent.com/51793648/60287920-5e7a1c00-9913-11e9-8f8e-7d1e6ce2fff6.png)

Don't let me set a breakpoint.
Also try different option, like `aaa`, or first `oo+` and the `ood`, always the same problem:
`Cannot place a breakpoint on 0x000005e1 unmapped memory.See e? dbg.bpinmaps`

Try directly from the python script like this:

![image](https://user-images.githubusercontent.com/51793648/60288617-e3b20080-9914-11e9-8f3d-6cc6cf27fbf6.png)

Same problem.. it's seems like radare dosen't let me put a breakpoint and can't know why :(
Search for the same problem here, and other pages but it seems all the solution goes to start radare with the '-d' option.. I also try do it with the script, but throws an error: 
`r2 = r2pipe.open("./hello -d")`

![image](https://user-images.githubusercontent.com/51793648/60289257-4bb51680-9916-11e9-86e7-3868b6fcb5d4.png)

### Additional Logs, screenshots, source-code,  configuration dump, ...

The file is a simple Hello world, write in c and compile it. But I try also with others files.

Appreciate any help very much

**Comment by abcSup** [comment] 2020-03-02 20:37
This seems to be fixed in #15750.

Hello @RazviAlex, could you try it again with the latest r2?

**Comment by XVilka** [comment] 2020-06-15 01:47
@RazviAlex please confirm, otherwise we will close the issue as fixed.

**Comment by XVilka** [comment] 2020-06-19 06:54
Closing due to the lack of the answer. Please reopen if it is still reproducible.

**Closed by XVilka** 2020-06-19 06:54 UTC
Labels: RDebug, high-priority
