### ISSUE TITLE
invalid disassembly for x86 16bit

### ISSUE THREAD

**Issue by lasek0** [radareorg/radare2#18887] opened 2021-07-05 21:57 UTC
## Environment

```sh
$ date
pon, 5 lip 2021, 23:53:34 CEST
$ r2 -v
radare2 5.4.0-git 26743 @ linux-x86-64 git.5.3.1
commit: 9d6afad8b2e2d964e3e7cef598403640120c9cb9 build: 2021-07-05__23:24:16
$ uname -ms
Linux x86_64
$ 

```

## Description

invalid disassembly for x86 16bit mode

## Test

couple of examples, verified with ndisasm (in comment what should be based on NDISASM version 2.14.02):
```
│           0000:0cfc      0d             invalid                      ; 0D0020 or ax,0x2000
│           0000:0cfd      0020           add byte [bx + si], ah       ; -----
```
```
│           0000:07fc      33             invalid                      ; 33C0 xor ax,ax
│           0000:07fd      c08bda81e3     ror byte [bp + di - 0x7e26], 0xe3 ; 8BDA mov bx,dx
│           0000:0802      0040c1         add byte [bx + si - 0x3f], al ; 81E30040 and bx,0x4000
│           0000:0805      eb0d           jmp 0x814                    ; C1EB0D shr bx,byte 0xd
```
```
│           0000:06fc      33             invalid                      ; 33C0 xor ax,ax
│           0000:06fd      c0efba         shr bh, 0xba                 ; EF out dx,ax
│           0000:0700      5a             pop dx                       ; BA5AFF mov dx,0xff5a
│           0000:0701      ff             invalid                      ; ---
```

**Comment by trufae** [comment] 2021-07-06 07:32
What is each output? What is the correct and what is the wrong? Also, if the problem is in the disasm, r2 uses capstone for disassemble x86 by default. So its probably a bug in capstone. You can try installing the udis86 plugin, i think it supports 16 and 32 bit modes better than capstone.

**Comment by lasek0** [comment] 2021-07-06 12:56
this outputs was an result of pd N command. I added CC+ comments for each incorrectly disassembled instructions just for myself to read code properly but I think that r2 should disassemble it correctly for me instead of invalid ins.

Example:
r2 disassemble the following 33c08bda81e30040c1eb0d bytes as following instructions
```
33             invalid
c08bda81e3     ror byte [bp + di - 0x7e26], 0xe3
0040c1         add byte [bx + si - 0x3f], al
eb0d           jmp 0x814
```
which not correct according to the ndisasm. based on ndisasm this should be decoded as:
```
33C0    xor ax,ax
8BDA    mov bx,dx
81E30040    and bx,0x4000
C1EB0D    shr bx,byte 0xd
```
which makes also much more sense.
I think also that this is not a problem with capstone because I check that using python that raw capstone for CS_ARCH_X86 and CS_MODE_16 disassemble it correctly.
which can be seen also in this online capstone disassembler:

http://shell-storm.org/online/Online-Assembler-and-Disassembler/?opcodes=33c08bda81e30040c1eb0d+&arch=x86-16&endianness=little&dis_with_addr=True&dis_with_raw=True&dis_with_ins=True#disassembly

**Comment by trufae** [comment] 2021-07-07 11:01
cant reproduce

![Screenshot 2021-07-07 at 13 01 29](https://user-images.githubusercontent.com/6431515/124748467-741f7480-df23-11eb-8d46-0af0fa78475a.png)

**Comment by lasek0** [comment] 2021-07-07 17:40
All right, today I play a little to create example file, by remove saved r2 project and start re of bin file from scratch,
and wired disassembly disappear. I have no clue what I did wrong first time. I basically use few commands like af @ addr and CC+ comment @ addr, really no complex staff since I want only to discover functions in bin dump. I really want to apologize. Sorry.

**Comment by lasek0** [comment] 2021-07-07 18:11
finally I have example that reproduce problem.
please do following:
```
$python3 -c "__import__('sys').stdout.buffer.write(0x6f7*b'\xff'+b'\x3d\x10\x27\x72\x19\x33\xc0\xef\xba\x5a\xff')" > dump.bin
$r2 -a x86 -b 16 dump.bin
```

then in r2:
pd 1790 # type y

and to compare same bytes type in r2:
pd 6 @ 0x6f7


my output:
```
[0000:0000]> pd 1790 # type y

Do you want to print 1790 lines? (y/N) y
            0000:0000      ff             invalid
            0000:0001      ff             invalid
...
            0000:06f6      ff             invalid
            0000:06f7      3d1027         cmp ax, 0x2710
            0000:06fa      7219           jb 0x715
            0000:06fc      33c0           xor ax, ax
            0000:06fe      ef             out dx, ax
            0000:06ff      ba             invalid
            0000:0700      5a             pop dx
            0000:0701      ff             invalid
[0000:0000]> pd 6 @ 0x6f7
            0000:06f7      3d1027         cmp ax, 0x2710
        ┌─< 0000:06fa      7219           jb 0x715
        │   0000:06fc      33c0           xor ax, ax
        │   0000:06fe      ef             out dx, ax
        │   0000:06ff      ba5aff         mov dx, 0xff5a
        │   0000:0702      ff             invalid
[0000:0000]> 
```
You can see that first two instructions are disassembled correctly in both cases.
```
            0000:06f7      3d1027         cmp ax, 0x2710
            0000:06fa      7219           jb 0x715
```
but after that there are different disassembly even if sizes of instructions should be correctly recognized. 

this reproduces my problem, how also in Your r2.

**Comment by Lazula** [comment] 2021-09-10 06:09
I can reproduce this problem. I tested capstone manually by modifying the code [here](https://www.capstone-engine.org/lang_c.html) to use `#define CODE "=\x10'r\x19\x03\xc0\xef\xbaZ\xff"` and `CS_MODE_16`, and it correctly disassembles `\xba\x5a\xff` as `mov dx, 0xff51`, so I think the issue is in r2, not capstone. The disassembly works on both `master` and `next`, the branch r2 uses. It fails to disassemble in r2 as shown above.

After a little testing, I found that it seems to only fail when you start before the address 0x2. `pd 0x700 @ 0x0` fails, `pd 0x700 @ 0x1` fails, but `pd 0x700 @ 0x2` and every address I tried after `0x2` succeeds.

**Comment by trufae** [comment] 2021-09-10 10:29
works for me:

```
$ r2 -a x86 -b 16 -
[0000:0000]> wx 33c08bda81e30040c1eb0d
[0000:0000]> pd 10
            0000:0000      33c0           xor   ax,   ax
            0000:0002      8bda           mov   bx,   dx
            0000:0004      81e30040       and   bx,   0x4000
            0000:0008      c1eb0d         shr   bx,   0xd
```

**Comment by trufae** [comment] 2021-09-10 10:30
why are you disasemlling 1790 instructions?

**Comment by trufae** [comment] 2021-09-10 10:32
@Lazula capstone have the `cstool` to test things like this, no need to change example progams :) 

also, this ba5aff is also dissasembled properly:

```
[0000:0000]> wx ba5aff
[0000:0000]> pd 1
            0000:0000      ba5aff         mov   dx,   0xff5a
[0000:0000]>
```

**Comment by trufae** [comment] 2021-09-10 10:33
If you start disassembling in thge middle of a instruction you get wrong disassembly until the instructions get aligned to make sense again, thats expected and normal behaviour. so not sure if im missing something still :?

**Comment by Lazula** [comment] 2021-09-10 13:41
The issue is a contextual disassembly failure, not splitting the instruction. I am using the provided dump.bin:

```
python3 -c "__import__('sys').stdout.buffer.write(0x6f7*b'\xff'+b'\x3d\x10\x27\x72\x19\x33\xc0\xef\xba\x5a\xff')" > dump.bin
r2 -a x86 -b 16 dump.bin
```

Whether or not ba5aff is disassembled correctly is dependent on the address you started at:

```
[0000:0000]> pd 0x700 @ 0x0
<snip>
            0000:06f7      3d1027         cmp ax, 0x2710
            0000:06fa      7219           jb 0x715
            0000:06fc      33c0           xor ax, ax
            0000:06fe      ef             out dx, ax
            0000:06ff      ba             invalid
            0000:0700      5a             pop dx
            0000:0701      ff             invalid
[0000:0000]> pd 0x700 @ 0x1
<snip>
            0000:06f7      3d1027         cmp ax, 0x2710
            0000:06fa      7219           jb 0x715
            0000:06fc      33c0           xor ax, ax
            0000:06fe      ef             out dx, ax
            0000:06ff      ba             invalid
            0000:0700      5a             pop dx
            0000:0701      ff             invalid
[0000:0000]> pd 0x700 @ 0x2
<snip>
            0000:06f7      3d1027         cmp ax, 0x2710
            0000:06fa      7219           jb 0x715
            0000:06fc      33c0           xor ax, ax
            0000:06fe      ef             out dx, ax
            0000:06ff      ba5aff         mov dx, 0xff5a
```

**Comment by Lazula** [comment] 2021-09-10 13:55
I had to convert the block of `ff` to `90` when using cstool as it fails on invalid instructions, after which it correctly disassembled the entire block. To be sure, I tested it on r2 as well.

```
python3 -c "__import__('sys').stdout.buffer.write(0x6f7*b'\x90'+b'\x3d\x10\x27\x72\x19\x33\xc0\xef\xba\x5a\xff')" > dump2.bin
r2 -a x86 -b 16 dump2.bin
```

```
[0000:0000]> pd 0x700 @ 0x0
            0000:06f7      3d1027         cmp ax, 0x2710
            0000:06fa      7219           jb 0x715
            0000:06fc      33c0           xor ax, ax
            0000:06fe      ef             out dx, ax
            0000:06ff      ba5aff         mov dx, 0xff5a
```

The same results are produced by starting at 1, 2, etc. It seems that the big block of invalid instructions is causing the problem in dump.bin.

**Comment by trufae** [comment] 2021-09-13 16:03
ok got it and i know where the problem lies. you may want to use `pD` meanwhile i fix the issue.

thanks for reporting!

**Comment by trufae** [comment] 2021-09-13 16:29
I did a fix, but the right fix will require more tests using larger instructions and smaller block sizes. Would you like to cook some of those? As phrased in the pr:

```
we probably need more tests and checks comparing the disasm using different block sizes, as well as comparing it with larger instructions.. but i thikn the right way to go would be to always pass enough bytes to the disassembler, this is using the analop info about the maxinstrsize instead of this hack. But at least we got this case covered and a test!

```

**Comment by trufae** [comment] 2021-09-19 19:44
Fixed in https://github.com/radareorg/radare2/pull/19111

**Closed** 2021-09-19 20:37 UTC
