### ISSUE TITLE
Mouse glitches when clicking in hud mode

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#17167] opened 2020-06-27 19:47 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.15
| File format of the file you reverse (mandatory)      | none
| Architecture/bits of the file (mandatory)            | intel
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 26817 @ darwin-x86-64 git.4.4.0-333-g51405f81f
commit: 51405f81f4ebe2b32b1e8bbfb4d79e73c23aca69 build: 2020-06-27__17:15:00
### Expected behavior

mouse gliutches not appearing

### Actual behavior

mouse glitches appearing

### Steps to reproduce the behavior 

enter visual mode, press _ and then click mouse or just click the offset in visual mode a couple of times, see the movie if you are lazy to read:

![r2visualbug](https://user-images.githubusercontent.com/6431515/85930835-cdd87200-b8bf-11ea-9354-d873239e55d4.gif)

**Comment by ret2libc** [comment] 2020-06-27 20:49
Closing, it seems to be a duplicate of https://github.com/radareorg/radare2/issues/16790 and probably related also to https://github.com/radareorg/radare2/issues/17122 . There is already a PR at https://github.com/radareorg/radare2/pull/17152/ , could you try whether it fixes your issue?

If you think this is different from the issues I mentioned, re-open, though I think it is just the same bug triggered through different commands.

**Closed by ret2libc** 2020-06-27 20:49 UTC
