### ISSUE TITLE
Android radare2 command not found.

### ISSUE THREAD

**Issue by SilasMo** [radareorg/radare2#19484] opened 2021-12-09 03:14 UTC
```
root@goyave3g:/data/data/green_green_avk.anotherterm.oldgood # r2
/data/local/radare2-5.5.2-android-armv7/data/data/org.radareorg.radare2installer/bin/r2[2]: radare2: not found
127|root@goyave3g:/data/data/green_green_avk.anotherterm.oldgood # date
Thu Dec  9 05:09:42 CAT 2021
root@goyave3g:/data/data/green_green_avk.anotherterm.oldgood # r2 -v
/data/local/radare2-5.5.2-android-armv7/data/data/org.radareorg.radare2installer/bin/r2[2]: radare2: not found
127|root@goyave3g:/data/data/green_green_avk.anotherterm.oldgood # uname -ms
tmp-mksh: uname: not found
```
When i try to run any radare2 binary the above error is produced. I have tried exporting paths and ld library paths and even compiled it myself but the same error is produced. What am I doing wrong what should I do? Any help is greatly appreciated.

**Comment by enovella** [comment] 2021-12-09 11:39
Do you have more details about the setup? device? arch? OS version?

**Comment by trufae** [comment] 2021-12-09 11:45
Seems like the problem is in the CI, the armv7 build was generated with meson, which i guess hasnt been tested when created. I just switched to acr so ill update the tarball when the last commit in master finishes.

The error you get is because the `radare2` executable is not in `bin/` , which is not the case for arm64 (which was alreadyc ompiled with acr instead of meson)

**Comment by SilasMo** [comment] 2021-12-09 12:05
>Do you have more details about the setup? device? arch? OS version?

Device Samsung Tab 
Arch: armv7a
os: 4.4.4

**Comment by SilasMo** [comment] 2021-12-09 12:09
>The error you get is because the radare2 executable is not in bin/ , which is not the case for arm64 (which was alreadyc ompiled with acr instead of meson)

I too built with meson but and I guess thats why the error was produced. I tried builddig with make but there came out this error `Checking whether c compiler works no`
I dont know what the problem really is. I was using Android NDK r20.

**Comment by trufae** [comment] 2021-12-09 19:00
try this tarball https://github.com/radareorg/radare2/releases/download/5.5.2/radare2-5.5.2-android-arm.tar.gz

**Comment by trufae** [comment] 2021-12-09 19:01
to build with acr you need to run the sys/android scripts, see the ci.yml file or the doc/android or sys/android* scripts for more details about how to tell the build system where's the ndk

**Comment by trufae** [comment] 2021-12-09 22:06
Which android are you using? This was inteoduced in android 23. I can build r2 with an older ndk to solve this

**Comment by SilasMo** [comment] 2021-12-09 23:40
I am using android 4.4.4. sorry for bothering you.

**Comment by trufae** [comment] 2021-12-10 12:05
This is the ndk v9... kitkat is super old. The lastest ndk is v23. Lots of things changed in this toolchain (gcc va clang..) installation psths, supported archs.. i can try to build in the ci with it but im not sure if builds made with ndk9 will work on any recent device

**Comment by SilasMo** [comment] 2021-12-10 20:58
I think you should go with the majority. It wont be useful if you are building for one person. Thanks for giving me a clue. i know where to get off now.

**Comment by trufae** [comment] 2021-12-13 15:45
i think it makes sense to try it out :) at least, im curious about this, i also have some kitkats in the drawer

**Comment by SilasMo** [comment] 2021-12-13 20:34
Thanks a lot man :)

**Comment by radare** [comment] 2021-12-16 17:25
https://github.com/radareorg/radare2/pull/19501

ill share the bin when the CI ends :) but its merged and seems like there was no build issues (/me crosses fingers)

**Comment by SilasMo** [comment] 2021-12-16 21:16
Thanks I will try to build tomorrow.  It seems like everything has been solved.

**Comment by trufae** [comment] 2021-12-17 20:54
Unfortunely the ndk21 only supports down to abi16. And kitkat is abi9. So i should lower the ndk and that will make it incompatible with new androids in theory. So if you can try to build with older ndks and make a pr for it (i tweaked the shellscript yhat installs the ndk in sys/ to make that configurable by passing arguments)

**Comment by SilasMo** [comment] 2021-12-17 21:38
which ndk do you suggest I use? Currently I have revision 20b. Should I lower it even the more?

**Comment by trufae** [comment] 2021-12-17 22:15
Wait. Before going further. I just found some docs saying kitkat is abi19, not abi9 so maybe it was a typo. Let me send u the link of the last ci build so u can try :) its for abi16 so even lower than kitkat should work in theory

**Comment by SilasMo** [comment] 2021-12-18 00:33
I was confused since you mentioned abi 9. I didnt ask because I thought my question would be stupid so I kept it to myself. Thanks am enlightened.

**Comment by trufae** [comment] 2021-12-18 09:10
Try this one : https://github.com/radareorg/radare2/releases/download/5.5.4/radare2-5.5.5-android-arm.tar.gz

**Comment by SilasMo** [comment] 2021-12-18 19:32
It failed again. 
```
u0_a103@goyave3g:/ $ export PATH=/storage/sdcard0/Download/data/data/radare2-5.5.5-android-arm/data/data/org.radare.radare2installer/radare2/bin:$PATH               
u0_a103@goyave3g:/ $ export LD_LIBRARY_PATH=/storage/sdcard0/Download/data/data/radare2-5.5.5-android-arm/data/data/org.radare.radare2installer/radare2/lib:$LD_LIBRARY_PATH                                          
u0_a103@goyave3g:/ $ t2
/system/bin/sh: t2: not found
127|u0_a103@goyave3g:/ $ r2
CANNOT LINK EXECUTABLE: could not load library "libr_cons.so" needed by "radare2"; caused by "libr_cons.so" is too small to be an ELF executable
1|u0_a103@goyave3g:/ $ r2
CANNOT LINK EXECUTABLE: could not load library "libr_cons.so" needed by "radare2"; caused by could not load library "libr_util.so" needed by "libr_cons.so"; caused by cannot locate symbol "__register_atfork" referenced by "libr_util.so"...
1|u0_a103@goyave3g:/ $ 
```
I wish I could be but I am of little knowledge and a weak mind. 

When compiling do you use prebuilt binaries or you make a standalone toolchain?
When I tried to build I used the prebuilt `armv7a-linux-androideabi19-clang` as the C compiler amd it said C compiler not working. Is clang not supported?

**Comment by SilasMo** [comment] 2022-03-09 19:51
> r2 builds fine with ALL known C compilers, gcc, clang, msvc, tcc, icc, ...
> 
> the decision to switch to clang from gcc by google is unrelated to r2 but r2 was building with gcc and now its building with clang, the scripts has changed because google released a couple of broken NDKs and the last ones use a different way to construct the environment to compile. bubt it should be possible to do that.
> 
> maybe a better solution would be to just create a library with this __register_atfork symbol and use LD_PRELOAD so you dont need to build with an ancient ndk.
> 
> i have little time, and im considering this ticket a low prio, feel free to update it if you make another try.
> 
> thanks

Thanks brother. Your effort means everything.

**Comment by trufae** [comment] 2023-03-30 10:52
Closing as long as its not an issue in r2

**Closed by trufae** 2023-03-30 10:52 UTC

**Comment by chouex** [comment] 2024-01-15 09:11
sloved by `cp /data/data/org.radare.radare2installer/radare2/lib/* /system/lib64/`
