### ISSUE TITLE
Support `@a:arch:bits` modifiers for `pa` instructions

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#14775] opened 2019-08-09 05:30 UTC
So the command like
```
[0x00000000]> "pa mov eax, 1; nop" @a:x86:16 @ 0x500
```
would work

**Comment by radare** [comment] 2019-08-09 06:14
Use @b: for bits and it will work

**Comment by XVilka** [comment] 2019-08-09 06:19
@radare still a bug, since `@a:arch[:bits]` still is how it is supposed to work.

**Comment by radare** [comment] 2019-08-09 06:25
Works with pd?

**Comment by XVilka** [comment] 2019-08-09 06:40
@radare yes, it is.

**Comment by radare** [comment] 2019-08-18 19:34
the problem is the quotes. we can only fix this with an improved command parser

**Comment by ret2libc** [comment] 2020-04-22 13:08
```
[0x00000000]> "pa mov ax, 1" @a:x86:16 @0x500
b80100
[0x00000000]> "pa mov ax, 1" @a:x86:32 @0@0x500
66b80100
```

This works with `cfg.newshell=1` (aka the new parser). I think we can close this.

**Closed by ret2libc** 2020-04-22 13:08 UTC
Labels: RAsm-Assembler, command, good first issue, high-priority, test-required
