### ISSUE TITLE
PPC lbzu    r9, 1(r4) instruction does not update r4

### ISSUE THREAD

**Issue by TommyBurger** [radareorg/radare2#15246] opened 2019-10-09 22:53 UTC
**Environment information**
* Operating System: Ubuntu Linux 16.04
* Cutter version:
Version 1.9.0 (built from source on 10/9/2019)
Using r2-3.9.0-137-gf6036ff
* File format: elf

**Describe the bug**
Using the following c source:
//powerpc-linux-gnu-gcc test.c -Os -nostdlib
void func(char *p1, char *p2)
{
  while(*p1++ = *p2++)
    ;
}
int _start()
{
  char buff[64];
  func(buff, "Hello, World.");
}

willl generate object code that includes:

28: sym.func ();
0x100000b8      addi    r4, r4, 0xffff ; [02] -r-x section size 72 named .text
0x100000bc      addi    r3, r3, 0xffff
0x100000c0      lbzu    r9, 1(r4)
0x100000c4      stbu    r9, 1(r3)
0x100000c8      cmpwi   cr7, r9, 0
0x100000cc      bne     cr7, 0x100000c0
0x100000d0      blr

The lbzu and stbu instructions should update r3 and r4 with the new effective address. It does not and ends up looping forever.

**To Reproduce**

1. Create a file from the above source.
2. Compile with powerpc-linux-gnu-gcc test.c -Os -nostdlib
3. Open the resulting a.out with Cutter
4. Start emulation in Cutter.
5. Step until lbzu and stbu instructions.
6. Observe r3 and r4 do not change and loops forever.

File:
[a.out.zip](https://github.com/radareorg/cutter/files/3712704/a.out.zip)

**Comment by ITAYC0HEN** [comment] 2019-10-10 13:35
No need to close, I simply transferred it :)

**Comment by radare** [comment] 2019-10-11 09:00
r3 and r4 are not touched inside the loop. so thats why they dont change

**Comment by radare** [comment] 2019-10-11 09:00
so the problem is the branch analysis destination is incorrect :? ppc.gnu plugin gives a different analysis loop

**Comment by radare** [comment] 2019-10-11 09:10
onlinedisassemblmer shows the same as capstone, so the gnu analysis plugin is wrong, but i dont see those r3, r4 registers being modified inside the loop att all

<img width="679" alt="Screenshot 2019-10-11 at 11 08 53" src="https://user-images.githubusercontent.com/917142/66639633-874ec480-ec17-11e9-9e97-d7d484ee9357.png">

**Comment by TommyBurger** [comment] 2019-10-11 10:20
The 'u' in lbzu and stbu stands for "update mode". In this case the source address register is updated with the new effective address. This link: http://www.eecs.umich.edu/courses/eecs373.w04/Lectures/stever_old_lectures/lec2.pdf page 2-3 describes this.

**Closed** 2019-10-11 10:59 UTC

**Comment by radare** [comment] 2019-10-11 11:02
Thanks for the documentation! i just updated the esil expressions accordingly.

See 26981d23b7f944af10d2ad7ac79360598223c3ab for omre details if you want to improve it or fix other bugs in the future.

i also added a test in r2r
