### ISSUE TITLE
disassemble error on arm data.rel.ro

### ISSUE THREAD

**Issue by smartether** [radareorg/radare2#19987] opened 2022-04-22 03:30 UTC
## Description

code 
void*  _Pthread_plt_addr_rel = (void*)0xff09f0;
extern "C" void** const _Pthread_plt_addr{ &_Pthread_plt_addr_rel};

disassemble error on arm data.rel.ro
## Test

![image](https://user-images.githubusercontent.com/3928724/164590652-2c165187-4443-4565-bfe8-f57378232c06.png)

![image](https://user-images.githubusercontent.com/3928724/164590623-9e837756-5255-4e27-a31a-73d360e4bcc9.png)

**Comment by trufae** [comment] 2023-05-04 07:26
Closing as there's no reproducer or feedback for more than a year and i dont see the bin.cache flag passed in the screenshot which is the reason why the relocs arent patched

**Closed by trufae** 2023-05-04 07:26 UTC
