### ISSUE TITLE
r2 can not find strings after reopen

### ISSUE THREAD

**Issue by krial057** [radareorg/radare2#14708] opened 2019-07-30 22:18 UTC
# r2 can not find strings after reopen

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86_64 64
| File format of the file you reverse (mandatory)      | ELF64
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0-git 22408 @ linux-x86-64 git.3.6.0-282-g1f8366427 commit: 1f8366427d0fd9890948381d9ee94e6a482c0aa4 build: 2019-07-30__18:05:12

### Expected behavior
'izz' should show strings in binary after 'doo'. Before executing 'doo' strings are shown correctly using 'izz'
### Actual behavior
'izz' doesn't show any strings after reopening the executable with 'doo'.

### Steps to reproduce the behavior 
Execute the following commands:
- r2 -d /bin/ls
- Enter 'izz' in the r2 shell
- All strings are shown
- Enter 'doo' in the r2 shell
- Enter 'izz' in the r2 shell
- No strings are shown

**Comment by ret2libc** [comment] 2020-07-27 14:07
This seems to be fixed to me. I'm going to close the issue, but please feel free to re-open it if it doesn't work as intended for you. Thanks for reporting this issue!

**Closed by ret2libc** 2020-07-27 14:07 UTC
Labels: RBin, RDebug, high-priority, test-required
