### ISSUE TITLE
Fixing relocations using "-e bin.cache=true" causes loss of function analysis

### ISSUE THREAD

**Issue by chinmaydd** [radareorg/radare2#20616] opened 2022-08-19 17:45 UTC
## Environment

```sh
$ # Fri 19 Aug 2022 10:31:14 AM PDT
$ # radare2 5.7.7 28702 @ linux-x86-64 git.5.7.2-370-g46d7213db
$ # commit: 46d7213dba3408d81b181ddf7f4101e82e2134e3 build: 2022-08-19__10:24:29
$ # Linux x86_64
```

## Description

I am currently analyzing a simple Linux Kernel module which is a relocatable. The two functions of interest are `hello_init` and `hello_cleanup`.

To fix relocations, I am using `-e bin.cache=true` when loading the binary for analysis and then `aaa` after for function recognition. Without fixing relocations, functions are identified correctly, but on applying `-e bin.cache=true` before running `aaa`, some function analysis is lost. See example below:

## Test

```
 $ r2 binary
Warning: run r2 with -e bin.cache=true to fix relocations in disassembly
 -- Select your architecture with: 'e asm.arch=<arch>' or r2 -a from the shell
[0x08000094]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze all functions arguments/locals
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Finding and parsing C++ vtables (avrr)
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information (aanr)
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x08000094]> pdf @ sym.hello_cleanup 
            ;-- section..exit.text:
            ;-- .exit.text:
            ;-- cleanup_module:
┌ 18: sym.hello_cleanup ();
│           0x080000ad      55             push rbp                    ; [06] -r-x section size 18 named .exit.text
│           0x080000ae      48c7c7000000.  mov rdi, 0                  ; RELOC 32 .rodata.str1.1 @ 0x080000bf + 0x10
│           0x080000b5      4889e5         mov rbp, rsp
│           0x080000b8      e800000000     call _printk                ; RELOC 32 _printk
│           ; CALL XREF from sym.hello_cleanup @ 0x80000b8(x)
│           0x080000bd      5d             pop rbp
└           0x080000be      c3             ret
[0x08000094]> 
```

As can be seen, function `hello_cleanup` is identified (relocations are not fixed)

```
$ r2 -e bin.cache=true binary
 -- Add custom Have you setup your ~/.radare2rc today?
[0x08000094]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze all functions arguments/locals
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Finding and parsing C++ vtables (avrr)
[INFO: [ESIL] Trap, trying to execute on non-executable memory
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information (aanr)
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x08000094]> pdf @ sym.hello_cleanup
ERROR: Cannot find function at 0x080000ad
[0x08000094]> pdf @ sym.hello_init 
            ;-- section..text:
            ;-- section..init.text:
            ;-- .text:
            ;-- .init.text:
            ;-- reloc.init_module:
            ;-- reloc..init.text:
            ;-- init_module:
            ;-- rip:
┌ 25: sym.hello_init ();
│           0x08000094      e8c5df0000     call __fentry__             ; RELOC 64 .init.text @ 0x08000094 ; [04] -r-x section size 25 named .init.text
│           0x08000099      55             push rbp
│           0x0800009a      48c7c7bf0000.  mov rdi, reloc..rodata.str1.1 ; 0x80000bf
│           0x080000a1      4889e5         mov rbp, rsp
│           0x080000a4      e8bddf0000     call _printk
│           0x080000a9      31c0           xor eax, eax
│           0x080000ab      5d             pop rbp
└           0x080000ac      c3             ret
```
In this case, no function is identified at `0x08000094`. But `hello_init` is identified - which means that its only certain function analysis is lost.  

File is base64 encoded here: https://gist.github.com/chinmaydd/4c0b537609984e367039daaec64d17df

**Comment by trufae** [comment] 2022-08-23 20:15
Thanks for reporting and the detailed explanation!

Turns out the root cause of this was because io.isValidAddress() didnt read the bytes from the underlying io before calling the cacheRead(), this was making another check to fail causing some memory addresses to be considered invalid causing the analysis to stop working.

Should be fixed no!

**Closed** 2022-08-23 21:25 UTC
