### ISSUE TITLE
TCC build fails

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#4328] opened 2016-03-16 14:35 UTC
```
make[4]: Entering directory `/var/lib/jenkins/workspace/radare2-tcc/libr/io/p'
tcc -shared -Dxx -o lib.so -I../../include -Wall -DWORDSIZE=64 -fPIC -shared -Dxx -L.. -DCORELIB    -fPIC -g -Wall -D__UNIX__=1 -I/var/lib/jenkins/workspace/radare2-tcc/libr/../shlr/gdb/include/ -I/var/lib/jenkins/workspace/radare2-tcc/libr/../shlr/wind -o io_ptrace.so -shared -Dxx \
    -shared -o io_ptrace.so  /var/lib/jenkins/workspace/radare2-tcc/libr/../shlr/gdb/lib/libgdbr.a -lutil /var/lib/jenkins/workspace/radare2-tcc/libr/../shlr/wind/libr_wind.a \
    -L../../util -L../../util -lr_util \
    -L.. -L.. -lr_io io_ptrace.o
tcc: warning: -shared: some compiler action already specified (3)
tcc: warning: multiple -o option
tcc: warning: -shared: some compiler action already specified (3)
tcc: warning: -shared: some compiler action already specified (3)
tcc: warning: multiple -o option
../libr_io.so: error: referenced dll 'libr_socket.so' not found
...
tcc -shared -Dxx -o libr_fs.so -Dxxlibr_fs.so p/fs_cpio.o p/fs_ext2.o p/fs_fat.o p/fs_fb.o p/fs_hfs.o p/fs_hfsplus.o p/fs_iso9660.o p/fs_jfs.o p/fs_minix.o p/fs_ntfs.o p/fs_posix.o p/fs_reiserfs.o p/fs_sfs.o p/fs_tar.o p/fs_udf.o p/fs_ufs.o p/fs_xfs.o fs.o file.o    -L/var/lib/jenkins/workspace/radare2-tcc/libr/util -L/var/lib/jenkins/workspace/radare2-tcc/libr/io -lr_util -lr_io   -fPIC    /var/lib/jenkins/workspace/radare2-tcc/libr/../shlr/grub/libgrubfs.a
/var/lib/jenkins/workspace/radare2-tcc/libr/io/libr_io.so: error: referenced dll 'libr_socket.so' not found
tcc: error: cannot find library 'libr_io'
make[4]: *** [libr_fs.so] Error 1
...
make[4]: Entering directory `/var/lib/jenkins/workspace/radare2-tcc/libr/bin/p'
tcc -shared -o bin_any.so -ldl    -fPIC -g -Wall -D__UNIX__=1 -I/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/include -I/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/bin/format/ -Wall -fPIC -I/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/include -I/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/include bin_any.o      -fPIC /var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/librz.a -L../../db -lr_db -L../../db -lr_db /var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/sdb/src/libsdb.a -L../../db -lr_db -L../../db -lr_db /var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/librz.a  -L/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/util -lr_util -L/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/bin -lr_bin \
-L../../magic -lr_magic \
-L../../util -lr_util
/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/bin/libr_bin.so: error: referenced dll 'libr_io.so' not found
tcc: error: cannot find library 'libr_bin'
make[4]: *** [bin_any.so] Error 1
make[4]: Leaving directory `/var/lib/jenkins/workspace/radare2-tcc/libr/bin/p'
```

**Comment by radare** [comment] 2016-03-16 16:03
im aware of this, this is why i filled many issues trying to remove the
r_io and r_cons dependencies from many r2 modules. this way there will be
no problem for the tcc linker

On 16 March 2016 at 15:35, Anton Kochkov <notifications@github.com> wrote:

> make[4]: Entering directory `/var/lib/jenkins/workspace/radare2-tcc/libr/io/p'
> tcc -shared -Dxx -o lib.so -I../../include -Wall -DWORDSIZE=64 -fPIC -shared -Dxx -L.. -DCORELIB    -fPIC -g -Wall -D__UNIX__=1 -I/var/lib/jenkins/workspace/radare2-tcc/libr/../shlr/gdb/include/ -I/var/lib/jenkins/workspace/radare2-tcc/libr/../shlr/wind -o io_ptrace.so -shared -Dxx \
>     -shared -o io_ptrace.so  /var/lib/jenkins/workspace/radare2-tcc/libr/../shlr/gdb/lib/libgdbr.a -lutil /var/lib/jenkins/workspace/radare2-tcc/libr/../shlr/wind/libr_wind.a \
>     -L../../util -L../../util -lr_util \
>     -L.. -L.. -lr_io io_ptrace.o
> tcc: warning: -shared: some compiler action already specified (3)
> tcc: warning: multiple -o option
> tcc: warning: -shared: some compiler action already specified (3)
> tcc: warning: -shared: some compiler action already specified (3)
> tcc: warning: multiple -o option
> ../libr_io.so: error: referenced dll 'libr_socket.so' not found
> ...
> tcc -shared -Dxx -o libr_fs.so -Dxxlibr_fs.so p/fs_cpio.o p/fs_ext2.o p/fs_fat.o p/fs_fb.o p/fs_hfs.o p/fs_hfsplus.o p/fs_iso9660.o p/fs_jfs.o p/fs_minix.o p/fs_ntfs.o p/fs_posix.o p/fs_reiserfs.o p/fs_sfs.o p/fs_tar.o p/fs_udf.o p/fs_ufs.o p/fs_xfs.o fs.o file.o    -L/var/lib/jenkins/workspace/radare2-tcc/libr/util -L/var/lib/jenkins/workspace/radare2-tcc/libr/io -lr_util -lr_io   -fPIC    /var/lib/jenkins/workspace/radare2-tcc/libr/../shlr/grub/libgrubfs.a
> /var/lib/jenkins/workspace/radare2-tcc/libr/io/libr_io.so: error: referenced dll 'libr_socket.so' not found
> tcc: error: cannot find library 'libr_io'
> make[4]: *** [libr_fs.so] Error 1
> ...
> make[4]: Entering directory `/var/lib/jenkins/workspace/radare2-tcc/libr/bin/p'
> tcc -shared -o bin_any.so -ldl    -fPIC -g -Wall -D__UNIX__=1 -I/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/include -I/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/bin/format/ -Wall -fPIC -I/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/include -I/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/include bin_any.o      -fPIC /var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/librz.a -L../../db -lr_db -L../../db -lr_db /var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/sdb/src/libsdb.a -L../../db -lr_db -L../../db -lr_db /var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/librz.a  -L/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/util -lr_util -L/var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/bin -lr_bin \
> -L../../magic -lr_magic \
> -L../../util -lr_util
> /var/lib/jenkins/workspace/radare2-tcc/libr/..//libr/bin/libr_bin.so: error: referenced dll 'libr_io.so' not found
> tcc: error: cannot find library 'libr_bin'
> make[4]: *** [bin_any.so] Error 1
> make[4]: Leaving directory `/var/lib/jenkins/workspace/radare2-tcc/libr/bin/p'
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4328>
>



-- 
--pancake

**Comment by MaskRay** [comment] 2017-09-13 06:13
Can be closed?

**Comment by XVilka** [comment] 2017-09-13 07:00
@MaskRay no - it still fails: http://ci.rada.re/job/radare2-tcc/2523/console

**Comment by XVilka** [comment] 2017-12-29 04:36
Wonder, can it be a problem of a paths?
```
tcc -shared -o bin_any.so -ldl    -fPIC -g -Wall -D__UNIX__=1 -I/home/jenkins/workspace/radare2-tcc/libr/..//libr/include -I/home/jenkins/workspace/radare2-tcc/libr/..//libr/bin/format/ -Wall -fPIC -I/home/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/include -I/home/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/include bin_any.o      -fPIC /home/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/librz.a /home/jenkins/workspace/radare2-tcc/libr/..//libr/../shlr/zip/librz.a  -L/home/jenkins/workspace/radare2-tcc/libr/..//libr/util -lr_util -L/home/jenkins/workspace/radare2-tcc/libr/..//libr/bin -lr_bin -L/home/jenkins/workspace/radare2-tcc/libr/..//libr/io -lr_io \
-L../../magic -lr_magic \
-L../../util -lr_util
/home/jenkins/workspace/radare2-tcc/libr/..//libr/io/libr_io.so: error: referenced dll 'libr_socket.so' not found
/home/jenkins/workspace/radare2-tcc/libr/..//libr/bin/libr_bin.so: error: referenced dll 'libr_io.so' not found
```
Is sequence "/..//" ever valid?

**Comment by radare** [comment] 2018-01-03 10:31
yes /..// is valid on all unixes

**Comment by radare** [comment] 2018-01-03 10:31
how to reproduce? builds fine on all my machines, and farm

**Comment by XVilka** [comment] 2018-01-03 16:43
see ci.rada.re

**Comment by XVilka** [comment] 2018-05-19 13:09
Are there any ideas why it still happens? http://ci.rada.re/job/radare2-tcc/6191/consoleFull

**Comment by radare** [comment] 2018-05-20 01:58
404?

**Comment by XVilka** [comment] 2018-05-20 03:41
404 because it removes old builds. Here is the permanent link http://ci.rada.re/job/radare2-tcc/lastBuild/consoleFull

**Comment by radare** [comment] 2018-05-20 08:55
Because of jemalloc crappy includes

**Comment by ret2libc** [comment] 2018-09-12 06:54
Removing me from the assignees because I don't even use TCC.

**Comment by ret2libc** [comment] 2020-07-16 13:09
I think it is compiling now, isn't it? Closing, feel free to re-open if I'm mistaken.

**Comment by trufae** [comment] 2020-07-16 16:56
tcc build is still failing, actually i found two bugs in the compiler and the mk compiler definition. ive created a PR to work on that, seems like macOS support for tcc is not yet able to build libraries, so ill chk with linux

**Closed** 2020-12-11 08:42 UTC
Labels: bug, buildsystem, good first issue
