### ISSUE TITLE
Problem with calling conventions on Arch Linux

### ISSUE THREAD

**Issue by theguy147** [radareorg/radare2#18916] opened 2021-07-18 20:29 UTC
## Environment

OS: Arch Linux

```sh
Sun Jul 18 07:49:30 PM UTC 2021

radare2 5.3.1 0 @ linux-x86-64 git.5.3.1
commit: unknown build: 2021-06-12__00:39:47

Linux x86_64
```

Side note: radare2 was installed with `pacman` from the official community repository on Arch Linux. The same issue also occurs when installing radare2 from the master branch on GitHub (at the time of this writing the commit is 45119050d8c1329d5f61adc587c79013d15afc67).

## Description

When opening a binary with r2 I get the following warning: `No calling convention defined for this file, analysis may be inaccurate`. This is true for every binary I tried (all of them were x86_64 ELF binaries).

After analyzing the binary (`aaa`) the `afcl` command only lists `reg` as a calling convention and not the expected ones including `amd64` that I see on other Operating Systems for the same binaries.

Also the function prototypes (of e.g. imported libc functions) are missing in the comments next to the assembly. I suspect this to be an connected issue.

#### Example program

```c
// file: test.c
#include<stdio.h>

int main() {
    printf("Hello World\n");
    return 0;
}
```

Simple compilation with:
```sh
gcc -otest test.c
```

#### Issue on Arch Linux (the output I get)

```sh
r2 -Aq -c "afcl; pdf @ sym.main" test
```
```
Warning: run r2 with -e bin.cache=true to fix relocations in disassembly
WARNING: No calling convention defined for this file, analysis may be inaccurate.
Warning: set your favourite calling convention in `e anal.cc=?`
reg
            ; DATA XREF from entry0 @ 0x1061
┌ 26: main ();
│           0x00001139      55             push rbp
│           0x0000113a      4889e5         mov rbp, rsp
│           0x0000113d      488d05c00e00.  lea rax, str.Hello_World    ; 0x2004 ; "Hello World"
│           0x00001144      4889c7         mov rdi, rax
│           0x00001147      e8e4feffff     call sym.imp.puts
│           0x0000114c      b800000000     mov eax, 0
│           0x00001151      5d             pop rbp
└           0x00001152      c3             ret

```

#### Comparison on Ubuntu Machine (the expected output)

```sh
r2 -Aq -c "afcl; pdf @ sym.main" test
```
```
Warning: run r2 with -e bin.cache=true to fix relocations in disassembly
amd64
amd64syscall
ms
reg
swift
            ; DATA XREF from entry0 @ 0x1081
┌ 27: int main (int argc, char **argv, char **envp);
│           0x00001149      f30f1efa       endbr64
│           0x0000114d      55             push rbp
│           0x0000114e      4889e5         mov rbp, rsp
│           0x00001151      488d3dac0e00.  lea rdi, str.Hello_World    ; 0x2004 ; "Hello World" ; const char *s
│           0x00001158      e8f3feffff     call sym.imp.puts           ; int puts(const char *s)
│           0x0000115d      b800000000     mov eax, 0
│           0x00001162      5d             pop rbp
└           0x00001163      c3             ret
```

**Comment by trufae** [comment] 2021-07-19 09:24
i wish i could reproduce :_ i tried on all my linux and macos machines and everything works fine here.

All this info is stored in sdb and the bug appeared when i introduced support for gperf and compiletime databases.

Can you try building with `--without-gperf`? can you share the full build log of the failing installations? may be good to have a CI job to repro the issue too.

thanks!

**Comment by theguy147** [comment] 2021-07-19 12:29
So, I did some further testing and I have to admit an error on my initial report: I thought I also tried building `radare2` using the `sys/install.sh` script instead of Arch's distro packager `pacman` but as it looks like I haven't because that works fine on a fresh Arch Linux install. So it is actually the `pacman` build (both `community/radare2` and `aur/radare2-git`) that are not working.

**I am not sure if this issue should be further discussed here but in case it actually is an underlying radare2 issue that causes the problem I narrowed it down further.**

`pacman` uses `meson` to build the package like this:

```sh
  arch-meson build \
    -D use_sys_capstone=true \
    -D use_capstone_version=v4 \
    -D use_sys_magic=true \
    -D use_sys_zip=true \
    -D use_sys_zlib=true \
    -D use_sys_lz4=true \
    -D use_sys_xxhash=true \
    -D use_sys_openssl=true \
    -D use_sys_tree_sitter=true \
    -D use_libuv=true \
    -D use_webui=true \
    -D tree-sitter-sync=true
  ninja -C build
```

where `arch-meson` expands to `meson setup --prefix /usr --libexecdir lib --sbindir bin --buildtype plain --auto-features enabled --wrap-mode nodownload -D b_lto=true -D b_pie=true`

**when changing the meson buildtype from `plain` to `release` the issue disappears completely!** 

I don't know a lot about `meson` but according to https://mesonbuild.com/Running-Meson.html the `plain` buildtype is explained as follows: "no extra build flags are used, even for compiler warnings, useful for distro packagers and other cases where you need to specify all arguments by yourself" whereas `release` has "full optimization, no debug info".

it looks like `radare2` needs some of the optimizations or default build flags included in the `release` build type to work properly and identifying the needed ones would probably solve this problem once and for all. Again I'm not sure if that is an issue that the radare community should solve or rather the Arch Linux community...

**Comment by trufae** [comment] 2021-07-19 22:50
So the issue is only happening when building with meson? Actually gperf is not used or needed because despite being an awesome tool its not viable for large datasets so i end up doing my own cgen in sdb. Ill check it out and fix this. Disabling this option by default will make static builds not usable without support files

**Comment by trufae** [comment] 2021-07-19 22:50
Thanks for so much testing and details! Its really helpful

**Comment by trufae** [comment] 2021-07-19 22:51
Btw treesitter is no longer used in r2, if you are in touch with the arch maintainer it may be good to remove such flags from the meson line

**Comment by theguy147** [comment] 2021-07-19 22:57
> So the issue is only happening when building with meson? 

Yes, at least in my tests the problem only happened with `meson`

> Btw treesitter is no longer used in r2, if you are in touch with the arch maintainer it may be good to remove such flags from the meson line

Yes, I noticed as well. I will try to contact the arch maintainer. It will be better to remove unneeded dependencies from the package manager.

**Comment by trufae** [comment] 2021-07-23 06:29
This is fixed in master. Thanks for reporting and testimg!

**Closed by trufae** 2021-07-23 06:29 UTC
