### ISSUE TITLE
Basic blocks which end in call to non-returning functions should not have a 'fail' field

### ISSUE THREAD

**Issue by chinmaydd** [radareorg/radare2#20684] opened 2022-09-05 19:24 UTC
## Description

For an analysis project, I am using `pdbj` to collect successors to basic blocks via radare2. Specifically, I am using the `jump` and `fail` fields to get their addresses. 

In this specific binary, there is a basic block which ends in a call to a non-returning function (`__assert_fail`) and the followthrough address is the start of a different function.

```
[0x00401780]> pd 15 @ 0x004020c1
│           ; CODE XREF from sym.wordcount_splitter @ 0x401b2c(x)
│           0x004020c1      488d0d4e1600.  lea rcx, obj.__PRETTY_FUNCTION__.2 ; 0x403716 ; "MALLOC" ; const char *function
│           0x004020c8      ba34000000     mov edx, 0x34               ; '4' ; 52 ; unsigned int line
│           0x004020cd      488d35891500.  lea rsi, str..._.._include_stddefines.h ; 0x40365d ; "../../include/stddefines.h" ; const char *file
│           0x004020d4      488d3d9d1500.  lea rdi, str.temp           ; 0x403678 ; "temp" ; const char *assertion
└           0x004020db      e870f1ffff     call sym.imp.__assert_fail  ; void __assert_fail(const char *assertion, const char *file, unsigned int line, const char *function)
            ; CALL XREFS from sym.wordcount_map @ 0x4022f9(x), 0x40237e(x)
┌ 405: sym.wordcount_reduce (int64_t arg1, int64_t arg2);
│ rg: 2 (vars 0, args 2)
│ bp: 0 (vars 0, args 0)
│ sp: 5 (vars 5, args 0)
│           0x004020e0      f30f1efa       endbr64
│           0x004020e4      4157           push r15
│           0x004020e6      4863f6         movsxd rsi, esi             ; arg2
│           0x004020e9      4156           push r14
```

I tried marking the address of `sym.imp.__assert_fail` as noreturn through `tn` and then running all analyses via `aaa` but this still persists. The way I am handling it right now is checking if the callee function exists in the list provided by `tn` and filtering out those addresses.

More generally, if `fail` represents the followthrough address I guess this makes sense. But fundamentally, if a call to a `noreturn` function is made I think it would be more appropriate if the `fail` field is NOT present. I would like to hear thoughts on this. Thanks!

**Comment by trufae** [comment] 2022-09-07 14:35
You mean the RAnalOp.fail to be ut64.max when RAnalOp.jump points to a noreturn symbol? yeah taht seems reasonable :)

do you want to make the fix? otherwise i can pile this up to my todo list for this week

**Comment by trufae** [comment] 2022-09-07 14:37
i mean, if the ranalop provides no fail in that call, the basicblock info will have no fail line. so it should be only one place to fix this behaviour

**Comment by chinmaydd** [comment] 2022-09-07 23:30
Ah, you are right -- that seems like the appropriate way to fix it. One can identify for the `ut64.max` value when looking for the successor.

I would like to fix it, but I am busy for the next couple of weeks. If its not a priority/blocker, I can give it a shot soon.

**Comment by trufae** [comment] 2022-09-08 17:34
After some testing i think the problem is that you are asuming the instruction information is the same as the basic block one. when you do `pdbj` you are disassembling every basic block instruction. but this output doesnt contain the information of the basic block itself. to get that you can use `abj`. Maybe `pdbj` should also include the information of the basic blocks, but this would change the schema of the json and some people may be affected. but im fine for changing json outputs if its for the better

**Comment by trufae** [comment] 2022-09-09 13:49
I have improved the support for noreturn propagation with some new commands as well as for listing the callers of a function to script them out. I have pushed a branch with my experiments with the ut64 in the analop. buti dont think that would be correct because the instruction itself doesnt change. and that noreturn information is not propagated backwards, so it needs to reanalize recursively when one noreturn function is found. So i would close this ticket, and continue experimenting with this branch, feel free to try it out https://github.com/radareorg/radare2/commit/cd5a9c639dcb26f1ec6af90a051670d97c72156d

**Closed by trufae** 2022-09-09 13:49 UTC

**Comment by chinmaydd** [comment] 2022-09-09 19:35
Thanks for all the help pancake!

I see what you mean about using `abj` instead of `pdbj`. The project I am working on is trying to statically build the CFG to mimic dynamically collected traces from QEMU. In QEMU, the unit of execution is a `TranslationBlock`(TB) instead of a `BasicBlock`. In that case, I need to consider each `call` instruction as a TB terminator. For that reason, I need to use `pdbj` to record call targets and fallthroughs appropriately.

> Maybe pdbj should also include the information of the basic blocks, but this would change the schema of the json and some people may be affected

I understand, you are right its best to keep it this way for now.

> buti dont think that would be correct because the instruction itself doesnt change. and that noreturn information is not propagated backwards, so it needs to reanalize recursively when one noreturn function is found

Fair point, each noreturn call is going to kick another analysis loop which might be super expensive.

> So i would close this ticket, and continue experimenting with this branch, feel free to try it out 

Great, I will do that. I think marking the failthrough as `ut64_max` should be good enough for my use case. Thanks again !
