### ISSUE TITLE
aeim should initialize memory defined by bin-plugin

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#8226] opened 2017-08-16 15:26 UTC
aeim once was intended to initialize memory defined by the bin-plugin. ok, I have to admit, that there is only 1 bin-plugin that defines that memory, but we have to start somewhere.

![2017-08-16-172223_1920x1080_scrot](https://user-images.githubusercontent.com/5904302/29371145-11d01b28-8297-11e7-90a2-e222e260f451.png)

with siol this should work in the future

**Comment by XVilka** [comment] 2017-08-16 15:31
Question - how far this future is?
![maxresdefault](https://user-images.githubusercontent.com/203261/29371478-0509c918-82db-11e7-8dcd-f790372a088e.jpg)

**Comment by condret** [comment] 2017-08-16 15:34
at the end of r2con opsiol should be done. Then, ppl can slap my face, when I come up with procrastionation again

**Comment by Maijin** [comment] 2017-08-16 15:46
```
only 1 bin-plugin that defines that memory
```

False. https://github.com/radare/radare2/blob/master/libr/bin/p/bin_nes.c#L108 etc.

**Comment by condret** [comment] 2017-08-16 15:56
wow

**Comment by Maijin** [comment] 2017-08-18 11:55
This issue looks like a duplicate of https://github.com/radare/radare2/issues/6778

**Comment by radare** [comment] 2017-08-27 17:10
ping

**Comment by ret2libc** [comment] 2020-07-01 20:22
Closing as duplicate of https://github.com/radareorg/radare2/issues/6778 .

**Closed by ret2libc** 2020-07-01 20:22 UTC
Labels: ESIL, RBin, RIO
