### ISSUE TITLE
Some ARM binary incorrectly disassembles some instructions

### ISSUE THREAD

**Issue by Tigre000** [radareorg/radare2#14988] opened 2019-09-09 00:31 UTC
# Some ARM binary incorrectly disassembles some instructions

I found out that the radare2 version in docker was low while I was using radare2 as a docker.
So I installed the latest version from github.
But code analysis differents radare2 in latest(version 3.8.0) from radare2 in docker(version 3.3.0-git).

In the latest version, the symbol is strange. (puts, strlen, printf...)

	r2@r2tigre:/mnt/Easy/r2baby$ r2 -v
	radare2 3.8.0 22646 @ linux-x86-64 git.3.8.0
	commit: b4860e4eecad2053202965926f16296864b2f1e5 build: 2019-09-04__08:54:11
	r2@r2tigre:/mnt/Easy/r2baby$ r2 -AA babyr2
	[0x004002b4]> pd 5 @ main+0x20
	|           0x0040041c      600200f0       adrp x0, 0x44f000
	|           0x00400420      00600891       add x0, x0, 0x218           ; 0x44f218 ; "wr0ng length?"
	|           0x00400424      6b1d0094       bl loc._x_53
	|           0x00400428      20008052       movz w0, 0x1
	|           0x0040042c      01170094       bl sym.exit                 ; void exit(int status)

But radare2 in docker is differents than latest version.

	r2@radare2:/mnt/Easy/r2baby$ r2 -v
	radare2 3.3.0-git 1 @ linux-x86-64 git.3.3.0-git
	commit: eecaf9d946a07b66bf32b9680457dbe8df81f507 build: 2019-01-31__19:48:01
	r2@radare2:/mnt/Easy/r2baby$ r2 -AA babyr2
	[0x004002b4]> pd 5 @ main+0x20
	|           0x0040041c      600200f0       adrp x0, 0x44f000
	|           0x00400420      00600891       add x0, x0, 0x218           ; 0x44f218 ; "wr0ng length?" ; const char *s
	|           0x00400424      6b1d0094       bl sym.puts                 ; int puts(const char *s)
	|           0x00400428      20008052       movz w0, 0x1
	|           0x0040042c      01170094       bl sym.exit                 ; void exit(int status)

So I checked the other release versions.
But only the radare2 in docker did it well.

While Searching I found an issue similar to mine.
<https://github.com/radare/radare2/issues/3684>
I refer to it and found a way to solve my issue.
However, I knew that we should use -rs instead of -rSIeMzisRp when writing scripts and run with -I instead of -i.

	r2@r2tigre:/mnt/Easy/r2baby$ r2 -v
	radare2 3.8.0 22646 @ linux-x86-64 git.3.8.0
	r2@r2tigre:/mnt/Easy/r2baby$ rabin2 -rs babyr2 > test.r2
	r2@r2tigre:/mnt/Easy/r2baby$ r2 -AA -I test.r2 babyr2
	[0x004002b4]> pd 5 @ main+0x20
	|           0x0040041c      600200f0       adrp x0, 0x44f000
	|           0x00400420      00600891       add x0, x0, 0x218           ; 0x44f218 ; "wr0ng length?" ; const char *s
	|           0x00400424      6b1d0094       bl sym.puts                 ; int puts(const char *s)
	|           0x00400428      20008052       movz w0, 0x1
	|           0x0040042c      01170094       bl sym.exit                 ; void exit(int status)

Maybe as the version is upgraded, the symbol automatically mappings to the memory during program loading appears to have been disabled.
<code>rabin2 -rs binary > test.r2; r2 -I test.r2 binary; rm -rf test.r2</code>
I think it would be convenient to set the default settings as above code.
Or Maybe solving this bug itself would be convenient too.

**Comment by radare** [comment] 2019-09-09 15:46
can you share the binary?

**Comment by radare** [comment] 2019-09-09 16:20
and to  clarify the issue, the problem is unrelated to ARM and also unrelated to disassembling or with any instruction at all, its just about priority of flags

**Comment by Tigre000** [comment] 2019-09-10 00:40
The binary is a r2baby from r2con ctf.

**Comment by radare** [comment] 2019-10-25 17:00
the issue is not about the disassembler at all, but about the priorities of flags when determining the function name under some situations. thats a regression indeed

**Comment by radare** [comment] 2019-10-25 18:12
![IMAGE 2019-10-25 20:12:47](https://user-images.githubusercontent.com/917142/67594057-d0e4f680-f763-11e9-80e0-f2b19d3e1d21.jpg)

**Comment by ret2libc** [comment] 2019-10-25 18:31
While it is true that the problem is related to flags priority, there is no good way to choose between two symbol names in general. However, the problem with ARM is that there are a lot of symbols in the same place as functions start and those symbols are *mapping symbols* (e.g. $x, $d, $a). What we have done so far is to hide those symbols from the flags and use instead them as hints.

The issue here was that `$x` was not handled on AArch64 and it should be fixed with https://github.com/radareorg/radare2/pull/15362 .

**Closed** 2019-10-25 20:11 UTC
Labels: ARM, RAsm-Disasembler
