### ISSUE TITLE
drt with some options doesn't show registers

### ISSUE THREAD

**Issue by j123123** [radareorg/radare2#6374] opened 2016-12-25 12:04 UTC
```drt mmx```, ```drt xmm``` and ```drt flg``` doesn't show any register in r2 debug mode

**Comment by radare** [comment] 2016-12-26 00:45
Pla specify arch/os pair where this bug can be reproduced

**Comment by j123123** [comment] 2016-12-26 07:29
radare2 1.2.0-git 13307 @ linux-x86-64 git.1.1.0-37-gbc766ba
commit: bc766baf7375a1aa5151cd13ba354429aa0caa72 build: 2016-12-25

Ubuntu 16.04.1 LTS x86_64
```
$ r2 -d /bin/ls
...
[0x7f8571231cc0]> drt mmx
[0x7f8571231cc0]> drt xmm
[0x7f8571231cc0]> drt flg
[0x7f8571231cc0]> 
```

**Comment by skuater** [comment] 2016-12-26 12:54
Linux reg profile have all xmm,mmx,st grouped in fpu.
Theses command show it:
 drt fpu
 dr st0
 dr xmm0h
 drf
and u can modify using (dr cant use in linux to modify fpu registers yet ...):
 drm
 
Also u can use 'drp' to show the loaded profile.

**Comment by j123123** [comment] 2016-12-26 13:58
@skuater OK, but what if I want to see only XMM, MMX or FLAGS register?
For exampe, ``drt drx`` works correctly and shows me all debug registers. When I type ``drt flg`` I expect to get something like
````
rflags = 0x00000200
eflags = 0x00000200
cf = 0x00000000
pf = 0x00000000
af = 0x00000000
zf = 0x00000000
sf = 0x00000000
tf = 0x00000000
if = 0x00000001
df = 0x00000000
of = 0x00000000
ss = 0x0000002b
````
but I get nothing

**Comment by skuater** [comment] 2016-12-26 14:58
@j123123 no way , to solve this is needed do some changes into reg profile for linux. Ill try to implement when get some free time

**Comment by skuater** [comment] 2017-03-12 12:56
working on it

**Comment by XVilka** [comment] 2017-06-09 04:01
@RKX1209 @SrimantaBarua FYI.

**Comment by ret2libc** [comment] 2020-06-22 13:44
@abcSup could you please have a quick look at this when you have some time? It may be they are already fixed, but you know for sure better those parts of the code. Thanks!

**Comment by abcSup** [comment] 2020-06-22 14:18
`drt mmx` and `drt xmm` work. But, `drt flg` does not work because it is skipped.
https://github.com/radareorg/radare2/blob/a64cd129511c178851f385e97759a2012ef71d0f/libr/debug/dreg.c#L151-L153
I think I could remove those lines and make a PR to close this issue if there is no issue along the way.

**Closed** 2020-07-13 10:09 UTC
Labels: RDebug, enhancement
