### ISSUE TITLE
Make r2 offline installable

### ISSUE THREAD

**Issue by bannsec** [radareorg/radare2#15497] opened 2019-11-24 15:37 UTC
**Is your feature request related to a problem? Please describe.**
It is quite painful (even more-so lately with the new dependencies) to install radare2 in an offline environment.

**Describe the solution you'd like**
r2's installer for some reason utilizes scripted git pulls of specific branches. The better way in my opinion, and offline friendly way, is to utilize git's submodule support. This would both simplify your install scripts (since they wouldn't need to rely on pulling externally) and make r2 offline installable from a simple `git clone --recursive`

**Describe alternatives you've considered**
I have created my own jenky scripts that involve `sed` editing the r2 installer and copying over specific versions of dependency libraries. It always breaks when r2 updates any of it's dependency handling.

**Additional context**
There is some offline flag in the setup related to capstone i believe, but that only handles capstone and it is not a submodule, meaning you still have to manually clone capstone and move it into the right directory, then use the correct flag. Even with that, the numerous other external dependencies will still fail.

**Comment by radare** [comment] 2019-11-24 16:13
we need to apply patches on this cloned repo, submodules are not distribuetd on github tarballs so the release tarballs will be broken, we have been discussing this for years and still github didnt solved the problem..well there are git subtrees, but it's a different monster

**Comment by bannsec** [comment] 2019-11-24 16:14
Perhaps there could be a "sys/prepare_offline.sh" or something that would do all the necessary cloning?

**Comment by radare** [comment] 2019-11-24 18:21
yeah we need a solution for this and i vote for simplifying it as much as possible

**Comment by ret2libc** [comment] 2019-12-02 07:42
What about using submodules and just improve radare2-release to generate a tarball with all the dependencies inside?

**Comment by radare** [comment] 2019-12-02 08:38
We can do sys/install handle all the git submodules so that will be seamless for the users. And the tarball is generated with “make dist”. Im happy about making this change now

* capstone
* spp
* sdb

Dunno if im missing anything

**Comment by XVilka** [comment] 2019-12-02 08:46
There is another way to proceed - generate the release tarballs with GitHub Actions:
- https://github.com/marketplace/actions/github-action-publish-binaries
- https://github.com/actions/upload-artifact
- https://github.com/marketplace/actions/github-upload-release-artifacts
- https://github.com/marketplace/actions/create-release
- https://github.com/actions/upload-release-asset

**Comment by ret2libc** [comment] 2019-12-02 10:37
> We can do sys/install handle all the git submodules so that will be seamless for the users. And the tarball is generated with “make dist”. Im happy about making this change now 
> * capstone
> * spp
> * sdb
> Dunno if im missing anything

* tree-sitter
* radare2-shell-parser

**Comment by ret2libc** [comment] 2019-12-02 10:38
> There is another way to proceed - generate the release tarballs with GitHub Actions:
> 
>     * https://github.com/marketplace/actions/github-action-publish-binaries
> 
>     * https://github.com/actions/upload-artifact
> 
>     * https://github.com/marketplace/actions/github-upload-release-artifacts
> 
>     * https://github.com/marketplace/actions/create-release
> 
>     * https://github.com/actions/upload-release-asset

The problem with relying on github actions, I think, is that it makes us more and more dependent on GitHub. It would be harder to switch to something else, if needed. Anyway, I'm ok with any solution to generate the release tarball.

**Comment by Maijin** [comment] 2019-12-02 14:25
As already discussed here, Submodules aren't followed for tar.gz but subtree are - https://github.com/radareorg/radare2/issues/11730

**Comment by radare** [comment] 2019-12-02 16:03
Yes but now that nobody uses r2 we can break even more things . And using submodules and create a script to pull the things called from sys/install is the way to go imho

**Comment by Maijin** [comment] 2019-12-02 21:13
"nobody uses r2" false. But ok I'm fine with submodules too.

**Comment by hmht** [comment] 2019-12-09 10:41
Riccardo Schirone writes:
> What about using submodules

I'd just like to note that submodules track specific revisions; A commit
to radare2-regressions pretty much requires a commit to radare2 to
update the submodule. As an effect, they don't really play nice with
branches.

This differs from the current system that just grabs whatever is on
master.


Wouldn't it be easiest to allow the user to replace
https://github.com/radareorg/ with /home/user/offline/ or whatever?
Though that wouldn't really simplify the build system.

**Comment by radare** [comment] 2019-12-09 10:43
thats false. the current code checkouts a specific commit from capstone

**Comment by trufae** [comment] 2021-06-15 10:36
It's currently possible to build r2 without internet, you just need to have a system wide installation of capstone. and i plan to make capstone also optional soon. Closing for now

**Comment by Shoreshen** [comment] 2021-12-28 06:39
I met the problem of offline installation. However, while searching the internet, I only found installation method in document with "./make.sh && ./make.sh install". I did that in root, but seems not working...

**Comment by trufae** [comment] 2021-12-28 16:03
there's no such make.sh in r2, so not sure what are you trying. The only step that requires internet to build r2 is covered by the preconfigure script. So if you do `./preconfigure`  you can unplug the cable and do `./configure;make;make install` without issues

**Comment by bannsec** [comment] 2021-12-28 18:21
This is good to know.

**Comment by trufae** [comment] 2021-12-28 18:31
There's a workflow in the CI to verify that

**Comment by Shoreshen** [comment] 2021-12-29 02:10
> there's no such make.sh in r2, so not sure what are you trying. The only step that requires internet to build r2 is covered by the preconfigure script. So if you do `./preconfigure` you can unplug the cable and do `./configure;make;make install` without issues

Hi, sorry for not clearly describing what I'm doing. Actually I was trying to install capstone, so that according to the previous comment if I did it "system widely", I would be able to install r2 without internet.

From the [link](http://s4.ce.sharif.edu/blog/2019/01/17/capstone/), I found the installation from source of capstone would be "./make.sh && ./make.sh install"....... So I did that in root but seems not work.

**Comment by Shoreshen** [comment] 2021-12-29 02:13
In addition, if there would be a place that I can manually download and place capstone......... So that r2 can directly acquire the package from there instead of internet

**Comment by Shoreshen** [comment] 2021-12-29 06:05
Well I put capstone under `radare2/shlr/` it seems work, but a new  link error has been popped........ 

One of the message says `relocation R_X86_64_32S against `.data' can not be used when making a shared object`

**Comment by trufae** [comment] 2021-12-30 15:11
That means you build capstone in the wrong way, and r2 cant link to it because its not relocatable. you have two options here:

* let r2 build capstone for you
* install capstone system wide and tell r2 to use it instead of building its own

Hopefully, soon, capstone5 will be out, and i can finally remove all the patches in r2, and enforce system-installation of capstone instead of shipping our own fork of it, but its been about 4 years waiting for this cs5 release

**Comment by trufae** [comment] 2021-12-30 15:11
(see ./configure --with-syscapstone)

**Comment by Shoreshen** [comment] 2022-01-05 03:24
Thanks a lot. I actually installed capstone following [here](http://s4.ce.sharif.edu/blog/2019/01/17/capstone/) under root by `./make.sh && ./make.sh install`. Furthermore I configured r2 with `./configure --with-syscapstone`

However, installing r2 will still reporting the error of offline due to r2 trying to download capstone.........

**Comment by radare** [comment] 2022-01-05 03:36
Uhm thanks for the details. Ill check and fix as soon as i can reach my laptop

**Comment by Shoreshen** [comment] 2022-01-05 05:47
Thanks a lot!!!!

**Comment by trufae** [comment] 2022-01-24 13:13
ill close when i add a CI task for this

**Comment by trufae** [comment] 2022-01-28 15:44
Should be good now!

**Closed by trufae** 2022-01-28 15:44 UTC
Labels: buildsystem
