### ISSUE TITLE
Support dotnet bin parsing

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#15249] opened 2019-10-11 11:19 UTC
https://github.com/VirusTotal/yara/blob/master/libyara/modules/dotnet.c

Reuse this to do the .net bin plugin

**Comment by XVilka** [comment] 2019-10-12 04:08
Duplicate of https://github.com/radareorg/radare2/issues/921 and https://github.com/radareorg/radare2/issues/662

**Comment by Maijin** [comment] 2019-10-28 14:11
and link dead

**Closed by Maijin** 2019-10-28 14:11 UTC
