### ISSUE TITLE
Failing debug tests on Fedora 31

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#15663] opened 2019-12-17 12:00 UTC
Failing debug tests on Fedora 31

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 31 x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.1.0-git 25235 @ linux-x86-64 git.4.0.0-235-g982be5049
commit: 982be504999364c966d339c4c29f20da80128e14 build: 2019-12-17__12:49:58

```
[XX] db/archos/linux-x64/dbg_io 'dbg.write'  259
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -d -i /tmp/tmp-600822adYFCL8QCfn2 /bin/ls
s entry0
p8 2
wx 9090
p8 2
dk 9

-31ed
+f30f
 9090

EXPECT=<<RUN
f30f
9090
[**]     db/archos/linux-x64/dbg_io   OK 12642 BR  956 XX    1 FX   32
[XX] db/archos/linux-x64/dbg_maps 'dbg.maps.count'  241
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -d -i /tmp/tmp-600822oFeT63vyNcFX ../bins/elf/analysis/elf-nx
dm~?
dk 9

-7
+9

EXPECT=<<RUN
9
[XX] db/archos/linux-x64/dbg_maps 'dbg.maps.count/'  251
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -d -i /tmp/tmp-600822oZRLDSlWRkwa ../bins/elf/analysis/elf-nx
dm~?/
dk 9

-4
+6

EXPECT=<<RUN
6
[XX] db/archos/linux-x64/dbg_maps 'dbg.maps.count.after.map'  243
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -d -i /tmp/tmp-6008221XPT0xHa6IyK ../bins/elf/analysis/x86-helloworld-gcc
dm~?
db sym.imp.puts
dc~?
dm~?
dc

-7
+9
 0
-14
+16
 Hello world!

EXPECT=<<RUN
9
0
16
Hello world!
[**]   db/archos/linux-x64/dbg_maps   OK 12643 BR  962 XX    4 FX   32e'  6528
[**]     db/archos/linux-x64/dbg_oo   OK 12644 BR  964 XX    4 FX   32
[XX] db/archos/linux-x64/dbg_px0 'dbg.px0'  240
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -d -i /tmp/tmp-600822t482O1dP7m4y ../bins/elf/analysis/elf-nx
px0

-89e083ec0c50e8850b
+89e083ec0c50e8950c

EXPECT=<<RUN
89e083ec0c50e8950c

```

cc @ret2libc

**Comment by ret2libc** [comment] 2020-03-04 10:28
```
[XX] db/archos/linux-x64/dbg_io 'dbg.write'  259
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -d -i /tmp/tmp-600822adYFCL8QCfn2 /bin/ls
s entry0
p8 2
wx 9090
p8 2
dk 9

-31ed
+f30f
 9090
```

It is using /bin/ls... /bin/ls on Fedora 31 contains `f30f1efa       endbr64` as first instruction, so it is right. The problem is, why are we using /bin/ls for testing instead of one of our binaries in test/bins?

**Comment by XVilka** [comment] 2020-03-04 10:32
We shouldn't.

**Comment by ret2libc** [comment] 2020-03-05 14:16
This is not a bug anyway. I think debug tests are too reliant on the system being used, so you cannot easily test how many mappings there should be or things like that. It depends on the system, the library, the library versions, etc. For now, I think we should only run those in the radare2-travis container image.

We could fix tests, sure, but I still need to find a way to check whether a string is present, but not *how many times*.
For example, I want to test that `ld` has been mapped, but not how many mapping entries it has, because that depends on the ld version and the way it was compiled and dunno whatever else.

**Comment by radare** [comment] 2020-04-08 13:59
imho we should close this issue

**Comment by XVilka** [comment] 2020-04-10 04:10
Here it happens again:
```
[**]                            db/archos/linux-x64/dbg    12626 OK       928 BR        0 XX       21 FX
[XX] db/archos/linux-x64/dbg_px0 dbg.px0
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -d -Qc px0 ../bins/elf/analysis/elf-nx
-- stdout
--- .a  2020-04-10 12:08:13.022732089 +0800
+++ .b  2020-04-10 12:08:13.022732089 +0800
@@ -1 +1 @@
-89e083ec0c50e8850b
+89e083ec0c50e8950c


-- stderr
Process with PID 458631 started...
= attach 458631 458631
bin.baddr 0x08048000
Using 0x8048000
Unknown DW_FORM 0x06
asm.bits 32
glibc.fc_offset = 0x00148
Warning: r_bin_file_hash: file exceeds bin.hashlimit

[**]                        db/archos/linux-x64/dbg_px0    12626 OK       928 BR        1 XX       21 FX
[**]                    db/archos/linux-x64/dbg_aaa_dcu    12629 OK       928 BR        1 XX       21 FX
[XX] db/archos/linux-x64/dbg_io dbg.write
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -d -Qc 's entry0
p8 2
wx 9090
p8 2
dk 9
' /bin/ls
-- stdout
--- .a  2020-04-10 12:08:14.288723677 +0800
+++ .b  2020-04-10 12:08:14.288723677 +0800
@@ -1,2 +1,2 @@
-31ed
+f30f
9090


-- stderr
Process with PID 458664 started...
= attach 458664 458664
bin.baddr 0x563ba9614000
Using 0x563ba9614000
asm.bits 64
Warning: r_bin_file_hash: file exceeds bin.hashlimit

[**]                         db/archos/linux-x64/dbg_io    12637 OK       928 BR        2 XX       21 FX
[**]                       db/archos/linux-x64/dbg_aslr    12638 OK       928 BR        2 XX       21 FX
[**]                       db/archos/linux-x64/dbg_cont    12639 OK       928 BR        2 XX       21 FX
[**]                       db/archos/linux-x64/bug_6678    12641 OK       928 BR        2 XX       21 FX
[**]                       db/archos/linux-x64/dbg_bps2    12645 OK       929 BR        2 XX       21 FX
[**]                        db/archos/linux-x64/dbg_bps    12658 OK       929 BR        2 XX       21 FX
[**]                     db/archos/linux-x64/dbg_cmdbps    12671 OK       930 BR        2 XX       21 FX
[**]                        db/archos/linux-x64/dbg_fds    12673 OK       931 BR        2 XX       21 FX
[**]                       db/archos/linux-x64/dbg_step    12675 OK       931 BR        2 XX       21 FX
[XX] db/archos/linux-x64/dbg_maps dbg.maps.count.after.map
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -d -Qc 'dm~?
db sym.imp.puts
dc~?
dm~?
dc
' ../bins/elf/analysis/x86-helloworld-gcc
-- stdout
--- .a  2020-04-10 12:08:18.144698053 +0800
+++ .b  2020-04-10 12:08:18.144698053 +0800
@@ -1,4 +1,4 @@
-7
+9
0
-14
+17
Hello world!


-- stderr
Process with PID 458907 started...
= attach 458907 458907
bin.baddr 0x08048000
Using 0x8048000
asm.bits 32
glibc.fc_offset = 0x00148
Warning: r_bin_file_hash: file exceeds bin.hashlimit
hit breakpoint at: 80482d0

[XX] db/archos/linux-x64/dbg_maps dbg.maps.count
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -d -Qc 'dm~?
dk 9
' ../bins/elf/analysis/elf-nx
-- stdout
--- .a  2020-04-10 12:08:18.425696186 +0800
+++ .b  2020-04-10 12:08:18.425696186 +0800
@@ -1 +1 @@
-7
+9


-- stderr
Process with PID 458937 started...
= attach 458937 458937
bin.baddr 0x08048000
Using 0x8048000
Unknown DW_FORM 0x06
asm.bits 32
glibc.fc_offset = 0x00148
Warning: r_bin_file_hash: file exceeds bin.hashlimit

[XX] db/archos/linux-x64/dbg_maps dbg.maps.count/
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -d -Qc 'dm~?/
dk 9
' ../bins/elf/analysis/elf-nx
-- stdout
--- .a  2020-04-10 12:08:18.731694152 +0800
+++ .b  2020-04-10 12:08:18.731694152 +0800
@@ -1 +1 @@
-4
+6


-- stderr
Process with PID 458961 started...
= attach 458961 458961
bin.baddr 0x08048000
Using 0x8048000
Unknown DW_FORM 0x06
asm.bits 32
glibc.fc_offset = 0x00148
Warning: r_bin_file_hash: file exceeds bin.hashlimit

[**]                         db/archos/linux-x64/dbg_dL    12677 OK       934 BR        5 XX       21 FX
```

**Comment by ret2libc** [comment] 2020-04-10 06:58
Yes but I don't think it's a bug. It is just different system

**Comment by ret2libc** [comment] 2020-04-22 12:54
I would close this bug. I don't think the tests or r2 are broken, it's just that we don't have a way to tests with "regex", which is something @thestr4ng3r mentioned. That would be useful here as well. Can we close this?

**Comment by ret2libc** [comment] 2020-07-17 10:06
As said, I'm closing this. There is also another bug, at least, about "broken" tests on debian system, etc. These are not really broken, but we should add support for tests with regex or something like that. We can't expect to have the same debug tests on all systems, because they are different systems.

**Closed by ret2libc** 2020-07-17 10:06 UTC
Labels: DWARF, RDebug, test-required
