### ISSUE TITLE
loading big elf hangs

### ISSUE THREAD

**Issue by yuzhichang** [radareorg/radare2#21507] opened 2023-03-22 10:20 UTC
## Environment

radare2 5.8.5 30090 @ linux-x86-64 git.5.8.4-21-g7dd19cff68
commit: 7dd19cff683be93c7b386a43737c3b473f74dac8 build: 2023-03-22__14:27:50
Linux x86_64

## Description

I try to analyze functions address of grpc so inside whl such as [this one](https://pypi.tuna.tsinghua.edu.cn/packages/4b/63/d6075e4894a413cb7c33e770b16b71d4edb2a53d98260dd9ae8e824046f7/grpcio-1.41.1-cp36-cp36m-manylinux2010_x86_64.whl). whl is just a zip file, can be extracted with `unzip` command. The so inside new versions of grpc x86_64 whl is stripped. 
I managed to build a not-stripped one from the exactly same revision source code. However my built after stripping differs with the official one.

Loading the stripped one(8.6MB) end in seconds.
Loing the not-stripped one(158MB) hangs:
```
$ r2 1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so
```

The loading costs one cpu, and more and more RES,  and cannot end in a hour. `perf` indicates it's busy on `memmove` and `memset`.
```
+   99.95%     0.00%  r2       libc.so.6             [.] __libc_start_call_main                                                                                           ◆
+   99.95%     0.00%  r2       radare2               [.] main                                                                                                             ▒
+   99.95%     0.00%  r2       libr_main.so          [.] r_main_radare2                                                                                                   ▒
+   99.95%     0.00%  r2       libr_main.so          [.] binload                                                                                                          ▒
+   99.95%     0.00%  r2       libr_core.so          [.] r_core_bin_load                                                                                                  ▒
+   99.95%     0.00%  r2       libr_core.so          [.] r_core_file_do_load_for_io_plugin                                                                                ▒
+   99.95%     0.00%  r2       libr_core.so          [.] r_core_bin_set_env                                                                                               ▒
+   99.95%     0.00%  r2       libr_core.so          [.] r_core_bin_info                                                                                                  ▒
+   99.95%     0.00%  r2       libr_core.so          [.] bin_dwarf                                                                                                        ▒
+   99.95%     0.00%  r2       libr_bin.so           [.] r_bin_dwarf_parse_info                                                                                           ▒
+   99.95%     0.00%  r2       libr_bin.so           [.] parse_info_raw                                                                                                   ▒
+   99.94%     0.01%  r2       libr_bin.so           [.] parse_comp_unit                                                                                                  ▒
+   99.92%     0.03%  r2       libr_bin.so           [.] parse_die                                                                                                        ▒
+   99.78%     0.08%  r2       libr_bin.so           [.] parse_attr_value                                                                                                 ▒
+   55.19%     0.03%  r2       libr_bin.so           [.] get_section_bytes                                                                                                ▒
+   55.10%     0.01%  r2       libr_util.so          [.] r_buf_read_at                                                                                                    ▒
+   54.98%     0.01%  r2       libr_util.so          [.] r_buf_read                                                                                                       ▒
+   54.97%     0.00%  r2       libr_util.so          [.] buf_io_read                                                                                                      ▒
+   54.97%     0.00%  r2       libr_util.so          [.] buf_read                                                                                                         ▒
+   54.94%     0.00%  r2       libr_io.so            [.] r_io_fd_read                                                                                                     ▒
+   54.94%     0.03%  r2       libr_io.so            [.] r_io_desc_read                                                                                                   ▒
+   54.92%     0.02%  r2       libr_io.so            [.] r_io_plugin_read                                                                                                 ▒
+   54.91%     0.00%  r2       libr_io.so            [.] __read                                                                                                           ▒
+   54.89%     0.00%  r2       libr_io.so            [.] r_io_def_mmap_read                                                                                               ▒
+   54.85%    54.84%  r2       libc.so.6             [.] __memmove_avx_unaligned_erms                                                                                     ▒
+   44.47%    44.47%  r2       libc.so.6             [.] __memset_avx2_unaligned_erms                                                                                     ▒
     0.14%     0.02%  r2       libr_util.so          [.] r_buf_seek                                                                                                       ▒
     0.13%     0.03%  r2       libr_util.so          [.] buf_seek                                                                                                         ▒
     0.10%     0.03%  r2       libr_util.so          [.] buf_io_seek                                                                                                      ▒
     0.07%     0.00%  r2       libr_io.so            [.] r_io_fd_seek                                                                                                     ▒
     0.06%     0.00%  r2       libr_util.so          [.] sdb_set_owned                                                                                                    ▒
     0.05%     0.05%  r2       libr_bin.so           [.] getsection                                                                                                       ▒
     0.04%     0.00%  r2       libr_util.so          [.] sdb_set_internal                                                                                                 ▒
     0.03%     0.02%  r2       libr_io.so            [.] r_io_desc_seek                                                                                                   ▒
     0.03%     0.01%  r2       libr_io.so            [.] r_io_desc_get                                                                                                    ▒
     0.03%     0.02%  r2       libr_util.so          [.] ht_pp_find_kv                                                                                                    ▒
     0.03%     0.00%  r2       libr_util.so          [.] sdb_ht_find_kvp                                                                                                  ▒
```

**Comment by trufae** [comment] 2023-03-22 17:20
pancake@pnuc:~/Downloads/grpc/_cython$ r2 cygrpc.cpython-36m-x86_64-linux-gnu.so 

thats the only file i found and itts 7MB and it tskes half a second to load :? where's that unstripped binary for testing? i assume you can -e bin.dwarf=false for faster loading but thats just a blind guess

**Comment by yuzhichang** [comment] 2023-03-23 01:43
@trufae `-e bin.dwarf=false` doesn't work for me.
```
zhichyu@leno:~/grpc_whl/notstripped$ r2 -e bin.dwarf=false 1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so
ERROR: variable 'bin.dwarf' not found
```
The unstripped binary is too big to paste here. I sent it to your mailbox(pancake@nowsecure.com).

**Comment by trufae** [comment] 2023-03-23 06:16
-e bin.dbginfo=false sorry

**Comment by yuzhichang** [comment] 2023-03-23 06:42
`-e bin.dbginfo=false` make loading faster but I cannot generate zignatures.

```
zhichyu@leno:~/grpc_whl/notstripped$ r2 -e bin.dbginfo=false 1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so
WARN: run r2 with -e bin.cache=true to fix relocations in disassembly
 -- Remember to maintain your ~/.radare_history
[0x00075100]> zg
INFO: generated zignatures: 0
[0x00075100]> zg c grpc.z
INFO: generated zignatures: 0
[0x00075100]> zaF
INFO: generated zignatures: 0
[0x00075100]> quit
```

**Comment by trufae** [comment] 2023-03-23 08:52
yep its the dwarf info that takes a while to be parsed and loaded. i will focus on optimizing this before the 5.9.x release. so i really appreciate your binary for testing.

```
0$ time r2 -qcq -e bin.dbginfo=false 1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so
WARN: run r2 with -e bin.cache=true to fix relocations in disassembly
r2 -qcq -e bin.dbginfo=false 1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so  0.79s user 0.05s system 99% cpu 0.843 total
0$
```

About the zignatures, they need the functions to be analyzed in order to work, thats why its showing 0 zignatures. 

```
[0x00075100]> aflc
19984
[0x00075100]> zg
INFO: generated zignatures: 19984
[0x00075100]>
```

**Comment by yuzhichang** [comment] 2023-03-24 06:52
Possible optimization:
-  Use better malloc implementation  such as [jemalloc](https://github.com/jemalloc/jemalloc).
- Use `ifdef __BIG_ENDIAN` and `ntoh` if possible

**Comment by trufae** [comment] 2023-03-28 04:07
Loading times drastically reduced in here https://github.com/radareorg/radare2/pull/21529

**Comment by trufae** [comment] 2023-03-28 05:00
Merged. It can be optimized even more but i think current situation is much better and its a reasonable amount of time (20s for a 160MB dwarf file). I think i can lower this time to 5s. But i would leave remaining optimizations for my future self as long as i have more important tasks to do.

thanks for reporting and submitting a reproducer. This change also helped to reduce ci time in 1'

**Closed by trufae** 2023-03-28 05:00 UTC

**Comment by yuzhichang** [comment] 2023-03-28 13:06
The optimization works on my workstation, but not work on my laptop.

The `perf record` of r2 on my laptop:
```
Samples: 111K of event 'cycles', Event count (approx.): 109351255003
  Children      Self  Command  Shared Object         Symbol
-   99.94%     0.00%  r2       libr_bin.so           [.] parse_comp_unit                                                                                                  ◆
   - 99.93% parse_comp_unit                                                                                                                                               ▒
      - 99.90% parse_die                                                                                                                                                  ▒
         - 99.77% parse_attr_value                                                                                                                                        ▒
            - 54.92% get_section_bytes                                                                                                                                    ▒
               - 54.73% r_buf_read_at                                                                                                                                     ▒
                  - 54.60% r_buf_read                                                                                                                                     ▒
                     - 54.59% buf_read                                                                                                                                    ▒
                        - 54.57% buf_io_read                                                                                                                              ▒
                           - 54.55% r_io_fd_read                                                                                                                          ▒
                              - 54.54% r_io_desc_read                                                                                                                     ▒
                                 - 54.53% r_io_plugin_read                                                                                                                ▒
                                    - __read                                                                                                                              ▒
                                       - 54.51% r_io_def_mmap_read                                                                                                        ▒
                                          - 54.50% r_buf_read_at                                                                                                          ▒
                                             - 54.50% r_buf_read                                                                                                          ▒
                                                - buf_read                                                                                                                ▒
                                                     54.46% __memmove_avx_unaligned_erms                                                                                  ▒
              44.75% __memset_avx2_unaligned_erms                                                                                                                         ▒
+   99.94%     0.00%  r2       libc.so.6             [.] __libc_start_call_main                                                                                           ▒
+   99.94%     0.00%  r2       radare2               [.] main                                                                                                             ▒
+   99.94%     0.00%  r2       libr_main.so          [.] r_main_radare2                                                                                                   ▒
+   99.94%     0.00%  r2       libr_main.so          [.] binload                                                                                                          ▒
+   99.94%     0.00%  r2       libr_core.so          [.] r_core_bin_load                                                                                                  ▒
+   99.94%     0.00%  r2       libr_core.so          [.] r_core_file_do_load_for_io_plugin                                                                                ▒
+   99.94%     0.00%  r2       libr_core.so          [.] r_core_bin_set_env                                                                                               ▒
+   99.94%     0.00%  r2       libr_core.so          [.] r_core_bin_info                                                                                                  ▒
+   99.94%     0.00%  r2       libr_core.so          [.] bin_dwarf                                                                                                        ▒
+   99.94%     0.00%  r2       libr_bin.so           [.] r_bin_dwarf_parse_info                                                                                           ▒
+   99.94%     0.00%  r2       libr_bin.so           [.] parse_info_raw                                                                                                   ▒
+   99.90%     0.01%  r2       libr_bin.so           [.] parse_die                                                                                                        ▒
+   99.78%     0.03%  r2       libr_bin.so           [.] parse_attr_value                                                                                                 ▒
+   54.93%     0.02%  r2       libr_bin.so           [.] get_section_bytes                                                                                                ▒
+   54.74%     0.01%  r2       libr_util.so          [.] r_buf_read_at                                                                                                    ▒
+   54.68%     0.00%  r2       libr_util.so          [.] r_buf_read                                                                                                       ▒
+   54.60%     0.02%  r2       libr_util.so          [.] buf_read                                                                                                        
 ```

**Comment by trufae** [comment] 2023-03-29 14:33
I guess your workstation is more powerful than your laptop or you didnt updated r2 in the laptop :? i know several more ways to optimize this code. Because its weird that your perf log is not showing the new `get_section_string` function :?

**Comment by trufae** [comment] 2023-03-29 14:44
i have implemented the same optimization for dwarf5 files https://github.com/radareorg/radare2/pull/21540

**Comment by yuzhichang** [comment] 2023-03-29 14:59
@trufae Sorry, It's my mistake to not reinstall r2. Thank again!
