### ISSUE TITLE
`rabin2 -S %R2_FILE% |grep prixfixe. |wc -l |awk "{print $1}"` broken on Windows clang-cl

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16560] opened 2020-04-13 02:33 UTC
clang-cl build on Windows: https://ci.appveyor.com/project/radareorg/radare2/builds/32131658/job/5n88sgw6aw9hswbe
```
[XX] C:\projects\radare2\test\new\db\tools\rabin2 rabin2 -S, -SS, -rS and -rSS file elf
ANSICON=1 R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rabin2 -S %R2_FILE%|wc -l|awk "{print $1}"
!rabin2 -SS %R2_FILE%|wc -l|awk "{print $1}"
!env RABIN2_PREFIX=prixfixe rabin2 -S %R2_FILE% |grep prixfixe. |wc -l |awk "{print $1}"
!env RABIN2_PREFIX=prixfixe rabin2 -SS %R2_FILE% |grep prixfixe. |wc -l |awk "{print $1}"
' ../bins/elf/analysis/x86-helloworld-gcc
-- stdout
- 35
- 14
- 30
- 9
- 
+ 35
+ 14
+ 30
+ 0
+ 
-- stderr
env: rabin2: No such file or directory
[**]       C:\projects\radare2\test\new\db\tools\rabin2      350 OK        19 BR        1 XX        5 FX
[**]           C:\projects\radare2\test\new\db\tools\r2      351 OK        19 BR        1 XX        5 FX
[**]
```

**Comment by radare** [comment] 2020-04-13 05:04
Dupe of https://github.com/radareorg/radare2/issues/16452

**Closed by radare** 2020-04-13 05:04 UTC
Labels: Windows

**Comment by radare** [comment] 2020-04-13 08:40
9 vs 0
