### ISSUE TITLE
Segfault on r_sign_addto_item when creating a signature from a libc

### ISSUE THREAD

**Issue by thotypous** [radareorg/radare2#17528] opened 2020-08-26 18:53 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux amd64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARM
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 25097 @ linux-x86-64 git.4.4.0-564-gc4a6d0e537 commit: c4a6d0e537e121af25b423f3bf8f45a26b84cec8 build: 2020-08-18__02:16:02

### Expected behavior

The signature file would be created

### Actual behavior

Segmentation fault

### Steps to reproduce the behavior 
 * Input file: [libc.zip](https://github.com/radareorg/radare2/files/5131708/libc.zip)
 * Run: `rasign2 -a -o anything.sdb libc.so.6`

### Additional Logs, screenshots, source-code,  configuration dump, ...

```
                Stack trace of thread 340455:
                #0  0x00007fd41b15e40f r_sign_addto_item (libr_anal.so.4.6.0-git + 0xb140f)
                #1  0x00007fd41b622cac n/a (libr_core.so.4.6.0-git + 0xbdcac)
                #2  0x00007fd41b6248a1 n/a (libr_core.so.4.6.0-git + 0xbf8a1)
                #3  0x00007fd41b68b3e7 r_cmd_call (libr_core.so.4.6.0-git + 0x1263e7)
                #4  0x00007fd41b6875dc n/a (libr_core.so.4.6.0-git + 0x1225dc)
                #5  0x00007fd41b6896c8 n/a (libr_core.so.4.6.0-git + 0x1246c8)
                #6  0x00007fd41b685780 r_core_cmd (libr_core.so.4.6.0-git + 0x120780)
                #7  0x00007fd41be78401 r_main_rasign2 (libr_main.so.4.6.0-git + 0x1f401)
                #8  0x00007fd41becd152 __libc_start_main (libc.so.6 + 0x28152)
                #9  0x000055590b22906e n/a (rasign2 + 0xc06e)
```

bemodtwz has noted on IRC that `fcn.00054758` has an empty list of basic blocks.

**Comment by swoops** [comment] 2020-08-26 19:04
This is a NULL pointer de-reference here: https://github.com/radareorg/radare2/blob/master/libr/anal/sign.c#L833

I *think* the root cause is function `fcn.00054758` has an empty list of basic blocks:
```
(gdb) p *fcn->bbs
$4 = {head = 0x0, tail = 0x0, free = 0x0, length = 0, sorted = true}
```
I don't think any function should have an empty list of basic blocks. The sign.c code would still benefit from a check here to prevent crashes, but I think the real bug is in the analysis of that function.

**Comment by thotypous** [comment] 2020-09-04 15:41
Radare2 does not crash anymore, although there is still an assertion failure.

Tested with:

```
radare2 4.6.0-git 24962 @ linux-x86-64 git.4.4.0-639-g052f97dd24
commit: 052f97dd2451308fe85e35c9d0330e3ac0a3287b build: 2020-09-04__11:26:40
```

Output:

```
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for vtables
[x] Finding xrefs in noncode section with anal.in=io.maps
[x] Analyze value pointers (aav)
[x] Value from 0x00000000 to 0x000e04e0 (aav)
[x] 0x00000000-0x000e04e0 in 0x0-0xe04e0 (aav)
[x] Emulate functions to find computed references (aaef)
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
WARNING: r_sign_fcn_bytes: assertion 'a && fcn && fcn->bbs && fcn->bbs->head' failed (line 818)
generated zignatures: 2455
```

Feel free to close this bug if you are already tracking the empty basic blocks problem in another issue.

**Comment by trufae** [comment] 2021-04-16 15:09
Closing as long as its fixed

**Closed by trufae** 2021-04-16 15:09 UTC
Labels: zignatures
