### ISSUE TITLE
[Status] filter word: Segmentation fault in free()

### ISSUE THREAD

**Issue by kyx0r** [radareorg/radare2#18858] opened 2021-06-23 02:30 UTC
## Environment

```sh
# copypaste this script into your shell and replace it with the output
date
Tue Jun 22 22:23:13 UTC 2021
r2 -v
radare2 5.3.1 0 @ linux-x86-64 git.5.3.1
commit: 5.3.1 build: 2021-06-22__22:11:23
uname -ms
Linux 5.13.0-rc5 #23 SMP Sat Jun 12 16:30:34 UTC 2021 x86_64 GNU/Linux
ldd r2
        /lib/ld-musl-x86_64.so.1 (0x7f5eb6d69000)
        libr_cons.so => /lib/libr_cons.so (0x7f5eb6d38000)
        libr_config.so => /lib/libr_config.so (0x7f5eb6d2f000)
        libr_io.so => /lib/libr_io.so (0x7f5eb6cbd000)
        libr_util.so => /lib/libr_util.so (0x7f5eb6b99000)
        libr_flag.so => /lib/libr_flag.so (0x7f5eb6b8e000)
        libr_asm.so => /lib/libr_asm.so (0x7f5eb5fa3000)
        libr_core.so => /lib/libr_core.so (0x7f5eb5d87000)
        libr_debug.so => /lib/libr_debug.so (0x7f5eb5d57000)
        libr_hash.so => /lib/libr_hash.so (0x7f5eb5d4b000)
        libr_bin.so => /lib/libr_bin.so (0x7f5eb5bc3000)
        libr_lang.so => /lib/libr_lang.so (0x7f5eb5bb6000)
        libr_anal.so => /lib/libr_anal.so (0x7f5eb5272000)
        libr_parse.so => /lib/libr_parse.so (0x7f5eb5206000)
        libr_bp.so => /lib/libr_bp.so (0x7f5eb51ff000)
        libr_egg.so => /lib/libr_egg.so (0x7f5eb51ec000)
        libr_reg.so => /lib/libr_reg.so (0x7f5eb51df000)
        libr_search.so => /lib/libr_search.so (0x7f5eb51d6000)
        libr_syscall.so => /lib/libr_syscall.so (0x7f5eb51cf000)
        libr_socket.so => /lib/libr_socket.so (0x7f5eb51be000)
        libr_fs.so => /lib/libr_fs.so (0x7f5eb5184000)
        libr_magic.so => /lib/libr_magic.so (0x7f5eb5175000)
        libr_crypto.so => /lib/libr_crypto.so (0x7f5eb5152000)
        libr_main.so => /lib/libr_main.so (0x7f5eb5127000)
        libc.so => /lib/ld-musl-x86_64.so.1 (0x7f5eb6d69000)

```

## Description
Segfault in free()

Complete stackstace:

```
Program received signal SIGSEGV, Segmentation fault.
-----------------------------------------------------------------------------------------------------------------------[regs]
  RAX: 0x00007FE72B90248C  RBX: 0x00007FE72BD5D030  RCX: 0x0000000000000010  RDX: 0x0000000000000005  o d I t s z a P c
  RSI: 0x000000000000000C  RDI: 0x00007FE72B902480  RBP: 0x000056315A13D298  RSP: 0x00007FFC9134FEA0  RIP: 0x00007FE72DA26868
  R8 : 0x0000000066646764  R9 : 0x00007FE72B902480  R10: 0x000000000000001D  R11: 0x0000000000000246  R12: 0x0000000000000010
  R13: 0x00007FE72B902480  R14: 0x0000000000000000  R15: 0x0000000000000000
  CS: 0033  DS: 0000  ES: 0000  FS: 0000  GS: 0000  SS: 002B
-----------------------------------------------------------------------------------------------------------------------[code]
=> 0x7fe72da26868 <__libc_free+408>:    hlt
   0x7fe72da26869 <__libc_free+409>:    jmp    0x7fe72da26762 <__libc_free+146>
   0x7fe72da2686e <__libc_free+414>:    xchg   ax,ax
   0x7fe72da26870 <__libc_free+416>:    movzx  eax,BYTE PTR [rip+0x8806c]        # 0x7fe72daae8e3 <__libc+3>
   0x7fe72da26877 <__libc_free+423>:    lea    r13,[rip+0x8a75e]        # 0x7fe72dab0fdc <__malloc_lock>
   0x7fe72da2687e <__libc_free+430>:    test   al,al
   0x7fe72da26880 <__libc_free+432>:    jne    0x7fe72da268c0 <__libc_free+496>
   0x7fe72da26882 <__libc_free+434>:    mov    rdi,rbp
   0x7fe72da26885 <__libc_free+437>:    mov    esi,r12d
   0x7fe72da26888 <__libc_free+440>:    call   0x7fe72da262e0 <nontrivial_free>
   0x7fe72da2688d <__libc_free+445>:    mov    rdi,r13
   0x7fe72da26890 <__libc_free+448>:    mov    rbp,rdx
   0x7fe72da26893 <__libc_free+451>:    mov    r12,rax
   0x7fe72da26896 <__libc_free+454>:    call   0x7fe72da66040 <__unlock>
   0x7fe72da2689b <__libc_free+459>:    test   rbp,rbp
   0x7fe72da2689e <__libc_free+462>:    je     0x7fe72da267fd <__libc_free+301>
   0x7fe72da268a4 <__libc_free+468>:    add    rsp,0x8
   0x7fe72da268a8 <__libc_free+472>:    mov    rsi,rbp
   0x7fe72da268ab <__libc_free+475>:    mov    rdi,r12
   0x7fe72da268ae <__libc_free+478>:    pop    rbx
   0x7fe72da268af <__libc_free+479>:    pop    rbp
   0x7fe72da268b0 <__libc_free+480>:    pop    r12
-----------------------------------------------------------------------------------------------------------------------------
__libc_free (p=p@entry=0x7fe72b902480) at src/malloc/mallocng/free.c:110
110     src/malloc/mallocng/free.c: No such file or directory.
gdb$ where
#0  __libc_free (p=p@entry=0x7fe72b902480) at src/malloc/mallocng/free.c:110
#1  0x00007fe72da25c35 in free (p=p@entry=0x7fe72b902480) at src/malloc/free.c:5
#2  0x00007fe72cb95810 in __handle_cmd_str_cache (core=core@entry=0x7fe72bd5d030, panel=panel@entry=0x7fe72b8b2430, force_cache=force_cache@entry=0x0) at panels.c:889
#3  0x00007fe72cb95c2a in __print_disassembly_cb (user=0x7fe72bd5d030, p=0x7fe72b8b2430) at panels.c:4444
#4  0x00007fe72cb95f20 in __default_panel_print (panel=0x7fe72b8b2430, core=0x7fe72bd5d030) at panels.c:5714
#5  __panel_print (core=core@entry=0x7fe72bd5d030, can=can@entry=0x7fe72bc179f0, panel=0x7fe72b8b2430, color=color@entry=0x1) at panels.c:5732
#6  0x00007fe72cb964b9 in __panels_refresh (core=0x7fe72bd5d030) at panels.c:5776
#7  0x00007fe72cb9c753 in __panels_process (panels=0x7fe72bc86910, core=0x7fe72bd5d030) at panels.c:6362
#8  r_core_panels_root (core=core@entry=0x7fe72bd5d030, panels_root=0x7fe72ba37db0) at panels.c:7061
#9  0x00007fe72cabedd1 in cmd_panels (input=0x7fe72b9ff681 "", data=0x7fe72bd5d030) at cmd.c:2456
#10 cmd_panels (data=0x7fe72bd5d030, input=0x7fe72b9ff681 "") at cmd.c:2418
#11 0x00007fe72cb55fb1 in r_cmd_call (cmd=0x7fe72bcf2010, input=input@entry=0x7fe72b9ff680 "v") at cmd_api.c:354
#12 0x00007fe72cac7b2f in r_core_cmd_subst_i (tmpseek=<optimized out>, colon=0x0, cmd=<optimized out>, core=0x7fe72bd5d030) at cmd.c:4355
#13 r_core_cmd_subst (core=core@entry=0x7fe72bd5d030, cmd=<optimized out>, cmd@entry=0x7fe72b9430f0 "v") at cmd.c:3252
#14 0x00007fe72cac974f in run_cmd_depth (cmd=0x7fe72b9430f0 "v", core=0x7fe72bd5d030) at cmd.c:5240
#15 r_core_cmd (core=core@entry=0x7fe72bd5d030, cstr=<optimized out>, log=log@entry=0x1) at cmd.c:5324
#16 0x00007fe72ca96ecb in r_core_prompt_exec (r=r@entry=0x7fe72bd5d030) at core.c:3235
#17 0x00007fe72ca975b8 in r_core_prompt_loop (r=r@entry=0x7fe72bd5d030) at core.c:3087
#18 0x00007fe72bdd8930 in r_main_radare2 (argc=<optimized out>, argv=<optimized out>) at radare2.c:1467
#19 0x00007fe72da1ab8a in libc_start_main_stage2 (main=0x56315a11e0f0 <main>, argc=0x3, argv=0x7ffc913505a8) at src/env/__libc_start_main.c:94
#20 0x000056315a11e2db in _start ()
```

## Test
Start any program using -d for debugger.
Enter visual mode v
Press f, "[Status] filter word:" will pop up. Type anything you want always segfault.

**Comment by trufae** [comment] 2021-06-23 10:57
thanks for reporting! the issue is addressed in git, and will be included in r2-5.4

**Closed** 2021-06-23 10:56 UTC
