### ISSUE TITLE
Single click interpreted as two clicks in visual mode

### ISSUE THREAD

**Issue by Vyber90** [radareorg/radare2#17943] opened 2020-11-19 19:43 UTC
# Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | WSL Kali x86_64, Windows 20H2
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 25277 @ linux-x86-64 git.4.4.0-941-g3ae296254
commit: 3ae296254b035cc01872d09bdf7e40258b95e512 build: 2020-11-19__18:43:32

### Expected behavior
Only detecting the mouse pressed event in order to not change the sought address when releasing the button
### Actual behavior
Unless you keep the mouse button pressed and release it far from an address, it will jump to the address under the mouse at releasing time
### Steps to reproduce the behavior 
[0x00000000]> v
*press and release the left mouse button on an address that is not the first one in the list. The program will jump to both the intended address and then the address under the mouse at the time of releasing the button after changing the focused address*.

**Comment by trufae** [comment] 2020-11-21 15:20
Theres no such thing as click or doubleclick in the terminal. If you want to select text press :

**Comment by Vyber90** [comment] 2020-11-21 16:04
then, why does the program react to my mouse button events when in visual mode?

**Comment by trufae** [comment] 2020-11-21 16:55
Because you can intersct with the whole panels and visual mode using the mouse, but you can click. No doubleclick

**Comment by Vyber90** [comment] 2020-11-21 19:02
The thing is, in my issue I reference double-clicking not as an independent event, but as a single-click happening twice. Changing the title in the issue.

**Comment by trufae** [comment] 2020-11-21 21:02
Which terminal and operating system are you using? So.. if i understand it correctly when you click once, you experience a double click?

**Comment by Vyber90** [comment] 2020-11-21 21:21
I am using the Linux subsystem for Windows in the standard (and downloadable by windows store) kali linux terminal for this OS.
And yes, that is esentially the problem, but you have a more descriptive text in the issue body itself.

**Comment by trufae** [comment] 2020-11-22 00:03
Ook, thanks for the details! Seems like it must be an specific issue to the windows subsystem, the ansi controls can probably be tweaked to work too.

Is this double click happening because of mousedown and mouseup events? Maybe this can be filtered out but must be tested on real linux to confirm no regressions. Would you like to try to fix it?

**Comment by Vyber90** [comment] 2020-11-22 08:38
Yes, they are. Mousedown and mouseup events are both interpreted as mousedowns.
About me fixing the issue, this would be my first contribution to an open-source program. Are you sure you want me to do it?

**Comment by trufae** [comment] 2020-11-22 18:07
There's always a first time :) i can't repro the issue. last windows machine i had was running windows 95, so im quite out of context to repro the issue. maybe any windows developer can have a look at it

**Comment by karliss** [comment] 2020-11-22 18:14
I don't think windows is necessary. I was able to repeat it on Linux using `4.6.0-git 27567 @ linux-x86-64 git.4.4.0-908-g91aebb649`

**Comment by trufae** [comment] 2020-11-22 18:20
correct. i can confirm the issue happens on linux. works fine on mac

**Comment by Vyber90** [comment] 2020-11-22 18:40
then, will I be assigned to solve this problem (I will try my best, but I don't promise anything)

**Comment by trufae** [comment] 2020-11-30 19:30
only people with commit rights can be assigned. i have assigne dmyself and i have -4 spare time to check 3rd party issues right now. but i'll send the fix if i find some spare time, did you investigated the issue?

**Comment by Vyber90** [comment] 2020-11-30 21:33
Okay, no problem.
And, to be honest, I do not even understand the filesystem for this repository (no src directory, for example) although I spent hours reading the CONTRIBUTING and DEVELOPERS files, so nope, I have not investigated anything at all though I tried my best.

**Comment by trufae** [comment] 2020-12-06 18:32
Not all projects have a `src` directory , actually many GNU projects don't even use directories. That's up tot he developer taste. Actually the only tool you need to use is usually `grep`. finding which files are related to the stuff you want to fix. In short:

* libr : contains all the libraries of r2
* binr: contain the programs that use those libraries
* shlr: 3rd party code or code shared in libr

what you need to look at is in `libr/cons`. I hope to get this fixed when my life becomes less chaotic, but it's an important issue to be solved before doing any release. 

Thanks for pointing it out and trying!

**Comment by Vyber90** [comment] 2020-12-06 22:11
Roger that, and thank you for your help! I am researching into the bug as soon as possible in order to make a report as detailed and accurate as I possibly can. Where do I share it when I have it? in this thread?

**Comment by trufae** [comment] 2020-12-09 12:11
I fixed in https://github.com/radareorg/radare2/pull/18012, but i dont consider it a proper fix because its disabling the mouse up. btw the issue is only happening with VTE, in linux.xterm and macOS is working fine.

**Comment by Vyber90** [comment] 2020-12-09 12:22
I felt quite lost when investigating the issue, so I will see what you did in order to understand how the hell this works.
Btw, thank you for your help, appreciate it a lot!

**Closed** 2020-12-13 02:55 UTC
