### ISSUE TITLE
OS X unit test failure - test_space_event, Fail at line 105: and it should be equal to thirdspace ptr: expected 0x7ff7c75001a0, got 0x7ff7c7402990.

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#15146] opened 2019-09-29 04:48 UTC
```
test_space_basic OK
test_space_stack OK
test_space_event ERR
[XX] Fail at line 105: and it should be equal to thirdspace ptr: expected 0x7ff7c75001a0, got 0x7ff7c7402990.
test_sparse
test_r_buf_new_sparse OK
```

**Comment by Maijin** [comment] 2019-09-30 08:38
Reproduced locally

**Comment by Maijin** [comment] 2019-09-30 08:39
This is fixed in master looks like

**Closed** 2019-10-28 10:19 UTC
Labels: OS X
