### ISSUE TITLE
Build fails: whitespace in path

### ISSUE THREAD

**Issue by prenex** [radareorg/radare2#13081] opened 2019-02-13 14:26 UTC
Build does not work if there is a whitespace in the build path where the git repo is cloned to.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 32
git commit:c3339b8f819e871e67cd45fdf15436b7b31c370b  build:2019-02-13__15:00:31

### Expected behavior

sys/install.sh installs the system.

### Actual behavior

Neither sys/install.sh, nor sudo sys/install.sh finish properly. See below:

```
Final report:
 - R_CHECKS_LEVEL = 2
 - PREFIX = /usr
 - HAVE_LIB_GMP = 0
 - HAVE_OPENSSL = 0
 - HAVE_LIBUV = 0
 - USE_CAPSTONE = 0
 - HAVE_PTRACE = 1
 - USE_PTRACE_WRAP = 1
 - HAVE_FORK = 1
 - VERSION = 3.3.0-git
 - USE_LIB_ZIP = 0
 - USE_LIB_MAGIC = 0
 - USE_LIB_XXHASH = 0
 - DEBUGGER = 1
 - CC = gcc
 - USERCC = gcc
 - HAVE_ARC4RANDOM_UNIFORM = 0
 - HAVE_EXPLICIT_BZERO = 0
 - HAVE_EXPLICIT_MEMSET = 0
 - USEROSTYPE = gnulinux
 - LIBVERSION = 3.3.0-git
 - BUILD = i686-unknown-linux-gnu
 - HOST = i686-unknown-linux-gnu
 - TARGET = i686-unknown-linux-gnu
libr/config.mk:45: /media/prenex/Plan9(Outer: No such file or directory
libr/config.mk:45: Space)/radare2/libr/../global.mk: No such file or directory
libr/config.mk:46: /media/prenex/Plan9(Outer: No such file or directory
libr/config.mk:46: Space)/radare2/libr/../mk/gcc.mk: No such file or directory
make: *** No rule to make target 'Space)/radare2/libr/../mk/gcc.mk'.  Stop.
```

I cloned into a path that contains "Plan9(Outer Space)" in it and visibly that is the problem ;-).

Easy workaround: install into an other directory that has sane path without whitespaces.

### Steps to reproduce the behavior 

- Just clone radare in a directory that is on a path with whitespace
- sys/install.sh
- Build should fail like above

**Comment by radare** [comment] 2019-02-13 14:58
Use meson if you cant content your spaces

**Comment by radare** [comment] 2019-02-13 14:58
Its known issue and its already tracked by another issue

**Comment by prenex** [comment] 2019-02-13 15:56
It is not a big deal as I already changed to use a non-whitespace path, just wanted to document it. I did not find a similar open issue beforehand but if there is any just close this - or just close anyways as there is an easy workaround.

**Comment by radare** [comment] 2019-02-13 23:27
i have implemented this approach in this pr

https://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them

https://github.com/radare/radare2/pull/13091

i didnt tested it, and i bet it will be failing in other places, so its wip, would you like to help on solving this issue?

**Comment by trufae** [comment] 2020-12-26 11:29
I think the best way to try and fix this is by adding a GHA task for it. i'll work on that.

**Comment by trufae** [comment] 2021-01-13 15:20
I merged the rewritten CI scripts which basically proof the following:

- ACR can't build or install on paths with spaces, it's not a bug in ACR, but a bug in GNU MAKE. it's known issue and there are some hacks to workaround this limitation (make functions work on strings, not paths, so spaces must be nestedly escaped several times to work).
- Meson/ninja can build and install on paths with spaces. This is tested per-commit in the GHA now


thanks for reporting!

**Closed by trufae** 2021-01-13 15:20 UTC
Labels: buildsystem
