### ISSUE TITLE
./sys/install.sh to /usr/bin not /usr/local/bin (violation of FHS)

### ISSUE THREAD

**Issue by EvanCarroll** [radareorg/radare2#9240] opened 2018-01-25 17:07 UTC
### Work environment

Using Linux, after I run `./configure` I get

```
Final report:
 - PREFIX = /usr/local
 - HAVE_LIB_GMP = 0
 - HAVE_OPENSSL = 0
 - USE_CAPSTONE = 0
 - HAVE_FORK = 1
 - VERSION = 2.3.0-git
 - USE_LIB_ZIP = 0
 - USE_LIB_MAGIC = 0
 - DEBUGGER = 1
 - CC = gcc
 - USERCC = gcc
 - USEROSTYPE = gnulinux
 - LIBVERSION = 2.3.0-git
 - BUILD = x86_64-unknown-linux-gnu
 - HOST = x86_64-unknown-linux-gnu
 - TARGET = x86_64-unknown-linux-gnu
```

### Expected behavior

Installs to /usr/local/bin

### Actual behavior

Installs to /usr/bin

This creates problems with sdbs aren't found,

> Cannot find /usr/local/share/radare2/2.3.0-git/format/dll/mySdb.sdb

If I don't use `./sys/install.sh` and I 

    ./configure
    ./make
    ./make install

Everything works fine.

**Comment by radare** [comment] 2018-01-25 17:34
did you git clean -xdf or make clean/mrproper before running ./configure ?

just tested this and the behaviour is correct if you run configure without arguments it will be installed in /usr/local, as any other autotools program will do.

sys/install.sh works fine too, i think your problem is because you iddnt cleaned the builddir, which is the reason why i did sys/install.sh

also you can pass the prefix as argument to sys/install.sh

**Comment by davidpolverari** [comment] 2018-04-16 01:12
@EvanCarroll, did it work for you after git clean -xdf or make clean/mrproper before running ./configure? Maybe this can be closed by now.

**Comment by EvanCarroll** [comment] 2018-07-13 23:08
Nope this is still a problem. Radare is installing into `/usr/bin`.

**Comment by EvanCarroll** [comment] 2018-07-13 23:17
Here is the problem in `build.sh` you have,

```
 27 else
 28   DEFAULT_PREFIX=/usr
 29   [ -n "${PREFIX}" -a "${PREFIX}" != /usr ] && \
 30     CFGARG="${CFGARG} --with-rpath"
 31 fi
```

that should be,

```
 27 else
 28   DEFAULT_PREFIX=/usr/bin
 29   [ -n "${PREFIX}" -a "${PREFIX}" != /usr ] && \
 30     CFGARG="${CFGARG} --with-rpath"
 31 fi
```

**Comment by Maijin** [comment] 2018-07-13 23:33
https://help.github.com/articles/editing-files-in-your-repository/

**Comment by EvanCarroll** [comment] 2018-07-13 23:53
So this is this essentially where I am at, we have two possibilities.

1. Fix it.
2. Restructure it.

My contention is that I don't understand why `sys/build.sh` sets `PREFIX` **ever**. It's generated by `./configure` and it sits in `./global.mk`

```
GIT_PREFIX=https://
GIT_PREFIX=git://
PREFIX=/usr/local
LIBDIR=${PREFIX}/lib
```

`Makefile` pulls that in, 

    include global.mk

I'm not sure why we don't let that take over. If `global.mk` ever has the wrong `PREFIX` it would seem like that is in itself a bug.

**Comment by Maijin** [comment] 2018-07-14 01:17
@radare ^

**Comment by radare** [comment] 2018-07-14 08:02
Just pass the prefix as argument. I dont see any other problem. You can also override it with an env var. how many times do u change the prefix every day?

And btw, do you know about DESTDIR?

> On 14 Jul 2018, at 01:53, Evan Carroll <notifications@github.com> wrote:
> 
> So this is this essentially where I am at, we have two possibilities.
> 
> Fix it.
Fix wat
> Restructure it.
Always welcome but for wat

**Comment by EvanCarroll** [comment] 2018-07-14 15:08
> Always welcome but for wat

I'm not sure if you read the post at all with that? All I can think to do is paste it again,

My contention is that I don't understand why sys/build.sh sets PREFIX ever. It's generated by ./configure and it sits in `./global.mk`

```
GIT_PREFIX=https://
GIT_PREFIX=git://
PREFIX=/usr/local
LIBDIR=${PREFIX}/lib
```

Makefile pulls that in,

    include global.mk

I'm not sure why we don't let that take over. If global.mk ever has the wrong PREFIX it would seem like that is in itself a bug.

I just want the `acr`-generated `global.mk`'s `PREFIX` to be used. I don't ever changed it. On Ubuntu/Debian/Linux **sys/install.sh** is installing to `/usr/bin`, and that's simply wrong it should be installing to `/usr/local/bin`, `autotools`, and the `acr` are generating the right prefix. But `sys/build.sh` is screwing it up.

**Comment by radare** [comment] 2018-07-16 14:41
wtf i done see why ./configure ; make ; make isntall should isntall in /usr intead of /usr/local.  if you can send a pr fixing it i would appreciate it

**Comment by Maijin** [comment] 2018-09-28 14:52
ping 1

**Comment by EvanCarroll** [comment] 2018-09-28 17:16
I already wrote this up and provided a solution. I'm totally confused what you're trying to accomplish by rewriting autotools and no one gave any input on [the proposed solution.](https://github.com/radare/radare2/issues/9240#issuecomment-404981288)

**Comment by radare** [comment] 2018-09-29 03:04
the reason because sys/build.sh sets PREFIX it aims to be the easy way to build and install r2 in any system. so it finds where was r2 installed previously and checks where the system use to install user stuff. if you want a different prefix just pass it as argument. i dont understand what's the problem yet. the global.mk is honored all the time. if you use sys/build.sh its recompiling the whole r2 all the time, so i dont see why there must be any confussion with the environment.

**Comment by radare** [comment] 2018-09-29 03:04
feel free to send a PR for discussion

**Comment by EvanCarroll** [comment] 2018-09-29 23:32
@radare  because `sys/build.sh` does not honor `global.mk` it explicitly sets the PREFIX for all machines that are not darwin to `/usr` and then calls `./configure` with a hardcoded 

    ./configure ${CFGARG} --prefix="${PREFIX}" || exit 1

But, I do agree. It should honor `global.mk` (which would otherwise set it up properly with ./configure). But as documented above, that's not what seems to be happening (unless I'm totally missing something).

**Comment by radare** [comment] 2018-09-30 00:30
i dont understand why sys/build.sh should honor global.mk at all, because this file just defines the default values, and sys/build.sh is running configure, so its overriding the default values already. so there’s nothing to honor in global.mk if you use sys/* scripts basically

**Comment by EvanCarroll** [comment] 2018-09-30 19:35
It seems a lot has changed but it's still stupid on Debian shit is still installing to `/usr/bin/`

    cd .. && ln -fs "/usr/bin/radare2" "/usr/bin/r2"

`global.mk` has

    PREFIX=/usr/local

Which is incorrect, it should `/usr/local/bin`. `config-user.mk` has

```
DESTDIR=
PREFIX=/usr
BINDIR=/usr/bin
LIBDIR=/usr/lib
```

all of which is incorrect. So I guess since I opened this issue, someone broke `global.mk` and we're still hard-coding bad options `./configure`

**Comment by EvanCarroll** [comment] 2018-09-30 19:43
Ok, so here is the issue currently (since someone broke `global.mk`). Now we're using `config-user.mk`. If you run `./configure` vs `sys/install.sh` you get two different copies of `config-user.mk`.

```
diff config-user.mk ./new/config-user.mk 
7,13c7,13
< PREFIX=/usr
< BINDIR=/usr/bin
< LIBDIR=/usr/lib
< MANDIR=/usr/share/man
< DOCDIR=/usr/share/doc/radare2
< DATADIR=/usr/share
< INCLUDEDIR=/usr/include
---
> PREFIX=/usr/local
> BINDIR=/usr/local/bin
> LIBDIR=/usr/local/lib
> MANDIR=/usr/local/share/man
> DOCDIR=/usr/local/share/doc/radare2
> DATADIR=/usr/local/share
> INCLUDEDIR=/usr/local/include
83c83
< LDFLAGS+=-Wl,--as-needed
---
> LDFLAGS+=
```

The one at the bottom is correct. The one at the top is not correct. **The one at the top is not correct because we're providing a borked hard-coded prefix to `./configure` rather than letting it do the good work it does.**

**Comment by EvanCarroll** [comment] 2018-09-30 19:53
@radare updated all of these miraculously but please check out the last one for the actual diff.

**Comment by radare** [comment] 2018-09-30 23:08
Thts on purpose because you shouldnt have the distro pkg of r2 installed in debian and having it in local will cause more problems flr people who have it

**Comment by EvanCarroll** [comment] 2018-10-01 01:03
Regardless of your dislike for distros and packaging which I **fully** understand and get, you shouldn't be crapping on the distro and voluntary violating the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). It doesn't cause more problems installing to `/usr/local/bin`. It causes **less** problems. For example, this method fucks up apparmor profiles and generally causes security concerns. The distro thinks it has control over `/usr/bin` this is the user manually mucking with it. Moreover, aside from you wanting Radare to be installed by the user, you're removing the ability for the distro to ever install anything itself under the same name.

Just look at the FHS standard which **every** distro (mostly) follows,

>  Tertiary hierarchy for local data, **specific to this host.** Typically has further subdirectories, e.g., bin, lib, share.

^ That's you. That's why you're in `/usr/local/bin`.

I can't think of a single project other than `radare` which currently gets this wrong. You're actually overriding the defaults of GNU Make to do so.

**Comment by EvanCarroll** [comment] 2018-10-01 03:11
This bug is also the result of #6940

**Comment by radare** [comment] 2018-10-12 13:58
gnu make doesnt specifies anything about PREFIX at all. I can tell you several projects that does this wrong. and most pkgsrc maintainers will too. the thing that you are using sys/install.sh to install in your distro is not the way that it shuold be installed by a distro packager. thats why all distros use ./configure, make, etc....

If you want to use /usr/local just pass sys/install.sh /usr/local and it will work... but well, the rpath is not specified, so if you have another r2 in /usr you will get errors of mixed libs, so you need to add the --with-rpath in the configure line.

i'm fine to move to /usr/local if the distro have this in $PATH, the problem is that this is not the case for many distros and this causes more complains from users. I know FHS alreayd, no need to read about it, the reeason why im doing this is to override distro installations ebcause ALL distros ship old versions of r2, and having more than one r2 installed is most of the time not desired by the user and a root of problems when mixing versions or reporting issues for old versions when they have installed it from git but they were using the distro r2 without noticing instead.

which solution do you propose to all those notes?

**Comment by EvanCarroll** [comment] 2018-10-12 16:00
> gnu make doesnt specifies anything about `PREFIX` at all. 

[**hat's simply not true.**](https://www.gnu.org/software/make/manual/html_node/Directory-Variables.html) When you make statements like that that which just overlook **exactly** what I say without addressing it, I get the **strong** feeling you're simply not reading.

> If you want to use /usr/local just pass sys/install.sh /usr/local and it will work..

Yes, but the default should just work and it doesn't.

>  the rpath is not specified, so if you have another r2 in /usr you will get errors of mixed libs, so you need to add the --with-rpath in the configure line.

That's insanity because the `make` system should link everything against the versions it installs for example on my system,

```
 ldd /usr/local/bin/r2
	linux-vdso.so.1 (0x00007ffc8a33f000)
	libr_core.so => /usr/local/lib/libr_core.so (0x00007f9e6d2c9000)
	libr_parse.so => /usr/local/lib/libr_parse.so (0x00007f9e6d06f000)
	libr_search.so => /usr/local/lib/libr_search.so (0x00007f9e6ce68000)
	libr_cons.so => /usr/local/lib/libr_cons.so (0x00007f9e6cc44000)
	libr_config.so => /usr/local/lib/libr_config.so (0x00007f9e6ca3d000)
	libr_bin.so => /usr/local/lib/libr_bin.so (0x00007f9e6c6cc000)
	libr_debug.so => /usr/local/lib/libr_debug.so (0x00007f9e6c499000)
	libr_anal.so => /usr/local/lib/libr_anal.so (0x00007f9e6ba57000)
	libr_reg.so => /usr/local/lib/libr_reg.so (0x00007f9e6b84c000)
	libr_bp.so => /usr/local/lib/libr_bp.so (0x00007f9e6b646000)
	libr_io.so => /usr/local/lib/libr_io.so (0x00007f9e6b3c7000)
	libr_fs.so => /usr/local/lib/libr_fs.so (0x00007f9e6b186000)
	libr_asm.so => /usr/local/lib/libr_asm.so (0x00007f9e6a561000)
	libr_syscall.so => /usr/local/lib/libr_syscall.so (0x00007f9e6a35b000)
	libr_hash.so => /usr/local/lib/libr_hash.so (0x00007f9e6a14f000)
	libr_magic.so => /usr/local/lib/libr_magic.so (0x00007f9e69f3c000)
	libr_flag.so => /usr/local/lib/libr_flag.so (0x00007f9e69d34000)
	libr_egg.so => /usr/local/lib/libr_egg.so (0x00007f9e69b21000)
	libr_crypto.so => /usr/local/lib/libr_crypto.so (0x00007f9e698f7000)
	libr_util.so => /usr/local/lib/libr_util.so (0x00007f9e695f9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9e693da000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9e68fe9000)
	libr_lang.so => /usr/local/lib/libr_lang.so (0x00007f9e68de1000)
	libr_socket.so => /usr/local/lib/libr_socket.so (0x00007f9e68bd3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9e68835000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9e68631000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9e6d941000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f9e6842e000)

```

You'll see that my versions which I just plane built with `./configure; make; make install` links against r2 in `/usr/local/bin`. The **only** area for misconfiguration here is with the hand-rolled `r2pm` which builds against the headers for Radare. This is in a fact a bug though and shitty of `r2pm` but that's another issue and the point here isn't to get two versions working at the same time (which would be a walk in the park and **dirt** easy, it's simply to put the version in the right place to begin with).

For reference, two versions of `r2` (2.3 and 3.0) getting along just fine.

```
$ r2 -v
radare2 3.0.0-git 19680 @ linux-x86-64 git.2.9.0-246-g47297f6d0
commit: 47297f6d0a929893412694fffe025717f56974e6 build: 2018-09-30__14:44:50
$ /usr/bin/r2 -v
radare2 2.3.0 0 @ linux-x86-64 git.2.3.0
commit: HEAD build: 2018-02-23__17:22:33
$ /usr/local/bin/r2 -v
radare2 3.0.0-git 19680 @ linux-x86-64 git.2.9.0-246-g47297f6d0
commit: 47297f6d0a929893412694fffe025717f56974e6 build: 2018-09-30__14:44:50
```

> i'm fine to move to /usr/local if the distro have this in $PATH, the problem is that this is not the case for many distros and this causes **more complains from users.**

Nope! First, that's not the suggestion. The suggestion is to let `config-user.mk` decide. If your running of `./configure-user-mk` generates the wrong files you need to file a bug *somewhere*. The problem here is that **WE OVERRIDE THE VALUES IN `config-user.mk` BLINDLY**

> I know FHS alreayd, no need to read about it, the reeason why im doing this is to override distro installations ebcause ALL distros ship old versions of r2, and having more than one r2 installed is most of the time not desired by the user and a root of problems when mixing versions or reporting issues for old versions when they have installed it from git but they were using the distro r2 without noticing instead.

Nope! That's not the solution. **THE SOLUTION TO A DISTRO THAT MISBEHAVES IS NOT TO REQUIRE ROOT TO INSTALL AND TO OVERWRITE THE DISTRO** For fucks sake, if those files are needed by the distro and you override them you've fundamentally broken the install.

> which solution do you propose to all those notes?

You're wrong. The whole rest of the world is right. I'm just going to quote the docs for make you,

> **GNU packages should not try to guess which value should be appropriate for these variables [(like `PREFIX`)] on the system they are being installed onto: use the default settings specified here so that all GNU packages behave identically, allowing the installer to achieve any desired layout.**

If you're not open to being wrong you'll never acknowledge a solution.

* Distros install shit.
* You need to make your code not dependent on what the Distro does.
* Distros package things with a specific prefix `PREFIX=/usr`
* Users that run `./configure; make; make install` install things to a **different** prefix, `PREFIX=/usr/local`
* **EVERYTHING** does this.
* If there is a problem
* * The sane solution is to file a bug
* * * Either the software needs to be engineered to run with different versions (one installed by the distro, one installed by the user)
* * * Or. the software needs to interface with the distro to remove the distro's version
* * * Or, the software needs to request the user to uninstall the distro's version
* * * But, There is a special place in hell for blindly installing over the distros stuff and **breaking the distribution**

**Comment by radare** [comment] 2018-10-12 16:49
> On 12 Oct 2018, at 18:00, Evan Carroll <notifications@github.com> wrote:
> 
> gnu make doesnt specifies anything about PREFIX at all.
> 
> hat's simply not true. <https://www.gnu.org/software/make/manual/html_node/Directory-Variables.html> When you make statements like that that which just overlook exactly what I say without addressing it, I get the strong feeling you're simply not reading
> 
oh well, what GNU make specifies is a convention for some variable names, and DESTDIR is the only uppercase. you can’t find PREFIX because its named prefix. This is another GNUism, because in all the BSD systems and original UNIX it is using uppercase names.

is this what you are complaining about? and yes, i am reading, but maybe we are not understanding each other
> If you want to use /usr/local just pass sys/install.sh /usr/local and it will work..
> 
> Yes, but the default should just work and it doesn't
> 

So your complain here is to use /usr/local everywhere, despite the OS, right? because this only takes 1 line in a PR to get it fixed and not 2 issues and several months of discussions.

Another solution that comes to my mind is to check if /usr/local/bin is in the $PATH and then use /usr/local if so. but again, many distros and BSD systems use different paths, and /usr/local/lib is not available in the ld.config so if you install stuff there you end up having to run ldconfig again.

> the rpath is not specified, so if you have another r2 in /usr you will get errors of mixed libs, so you need to add the --with-rpath in the configure line.
> 
> That's insanity because the make system should link everything against the versions it installs for example on my system,
> 
that’s completely unrelated, the build system links against the compiled libraries inside the source directory of r2. Or at least that’s what it should do. rpath is for runtime, and its not enabled by default because it was a huge complain and a bad practice by many distros (like Gentoo), you can google for this.

>  ldd /usr/local/bin/r2
> 	linux-vdso.so.1 (0x00007ffc8a33f000)
> 	libr_core.so => /usr/local/lib/libr_core.so (0x00007f9e6d2c9000)
> 	libr_parse.so => /usr/local/lib/libr_parse.so (0x00007f9e6d06f000)
> 	libr_search.so => /usr/local/lib/libr_search.so (0x00007f9e6ce68000)
> 	libr_cons.so => /usr/local/lib/libr_cons.so (0x00007f9e6cc44000)
> 	libr_config.so => /usr/local/lib/libr_config.so (0x00007f9e6ca3d000)
> 	libr_bin.so => /usr/local/lib/libr_bin.so (0x00007f9e6c6cc000)
> 	libr_debug.so => /usr/local/lib/libr_debug.so (0x00007f9e6c499000)
> 	libr_anal.so => /usr/local/lib/libr_anal.so (0x00007f9e6ba57000)
> 	libr_reg.so => /usr/local/lib/libr_reg.so (0x00007f9e6b84c000)
> 	libr_bp.so => /usr/local/lib/libr_bp.so (0x00007f9e6b646000)
> 	libr_io.so => /usr/local/lib/libr_io.so (0x00007f9e6b3c7000)
> 	libr_fs.so => /usr/local/lib/libr_fs.so (0x00007f9e6b186000)
> 	libr_asm.so => /usr/local/lib/libr_asm.so (0x00007f9e6a561000)
> 	libr_syscall.so => /usr/local/lib/libr_syscall.so (0x00007f9e6a35b000)
> 	libr_hash.so => /usr/local/lib/libr_hash.so (0x00007f9e6a14f000)
> 	libr_magic.so => /usr/local/lib/libr_magic.so (0x00007f9e69f3c000)
> 	libr_flag.so => /usr/local/lib/libr_flag.so (0x00007f9e69d34000)
> 	libr_egg.so => /usr/local/lib/libr_egg.so (0x00007f9e69b21000)
> 	libr_crypto.so => /usr/local/lib/libr_crypto.so (0x00007f9e698f7000)
> 	libr_util.so => /usr/local/lib/libr_util.so (0x00007f9e695f9000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9e693da000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9e68fe9000)
> 	libr_lang.so => /usr/local/lib/libr_lang.so (0x00007f9e68de1000)
> 	libr_socket.so => /usr/local/lib/libr_socket.so (0x00007f9e68bd3000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9e68835000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9e68631000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f9e6d941000)
> 	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f9e6842e000)
> 
> You'll see that my versions which I just plane built with ./configure; make; make install links against r2 in /usr/local/bin. The only area for misconfiguration here is with the hand-rolled r2pm which builds against the headers for Radare. This is in a fact a bug though and shitty of r2pm but that's another issue and the point here isn't to get two versions working at the same time (which would be a walk in the park and dirt easy, it's simply to put the version in the right place to begin with).
> 
this will simply not work if you have another r2 in /usr.

r2pm have nothing to do with the headers of r2. All is up to pkg-config. so and r2pm handles multiple PKG_CONFIG_PATHs properly, or at least it should unless you say nope.

> For reference, two versions of r2 (2.3 and 3.0) getting along just fine.
> 
> $ r2 -v
> radare2 3.0.0-git 19680 @ linux-x86-64 git.2.9.0-246-g47297f6d0
> commit: 47297f6d0a929893412694fffe025717f56974e6 build: 2018-09-30__14:44:50
> $ /usr/bin/r2 -v
> radare2 2.3.0 0 @ linux-x86-64 git.2.3.0
> commit: HEAD build: 2018-02-23__17:22:33
> $ /usr/local/bin/r2 -v
> radare2 3.0.0-git 19680 @ linux-x86-64 git.2.9.0-246-g47297f6d0
> commit: 47297f6d0a929893412694fffe025717f56974e6 build: 2018-09-30__14:44:50
> i'm fine to move to /usr/local if the distro have this in $PATH, the problem is that this is not the case for many distros and this causes more complains from users.
> 
> Nope! First, that's not the suggestion. The suggestion is to let config-user.mk decide. If your running of ./configure-user-mk generates the wrong files you need to file a bug somewhere. The problem here is that WE OVERRIDE THE VALUES IN config-user.mk BLINDLY
> 
> 
what about making a PR instead of typing in uppercase?
> I know FHS alreayd, no need to read about it, the reeason why im doing this is to override distro installations ebcause ALL distros ship old versions of r2, and having more than one r2 installed is most of the time not desired by the user and a root of problems when mixing versions or reporting issues for old versions when they have installed it from git but they were using the distro r2 without noticing instead.
> 
> Nope! That's not the solution. THE SOLUTION TO A DISTRO THAT MISBEHAVES IS NOT TO REQUIRE ROOT TO INSTALL AND TO OVERWRITE THE DISTRO For fucks sake, if those files are needed by the distro and you override them you've fundamentally broken the install.
> 
sorry but none of my linux or bsd systems have /usr/local with 777, so i still need root to install in there.

again, dont speak in uppercase, no single distro should break for overwriting r2. but its true that it shouldnt overwrite files created by another pkg.. let’s say for example. i have linux systems running pkgsrc and debian pkg system at the same time, they install packages in /usr and /usr/local, so the current behaviour and what you propose will simply not work.

to make a clean install removing old files ther’es make purge, and i have never bricked any system for doing that. but again, yes, it’s dirty, so ii’m open for better solutions

> which solution do you propose to all those notes?
> 
> You're wrong. The whole rest of the world is right. I'm just going to quote the docs for make you,
> 
> GNU packages should not try to guess which value should be appropriate for these variables [(like PREFIX)] on the system they are being installed onto: use the default settings specified here so that all GNU packages behave identically, allowing the installer to achieve any desired layout.
> 

omg, you are starting to be really anoyingly despotic :D do you know that r2 is not a GNU package? in fact it is not even a package.

Funnily this statement refers to PREFIX, which should be in lowercase according to their gnu conventions.

the purpose of using sys/install.sh is to automate some stuff, like guess how many CPUs you have, which OS you have to tweak some env to get the things working without having complains from users. that script saved me hours of helping people to get their systems fixed.
> If you're not open to being wrong you'll never acknowledge a solution
> 
i’m open to recognize that im wrong, and in fact i do that several times every day, but you are not open to show your complains in a clear way.
> Distros install shit.
> You need to make your code not dependent on what the Distro does.
> Distros package things with a specific prefix PREFIX=/usr
> Users that run ./configure; make; make install install things to a different prefix, PREFIX=/usr/local
> EVERYTHING does this.
> If there is a problem
> The sane solution is to file a bug
> Either the software needs to be engineered to run with different versions (one installed by the distro, one installed by the user)
> Or. the software needs to interface with the distro to remove the distro's version
> Or, the software needs to request the user to uninstall the distro's version
> But, There is a special place in hell for blindly installing over the distros stuff and breaking the distribution

i’m still trying to understand what is the solution you propose :?

because at first it seems like you want sys/isntall.sh to use /usr/local , just right like ./configure does by default, but then you complain about config.mk which is a file that is used by the makefiles, but its behaviour is obviously modified by what the configure runs , and yes, every single variable in a makefile can be overrided by the user by passing it as argument. but not by touching config.mk, if your complain is that config.mk asumes a default prefix, then we can just remove that line and everything will work exactly the same.

My reasoning for not making sys/install.sh install in /usr is pretty clear to me and the only answer i get from you is “gnu, standards and everyone does that”, so absolutely ignoring my explanations and real use cases.

Many software packages solve this thing with a shellscript like all.bash in Go, or build.sh in capstone, etc. will you fill issues in all of them after we fix this?

I agree that having multiple versions of r2 installed should be possible, and it is possible in fact, but i’m just trying to understand your complains before getting dirty and start doing tests with things that are suposed to work.

Again, changing this will introduce issues to many users who have been assuming r2 gets in /usr because thats how it behaved for 13 years. So having checks to see what is installed and where is necessary, GNU can say whatever they want, but the reality is different.

And again, no single distro is using sys/install.sh to build their packages.

**Comment by XVilka** [comment] 2018-10-13 02:14
In fact, if you use . configure; make;make install it installs r2 in
/use/local (at least for me).

**Comment by EvanCarroll** [comment] 2018-10-14 19:06
@radare  I'm done with you. You're simply not reading.

@XVilka That's the desired effect. The problem is that `./sys/install.sh` does not. So one method will install to `/usr/bin/` the other to `/usr/local/bin`. This is because `./sys/install.sh` actually overrides what is configured with `./configure`.

**Comment by Maijin** [comment] 2018-10-14 22:39
Isn't ./sys/user.sh supposed to fullfill this?

**Comment by Maijin** [comment] 2018-10-14 22:42
And also, what about doing an actual Pull-request with the fix you propose to remove this override?

**Comment by Maijin** [comment] 2018-10-14 22:48
Oh wait I actually think that's what @radare did here https://github.com/radare/radare2/pull/11813

**Comment by radare** [comment] 2018-10-15 12:13
Assuming that i dont want to change my mind or I want to do things wrong is totally stupid. the PR i pushed removeing the PREFIX thing basically does nothing, because this variable was overriden after running configure because the config-user.mk is loaded after it. but i just pushed it because it was another of the things you complained in here, even if its dead code.

See capstone for example: https://github.com/aquynh/capstone/blob/master/make.sh#L65

So stop saying i'm the only one doing path assumptions or touching system files when running automatic shellscripts to build instead of the generic ./configure,make

I have read all your comments several times, and explained the reasons for that. i agree on changing this behaviour to not touch system files, but you didnt answered any of my comments. I have also pointed out other things that are not consistent with gnu autotools, because r2 uses ACR, not autotools. But again, let's focus on the only problem in here and not about gnu conventions. Because FHS > GNU.

Tell me how you solve the problem of installing in /usr/local without using rpath and we can make the script more interactive or show messages saying about that problem. Because your PR is basically breaking r2 on all linux distros which have r2 in /usr installed already. and having /usr/local/lib in global ldpath is a bad practice too.

**Closed** 2020-03-20 14:27 UTC
Labels: buildsystem
