### ISSUE TITLE
Use =? in visual eval editor (ve) or (vbe)

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14332] opened 2019-06-17 02:06 UTC
<img width="1256" alt="Screenshot 2019-06-17 at 04 05 52" src="https://user-images.githubusercontent.com/917142/59573872-47d2fa00-90b5-11e9-937e-705491ce25b4.png">

**Comment by radare** [comment] 2019-06-17 09:22
we can check in configNode->options

**Comment by XVilka** [comment] 2019-06-19 05:19
Should be moved to the 3.7.0 I think.

**Comment by XVilka** [comment] 2020-11-19 06:22
Duplicate of https://github.com/radareorg/radare2/issues/17940

**Closed by XVilka** 2020-11-19 06:22 UTC
Labels: consoleui, visual
